#!/bin/bash
# Copy-paste friendly setup commands
# Run each command one by one

echo "=== Odyssey ERP Database Setup Commands ==="
echo ""
echo "Copy and run these commands one by one:"
echo ""
echo "# 1. Create PostgreSQL user (enter 'odyssey' as password when prompted)"
echo "sudo -u postgres createuser -P odyssey"
echo ""
echo "# 2. Create database"
echo "sudo -u postgres createdb -O odyssey odyssey"
echo ""
echo "# 3. Verify connection (should show version)"
echo "PGPASSWORD=odyssey psql -h localhost -U odyssey -d odyssey -c 'SELECT version();'"
echo ""
echo "# 4. Run migrations"
echo "export PG_DSN='postgres://odyssey:odyssey@localhost:5432/odyssey?sslmode=disable'"
echo "make migrate-up"
echo ""
echo "# 5. Seed test data"
echo "make seed"
echo ""
echo "# 6. Start application"
echo "./run-background.sh"
echo ""
echo "# 7. Check status"
echo "./status.sh"
echo ""
echo "✅ Test Account:"
echo "   Email: admin@odyssey.local"
echo "   Password: admin123"
echo ""
echo "🌐 Access: http://localhost:8080"
