ALTER TABLE timesheets
    ADD COLUMN IF NOT EXISTS billable_rate NUMERIC(20,6) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS base_currency CHAR(3),
    ADD COLUMN IF NOT EXISTS base_amount NUMERIC(20,6),
    ADD COLUMN IF NOT EXISTS fx_rate NUMERIC(20,10),
    ADD COLUMN IF NOT EXISTS fx_rate_source TEXT,
    ADD COLUMN IF NOT EXISTS fx_rate_locked_at TIMESTAMPTZ;
