DELETE FROM role_permissions WHERE permission_id IN (SELECT id FROM permissions WHERE name LIKE 'payroll.%');
DELETE FROM permissions WHERE name LIKE 'payroll.%';
DROP FUNCTION IF EXISTS prevent_posted_payroll_line_mutation() CASCADE;
DROP FUNCTION IF EXISTS prevent_posted_payroll_run_mutation() CASCADE;
DROP TABLE IF EXISTS payroll_account_mappings;
DROP TABLE IF EXISTS payroll_payment_batches;
DROP TABLE IF EXISTS payroll_payslips;
DROP TABLE IF EXISTS payroll_run_deductions;
DROP TABLE IF EXISTS payroll_run_lines;
DROP TABLE IF EXISTS payroll_runs;
DROP TABLE IF EXISTS payroll_thr;
DROP TABLE IF EXISTS payroll_overtime;
DROP TABLE IF EXISTS payroll_adjustments;
DROP TABLE IF EXISTS payroll_recurring_components;
DROP TABLE IF EXISTS payroll_components;
DROP TABLE IF EXISTS payroll_compensation_assignments;
DROP TABLE IF EXISTS payroll_periods;
DROP TABLE IF EXISTS payroll_company_policies;
DROP TABLE IF EXISTS payroll_bpjs_rates;
DROP TABLE IF EXISTS payroll_ter_brackets;
DROP TABLE IF EXISTS payroll_ptkp_statuses;
DROP TABLE IF EXISTS payroll_rule_versions;
