DROP MATERIALIZED VIEW IF EXISTS mv_ap_aging;
DROP MATERIALIZED VIEW IF EXISTS mv_ar_aging;
DROP MATERIALIZED VIEW IF EXISTS mv_cashflow_monthly;
DROP MATERIALIZED VIEW IF EXISTS mv_pl_monthly;
DROP FUNCTION IF EXISTS analytics_aging_bucket(DATE, DATE);
