ALTER TABLE users
    ADD COLUMN IF NOT EXISTS ui_theme TEXT NOT NULL DEFAULT 'system',
    ADD COLUMN IF NOT EXISTS ui_language TEXT NOT NULL DEFAULT 'id',
    ADD COLUMN IF NOT EXISTS ui_notifications BOOLEAN NOT NULL DEFAULT TRUE;
