// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package usersdb

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountType string

const (
	AccountTypeASSET     AccountType = "ASSET"
	AccountTypeLIABILITY AccountType = "LIABILITY"
	AccountTypeEQUITY    AccountType = "EQUITY"
	AccountTypeREVENUE   AccountType = "REVENUE"
	AccountTypeEXPENSE   AccountType = "EXPENSE"
)

func (e *AccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountType(s)
	case string:
		*e = AccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountType: %T", src)
	}
	return nil
}

type NullAccountType struct {
	AccountType AccountType `json:"account_type"`
	Valid       bool        `json:"valid"` // Valid is true if AccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountType), nil
}

type AccountingPeriodStatus string

const (
	AccountingPeriodStatusOPEN       AccountingPeriodStatus = "OPEN"
	AccountingPeriodStatusSOFTCLOSED AccountingPeriodStatus = "SOFT_CLOSED"
	AccountingPeriodStatusHARDCLOSED AccountingPeriodStatus = "HARD_CLOSED"
)

func (e *AccountingPeriodStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountingPeriodStatus(s)
	case string:
		*e = AccountingPeriodStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountingPeriodStatus: %T", src)
	}
	return nil
}

type NullAccountingPeriodStatus struct {
	AccountingPeriodStatus AccountingPeriodStatus `json:"accounting_period_status"`
	Valid                  bool                   `json:"valid"` // Valid is true if AccountingPeriodStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountingPeriodStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AccountingPeriodStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountingPeriodStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountingPeriodStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountingPeriodStatus), nil
}

type BoardPackStatus string

const (
	BoardPackStatusPENDING    BoardPackStatus = "PENDING"
	BoardPackStatusINPROGRESS BoardPackStatus = "IN_PROGRESS"
	BoardPackStatusREADY      BoardPackStatus = "READY"
	BoardPackStatusFAILED     BoardPackStatus = "FAILED"
)

func (e *BoardPackStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BoardPackStatus(s)
	case string:
		*e = BoardPackStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BoardPackStatus: %T", src)
	}
	return nil
}

type NullBoardPackStatus struct {
	BoardPackStatus BoardPackStatus `json:"board_pack_status"`
	Valid           bool            `json:"valid"` // Valid is true if BoardPackStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBoardPackStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BoardPackStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BoardPackStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBoardPackStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BoardPackStatus), nil
}

type DeliveryOrderStatus string

const (
	DeliveryOrderStatusDRAFT     DeliveryOrderStatus = "DRAFT"
	DeliveryOrderStatusCONFIRMED DeliveryOrderStatus = "CONFIRMED"
	DeliveryOrderStatusINTRANSIT DeliveryOrderStatus = "IN_TRANSIT"
	DeliveryOrderStatusDELIVERED DeliveryOrderStatus = "DELIVERED"
	DeliveryOrderStatusCANCELLED DeliveryOrderStatus = "CANCELLED"
)

func (e *DeliveryOrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryOrderStatus(s)
	case string:
		*e = DeliveryOrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryOrderStatus: %T", src)
	}
	return nil
}

type NullDeliveryOrderStatus struct {
	DeliveryOrderStatus DeliveryOrderStatus `json:"delivery_order_status"`
	Valid               bool                `json:"valid"` // Valid is true if DeliveryOrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryOrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryOrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryOrderStatus), nil
}

type EliminationRunStatus string

const (
	EliminationRunStatusDRAFT     EliminationRunStatus = "DRAFT"
	EliminationRunStatusSIMULATED EliminationRunStatus = "SIMULATED"
	EliminationRunStatusPOSTED    EliminationRunStatus = "POSTED"
	EliminationRunStatusFAILED    EliminationRunStatus = "FAILED"
)

func (e *EliminationRunStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EliminationRunStatus(s)
	case string:
		*e = EliminationRunStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EliminationRunStatus: %T", src)
	}
	return nil
}

type NullEliminationRunStatus struct {
	EliminationRunStatus EliminationRunStatus `json:"elimination_run_status"`
	Valid                bool                 `json:"valid"` // Valid is true if EliminationRunStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEliminationRunStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EliminationRunStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EliminationRunStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEliminationRunStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EliminationRunStatus), nil
}

type JournalStatus string

const (
	JournalStatusPOSTED JournalStatus = "POSTED"
	JournalStatusVOID   JournalStatus = "VOID"
)

func (e *JournalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JournalStatus(s)
	case string:
		*e = JournalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JournalStatus: %T", src)
	}
	return nil
}

type NullJournalStatus struct {
	JournalStatus JournalStatus `json:"journal_status"`
	Valid         bool          `json:"valid"` // Valid is true if JournalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJournalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JournalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JournalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJournalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JournalStatus), nil
}

type PeriodCloseChecklistStatus string

const (
	PeriodCloseChecklistStatusPENDING    PeriodCloseChecklistStatus = "PENDING"
	PeriodCloseChecklistStatusINPROGRESS PeriodCloseChecklistStatus = "IN_PROGRESS"
	PeriodCloseChecklistStatusDONE       PeriodCloseChecklistStatus = "DONE"
	PeriodCloseChecklistStatusSKIPPED    PeriodCloseChecklistStatus = "SKIPPED"
)

func (e *PeriodCloseChecklistStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PeriodCloseChecklistStatus(s)
	case string:
		*e = PeriodCloseChecklistStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PeriodCloseChecklistStatus: %T", src)
	}
	return nil
}

type NullPeriodCloseChecklistStatus struct {
	PeriodCloseChecklistStatus PeriodCloseChecklistStatus `json:"period_close_checklist_status"`
	Valid                      bool                       `json:"valid"` // Valid is true if PeriodCloseChecklistStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPeriodCloseChecklistStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PeriodCloseChecklistStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PeriodCloseChecklistStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPeriodCloseChecklistStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PeriodCloseChecklistStatus), nil
}

type PeriodCloseRunStatus string

const (
	PeriodCloseRunStatusDRAFT      PeriodCloseRunStatus = "DRAFT"
	PeriodCloseRunStatusINPROGRESS PeriodCloseRunStatus = "IN_PROGRESS"
	PeriodCloseRunStatusCOMPLETED  PeriodCloseRunStatus = "COMPLETED"
	PeriodCloseRunStatusCANCELLED  PeriodCloseRunStatus = "CANCELLED"
)

func (e *PeriodCloseRunStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PeriodCloseRunStatus(s)
	case string:
		*e = PeriodCloseRunStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PeriodCloseRunStatus: %T", src)
	}
	return nil
}

type NullPeriodCloseRunStatus struct {
	PeriodCloseRunStatus PeriodCloseRunStatus `json:"period_close_run_status"`
	Valid                bool                 `json:"valid"` // Valid is true if PeriodCloseRunStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPeriodCloseRunStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PeriodCloseRunStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PeriodCloseRunStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPeriodCloseRunStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PeriodCloseRunStatus), nil
}

type PeriodStatus string

const (
	PeriodStatusOPEN   PeriodStatus = "OPEN"
	PeriodStatusCLOSED PeriodStatus = "CLOSED"
	PeriodStatusLOCKED PeriodStatus = "LOCKED"
)

func (e *PeriodStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PeriodStatus(s)
	case string:
		*e = PeriodStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PeriodStatus: %T", src)
	}
	return nil
}

type NullPeriodStatus struct {
	PeriodStatus PeriodStatus `json:"period_status"`
	Valid        bool         `json:"valid"` // Valid is true if PeriodStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPeriodStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PeriodStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PeriodStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPeriodStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PeriodStatus), nil
}

type QuotationStatus string

const (
	QuotationStatusDRAFT     QuotationStatus = "DRAFT"
	QuotationStatusSUBMITTED QuotationStatus = "SUBMITTED"
	QuotationStatusAPPROVED  QuotationStatus = "APPROVED"
	QuotationStatusREJECTED  QuotationStatus = "REJECTED"
	QuotationStatusCONVERTED QuotationStatus = "CONVERTED"
)

func (e *QuotationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuotationStatus(s)
	case string:
		*e = QuotationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for QuotationStatus: %T", src)
	}
	return nil
}

type NullQuotationStatus struct {
	QuotationStatus QuotationStatus `json:"quotation_status"`
	Valid           bool            `json:"valid"` // Valid is true if QuotationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuotationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.QuotationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuotationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuotationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuotationStatus), nil
}

type SalesOrderStatus string

const (
	SalesOrderStatusDRAFT      SalesOrderStatus = "DRAFT"
	SalesOrderStatusCONFIRMED  SalesOrderStatus = "CONFIRMED"
	SalesOrderStatusPROCESSING SalesOrderStatus = "PROCESSING"
	SalesOrderStatusCOMPLETED  SalesOrderStatus = "COMPLETED"
	SalesOrderStatusCANCELLED  SalesOrderStatus = "CANCELLED"
)

func (e *SalesOrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SalesOrderStatus(s)
	case string:
		*e = SalesOrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SalesOrderStatus: %T", src)
	}
	return nil
}

type NullSalesOrderStatus struct {
	SalesOrderStatus SalesOrderStatus `json:"sales_order_status"`
	Valid            bool             `json:"valid"` // Valid is true if SalesOrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSalesOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SalesOrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SalesOrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSalesOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SalesOrderStatus), nil
}

type VarianceSnapshotStatus string

const (
	VarianceSnapshotStatusPENDING    VarianceSnapshotStatus = "PENDING"
	VarianceSnapshotStatusINPROGRESS VarianceSnapshotStatus = "IN_PROGRESS"
	VarianceSnapshotStatusREADY      VarianceSnapshotStatus = "READY"
	VarianceSnapshotStatusFAILED     VarianceSnapshotStatus = "FAILED"
)

func (e *VarianceSnapshotStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VarianceSnapshotStatus(s)
	case string:
		*e = VarianceSnapshotStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VarianceSnapshotStatus: %T", src)
	}
	return nil
}

type NullVarianceSnapshotStatus struct {
	VarianceSnapshotStatus VarianceSnapshotStatus `json:"variance_snapshot_status"`
	Valid                  bool                   `json:"valid"` // Valid is true if VarianceSnapshotStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVarianceSnapshotStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VarianceSnapshotStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VarianceSnapshotStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVarianceSnapshotStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VarianceSnapshotStatus), nil
}

type Account struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Type      AccountType        `json:"type"`
	ParentID  pgtype.Int8        `json:"parent_id"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	IcFlag    bool               `json:"ic_flag"`
	// Tenant isolation: company-specific Chart of Accounts
	CompanyID pgtype.Int8 `json:"company_id"`
}

type AccountMap struct {
	ID             int64              `json:"id"`
	GroupID        int64              `json:"group_id"`
	CompanyID      int64              `json:"company_id"`
	LocalAccountID int64              `json:"local_account_id"`
	GroupAccountID int64              `json:"group_account_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AccountMapping struct {
	ID        int64              `json:"id"`
	Module    string             `json:"module"`
	Key       string             `json:"key"`
	AccountID int64              `json:"account_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CompanyID pgtype.Int8        `json:"company_id"`
}

type AccountingPeriod struct {
	ID           int64                  `json:"id"`
	PeriodID     int64                  `json:"period_id"`
	CompanyID    pgtype.Int8            `json:"company_id"`
	Name         string                 `json:"name"`
	StartDate    pgtype.Date            `json:"start_date"`
	EndDate      pgtype.Date            `json:"end_date"`
	Status       AccountingPeriodStatus `json:"status"`
	SoftClosedBy pgtype.Int8            `json:"soft_closed_by"`
	SoftClosedAt pgtype.Timestamptz     `json:"soft_closed_at"`
	ClosedBy     pgtype.Int8            `json:"closed_by"`
	ClosedAt     pgtype.Timestamptz     `json:"closed_at"`
	Metadata     []byte                 `json:"metadata"`
	CreatedAt    pgtype.Timestamptz     `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz     `json:"updated_at"`
}

type ApInvoice struct {
	ID         int64              `json:"id"`
	Number     string             `json:"number"`
	SupplierID int64              `json:"supplier_id"`
	GrnID      pgtype.Int8        `json:"grn_id"`
	Currency   string             `json:"currency"`
	Total      pgtype.Numeric     `json:"total"`
	Status     string             `json:"status"`
	IssuedAt   pgtype.Date        `json:"issued_at"`
	DueAt      pgtype.Date        `json:"due_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	CompanyID  pgtype.Int8        `json:"company_id"`
}

type ApPayment struct {
	ID          int64          `json:"id"`
	Number      string         `json:"number"`
	ApInvoiceID int64          `json:"ap_invoice_id"`
	Amount      pgtype.Numeric `json:"amount"`
	PaidAt      pgtype.Date    `json:"paid_at"`
	Method      string         `json:"method"`
	Note        string         `json:"note"`
}

type Approval struct {
	ID      int64              `json:"id"`
	Module  string             `json:"module"`
	RefID   pgtype.UUID        `json:"ref_id"`
	ActorID int64              `json:"actor_id"`
	Action  string             `json:"action"`
	Note    string             `json:"note"`
	At      pgtype.Timestamptz `json:"at"`
}

type ArInvoice struct {
	ID         int64              `json:"id"`
	Number     string             `json:"number"`
	CustomerID int64              `json:"customer_id"`
	SoID       pgtype.Int8        `json:"so_id"`
	Currency   string             `json:"currency"`
	Total      pgtype.Numeric     `json:"total"`
	Status     string             `json:"status"`
	DueAt      pgtype.Timestamptz `json:"due_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ArPayment struct {
	ID          int64              `json:"id"`
	Number      string             `json:"number"`
	ArInvoiceID int64              `json:"ar_invoice_id"`
	Amount      pgtype.Numeric     `json:"amount"`
	PaidAt      pgtype.Timestamptz `json:"paid_at"`
	Method      string             `json:"method"`
	Note        string             `json:"note"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID         int64              `json:"id"`
	ActorID    int64              `json:"actor_id"`
	Action     string             `json:"action"`
	Entity     string             `json:"entity"`
	EntityID   string             `json:"entity_id"`
	Meta       []byte             `json:"meta"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

type BoardPack struct {
	ID                 int64              `json:"id"`
	CompanyID          int64              `json:"company_id"`
	PeriodID           int64              `json:"period_id"`
	TemplateID         int64              `json:"template_id"`
	VarianceSnapshotID pgtype.Int8        `json:"variance_snapshot_id"`
	Status             BoardPackStatus    `json:"status"`
	GeneratedAt        pgtype.Timestamptz `json:"generated_at"`
	GeneratedBy        pgtype.Int8        `json:"generated_by"`
	FilePath           pgtype.Text        `json:"file_path"`
	FileSize           pgtype.Int8        `json:"file_size"`
	PageCount          pgtype.Int4        `json:"page_count"`
	ErrorMessage       pgtype.Text        `json:"error_message"`
	Metadata           []byte             `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type BoardPackTemplate struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Sections    []byte             `json:"sections"`
	IsDefault   bool               `json:"is_default"`
	IsActive    bool               `json:"is_active"`
	CreatedBy   int64              `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Branch struct {
	// Primary key (BIGINT for consistency)
	ID        int64              `json:"id"`
	CompanyID int64              `json:"company_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Address   string             `json:"address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Category struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	ParentID  pgtype.Int8        `json:"parent_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CompanyID pgtype.Int8        `json:"company_id"`
}

type Company struct {
	// Primary key (BIGINT for consistency)
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Address   string             `json:"address"`
	TaxID     string             `json:"tax_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ConsolGroup struct {
	ID                int64              `json:"id"`
	Name              string             `json:"name"`
	ReportingCurrency string             `json:"reporting_currency"`
	FxEnabled         bool               `json:"fx_enabled"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ConsolGroupAccount struct {
	ID        int64              `json:"id"`
	GroupID   int64              `json:"group_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Type      AccountType        `json:"type"`
	ParentID  pgtype.Int8        `json:"parent_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ConsolMember struct {
	ID        int64              `json:"id"`
	GroupID   int64              `json:"group_id"`
	CompanyID int64              `json:"company_id"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Customer struct {
	ID               int64              `json:"id"`
	Code             string             `json:"code"`
	Name             string             `json:"name"`
	CompanyID        int64              `json:"company_id"`
	Email            pgtype.Text        `json:"email"`
	Phone            pgtype.Text        `json:"phone"`
	TaxID            pgtype.Text        `json:"tax_id"`
	CreditLimit      pgtype.Numeric     `json:"credit_limit"`
	PaymentTermsDays int32              `json:"payment_terms_days"`
	AddressLine1     pgtype.Text        `json:"address_line1"`
	AddressLine2     pgtype.Text        `json:"address_line2"`
	City             pgtype.Text        `json:"city"`
	State            pgtype.Text        `json:"state"`
	PostalCode       pgtype.Text        `json:"postal_code"`
	Country          string             `json:"country"`
	IsActive         bool               `json:"is_active"`
	Notes            pgtype.Text        `json:"notes"`
	CreatedBy        int64              `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

// Delivery orders for fulfilling sales orders with inventory integration
type DeliveryOrder struct {
	ID int64 `json:"id"`
	// Unique document number in format DO-YYYYMM-#####
	DocNumber    string      `json:"doc_number"`
	CompanyID    int64       `json:"company_id"`
	SalesOrderID int64       `json:"sales_order_id"`
	WarehouseID  int64       `json:"warehouse_id"`
	CustomerID   int64       `json:"customer_id"`
	DeliveryDate pgtype.Date `json:"delivery_date"`
	// Lifecycle status: DRAFT → CONFIRMED → IN_TRANSIT → DELIVERED or CANCELLED
	Status         DeliveryOrderStatus `json:"status"`
	DriverName     pgtype.Text         `json:"driver_name"`
	VehicleNumber  pgtype.Text         `json:"vehicle_number"`
	TrackingNumber pgtype.Text         `json:"tracking_number"`
	Notes          pgtype.Text         `json:"notes"`
	CreatedBy      int64               `json:"created_by"`
	ConfirmedBy    pgtype.Int8         `json:"confirmed_by"`
	ConfirmedAt    pgtype.Timestamptz  `json:"confirmed_at"`
	DeliveredAt    pgtype.Timestamptz  `json:"delivered_at"`
	CreatedAt      pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz  `json:"updated_at"`
}

// Line items in delivery orders, linked to sales order lines
type DeliveryOrderLine struct {
	ID               int64 `json:"id"`
	DeliveryOrderID  int64 `json:"delivery_order_id"`
	SalesOrderLineID int64 `json:"sales_order_line_id"`
	ProductID        int64 `json:"product_id"`
	// Quantity planned for delivery in this DO
	QuantityToDeliver pgtype.Numeric `json:"quantity_to_deliver"`
	// Actual quantity delivered (set on confirmation)
	QuantityDelivered pgtype.Numeric     `json:"quantity_delivered"`
	Uom               string             `json:"uom"`
	UnitPrice         pgtype.Numeric     `json:"unit_price"`
	Notes             pgtype.Text        `json:"notes"`
	LineOrder         int32              `json:"line_order"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type EliminationJournalHeader struct {
	ID         int64              `json:"id"`
	GroupID    int64              `json:"group_id"`
	PeriodID   int64              `json:"period_id"`
	Status     string             `json:"status"`
	SourceLink pgtype.Text        `json:"source_link"`
	CreatedBy  int64              `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	PostedAt   pgtype.Timestamptz `json:"posted_at"`
}

type EliminationJournalLine struct {
	ID             int64              `json:"id"`
	HeaderID       int64              `json:"header_id"`
	GroupAccountID int64              `json:"group_account_id"`
	Debit          pgtype.Numeric     `json:"debit"`
	Credit         pgtype.Numeric     `json:"credit"`
	Memo           string             `json:"memo"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type EliminationRule struct {
	ID              int64              `json:"id"`
	GroupID         pgtype.Int8        `json:"group_id"`
	Name            string             `json:"name"`
	SourceCompanyID int64              `json:"source_company_id"`
	TargetCompanyID int64              `json:"target_company_id"`
	AccountSrc      string             `json:"account_src"`
	AccountTgt      string             `json:"account_tgt"`
	MatchCriteria   []byte             `json:"match_criteria"`
	IsActive        bool               `json:"is_active"`
	CreatedBy       int64              `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type EliminationRun struct {
	ID             int64                `json:"id"`
	PeriodID       int64                `json:"period_id"`
	RuleID         int64                `json:"rule_id"`
	Status         EliminationRunStatus `json:"status"`
	CreatedBy      int64                `json:"created_by"`
	CreatedAt      pgtype.Timestamptz   `json:"created_at"`
	SimulatedAt    pgtype.Timestamptz   `json:"simulated_at"`
	PostedAt       pgtype.Timestamptz   `json:"posted_at"`
	JournalEntryID pgtype.Int8          `json:"journal_entry_id"`
	Summary        []byte               `json:"summary"`
}

type FxPolicy struct {
	GroupAccountID int64              `json:"group_account_id"`
	Method         string             `json:"method"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type FxRate struct {
	AsOfDate    pgtype.Date        `json:"as_of_date"`
	Pair        string             `json:"pair"`
	AverageRate pgtype.Numeric     `json:"average_rate"`
	ClosingRate pgtype.Numeric     `json:"closing_rate"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type GlBalance struct {
	AccountID int64       `json:"account_id"`
	PeriodID  int64       `json:"period_id"`
	Opening   interface{} `json:"opening"`
	Debit     interface{} `json:"debit"`
	Credit    interface{} `json:"credit"`
	Closing   interface{} `json:"closing"`
}

type Grn struct {
	ID          int64              `json:"id"`
	Number      string             `json:"number"`
	PoID        pgtype.Int8        `json:"po_id"`
	SupplierID  int64              `json:"supplier_id"`
	WarehouseID int64              `json:"warehouse_id"`
	Status      string             `json:"status"`
	ReceivedAt  pgtype.Timestamptz `json:"received_at"`
	Note        string             `json:"note"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CompanyID   pgtype.Int8        `json:"company_id"`
}

type GrnLine struct {
	ID        int64          `json:"id"`
	GrnID     int64          `json:"grn_id"`
	ProductID int64          `json:"product_id"`
	Qty       pgtype.Numeric `json:"qty"`
	UnitCost  pgtype.Numeric `json:"unit_cost"`
}

type IcArapPair struct {
	GroupID          int64       `json:"group_id"`
	PeriodID         int64       `json:"period_id"`
	CompanyAID       pgtype.Int8 `json:"company_a_id"`
	CompanyBID       pgtype.Int8 `json:"company_b_id"`
	ArGroupAccountID int64       `json:"ar_group_account_id"`
	ApGroupAccountID int64       `json:"ap_group_account_id"`
	ArAmount         int64       `json:"ar_amount"`
	ApAmount         int64       `json:"ap_amount"`
}

type IcIntercompanyBalance struct {
	PeriodID       int64       `json:"period_id"`
	GroupID        int64       `json:"group_id"`
	CompanyID      pgtype.Int8 `json:"company_id"`
	CounterpartyID pgtype.Int8 `json:"counterparty_id"`
	GroupAccountID int64       `json:"group_account_id"`
	Balance        int64       `json:"balance"`
}

type IcRule struct {
	ID          int64              `json:"id"`
	GroupID     int64              `json:"group_id"`
	SrcGroupAcc int64              `json:"src_group_acc"`
	DstGroupAcc int64              `json:"dst_group_acc"`
	Type        string             `json:"type"`
	Enabled     bool               `json:"enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type IdempotencyKey struct {
	Key       string             `json:"key"`
	Module    string             `json:"module"`
	RefID     pgtype.UUID        `json:"ref_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type InventoryBalance struct {
	WarehouseID int64              `json:"warehouse_id"`
	ProductID   int64              `json:"product_id"`
	Qty         pgtype.Numeric     `json:"qty"`
	AvgCost     pgtype.Numeric     `json:"avg_cost"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type InventoryCard struct {
	ID          int64              `json:"id"`
	WarehouseID int64              `json:"warehouse_id"`
	ProductID   int64              `json:"product_id"`
	TxID        int64              `json:"tx_id"`
	TxCode      string             `json:"tx_code"`
	TxType      string             `json:"tx_type"`
	QtyIn       pgtype.Numeric     `json:"qty_in"`
	QtyOut      pgtype.Numeric     `json:"qty_out"`
	BalanceQty  pgtype.Numeric     `json:"balance_qty"`
	UnitCost    pgtype.Numeric     `json:"unit_cost"`
	BalanceCost pgtype.Numeric     `json:"balance_cost"`
	PostedAt    pgtype.Timestamptz `json:"posted_at"`
	Note        string             `json:"note"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type InventoryTx struct {
	ID          int64              `json:"id"`
	Code        string             `json:"code"`
	TxType      string             `json:"tx_type"`
	WarehouseID pgtype.Int8        `json:"warehouse_id"`
	RefModule   string             `json:"ref_module"`
	RefID       pgtype.UUID        `json:"ref_id"`
	Note        string             `json:"note"`
	PostedAt    pgtype.Timestamptz `json:"posted_at"`
	CreatedBy   pgtype.Int8        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CompanyID   pgtype.Int8        `json:"company_id"`
}

type InventoryTxLine struct {
	ID             int64          `json:"id"`
	TxID           int64          `json:"tx_id"`
	ProductID      int64          `json:"product_id"`
	Qty            pgtype.Numeric `json:"qty"`
	UnitCost       pgtype.Numeric `json:"unit_cost"`
	Amount         pgtype.Numeric `json:"amount"`
	SrcWarehouseID pgtype.Int8    `json:"src_warehouse_id"`
	DstWarehouseID pgtype.Int8    `json:"dst_warehouse_id"`
}

type JournalEntry struct {
	ID           int64              `json:"id"`
	Number       int64              `json:"number"`
	PeriodID     int64              `json:"period_id"`
	Date         pgtype.Date        `json:"date"`
	SourceModule string             `json:"source_module"`
	SourceID     pgtype.UUID        `json:"source_id"`
	Memo         pgtype.Text        `json:"memo"`
	PostedBy     pgtype.Int8        `json:"posted_by"`
	PostedAt     pgtype.Timestamptz `json:"posted_at"`
	Status       JournalStatus      `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type JournalLine struct {
	ID             int64              `json:"id"`
	JeID           int64              `json:"je_id"`
	AccountID      int64              `json:"account_id"`
	Debit          pgtype.Numeric     `json:"debit"`
	Credit         pgtype.Numeric     `json:"credit"`
	DimCompanyID   pgtype.Int8        `json:"dim_company_id"`
	DimBranchID    pgtype.Int8        `json:"dim_branch_id"`
	DimWarehouseID pgtype.Int8        `json:"dim_warehouse_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	IcPartyID      pgtype.Int8        `json:"ic_party_id"`
}

type MvApAging struct {
	Bucket    string      `json:"bucket"`
	CompanyID int64       `json:"company_id"`
	BranchID  int64       `json:"branch_id"`
	AsOf      interface{} `json:"as_of"`
	Amount    int64       `json:"amount"`
}

type MvArAging struct {
	Bucket    string      `json:"bucket"`
	CompanyID int64       `json:"company_id"`
	BranchID  int64       `json:"branch_id"`
	AsOf      interface{} `json:"as_of"`
	Amount    int64       `json:"amount"`
}

type MvCashflowMonthly struct {
	Period    string `json:"period"`
	CompanyID int64  `json:"company_id"`
	BranchID  int64  `json:"branch_id"`
	CashIn    int64  `json:"cash_in"`
	CashOut   int64  `json:"cash_out"`
}

type MvConsolBalance struct {
	PeriodID       int64  `json:"period_id"`
	GroupID        int64  `json:"group_id"`
	GroupAccountID int64  `json:"group_account_id"`
	LocalCcyAmt    int64  `json:"local_ccy_amt"`
	GroupCcyAmt    int64  `json:"group_ccy_amt"`
	Members        []byte `json:"members"`
}

type MvPlMonthly struct {
	Period    string `json:"period"`
	CompanyID int64  `json:"company_id"`
	BranchID  int64  `json:"branch_id"`
	Revenue   int64  `json:"revenue"`
	Cogs      int64  `json:"cogs"`
	Opex      int64  `json:"opex"`
	Net       int32  `json:"net"`
}

type Period struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	StartDate pgtype.Date        `json:"start_date"`
	EndDate   pgtype.Date        `json:"end_date"`
	Status    PeriodStatus       `json:"status"`
	ClosedAt  pgtype.Timestamptz `json:"closed_at"`
	LockedBy  pgtype.Int8        `json:"locked_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PeriodCloseChecklistItem struct {
	ID               int64                      `json:"id"`
	PeriodCloseRunID int64                      `json:"period_close_run_id"`
	Code             string                     `json:"code"`
	Label            string                     `json:"label"`
	Status           PeriodCloseChecklistStatus `json:"status"`
	AssignedTo       pgtype.Int8                `json:"assigned_to"`
	CompletedAt      pgtype.Timestamptz         `json:"completed_at"`
	Comment          pgtype.Text                `json:"comment"`
	CreatedAt        pgtype.Timestamptz         `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz         `json:"updated_at"`
}

type PeriodCloseRun struct {
	ID          int64                `json:"id"`
	CompanyID   int64                `json:"company_id"`
	PeriodID    int64                `json:"period_id"`
	Status      PeriodCloseRunStatus `json:"status"`
	CreatedBy   int64                `json:"created_by"`
	CreatedAt   pgtype.Timestamptz   `json:"created_at"`
	CompletedAt pgtype.Timestamptz   `json:"completed_at"`
	Notes       pgtype.Text          `json:"notes"`
	UpdatedAt   pgtype.Timestamptz   `json:"updated_at"`
}

type Permission struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Po struct {
	ID           int64              `json:"id"`
	Number       string             `json:"number"`
	SupplierID   int64              `json:"supplier_id"`
	Status       string             `json:"status"`
	Currency     string             `json:"currency"`
	ExpectedDate pgtype.Date        `json:"expected_date"`
	Note         string             `json:"note"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ApprovedBy   pgtype.Int8        `json:"approved_by"`
	ApprovedAt   pgtype.Timestamptz `json:"approved_at"`
	CompanyID    pgtype.Int8        `json:"company_id"`
}

type PoLine struct {
	ID        int64          `json:"id"`
	PoID      int64          `json:"po_id"`
	ProductID int64          `json:"product_id"`
	Qty       pgtype.Numeric `json:"qty"`
	Price     pgtype.Numeric `json:"price"`
	TaxID     pgtype.Int8    `json:"tax_id"`
	Note      string         `json:"note"`
}

type Pr struct {
	ID         int64              `json:"id"`
	Number     string             `json:"number"`
	SupplierID pgtype.Int8        `json:"supplier_id"`
	RequestBy  int64              `json:"request_by"`
	Status     string             `json:"status"`
	Note       string             `json:"note"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	CompanyID  pgtype.Int8        `json:"company_id"`
}

type PrLine struct {
	ID        int64          `json:"id"`
	PrID      int64          `json:"pr_id"`
	ProductID int64          `json:"product_id"`
	Qty       pgtype.Numeric `json:"qty"`
	Note      string         `json:"note"`
}

type Product struct {
	ID         int64              `json:"id"`
	Sku        string             `json:"sku"`
	Name       string             `json:"name"`
	CategoryID int64              `json:"category_id"`
	UnitID     int64              `json:"unit_id"`
	Price      pgtype.Numeric     `json:"price"`
	TaxID      pgtype.Int8        `json:"tax_id"`
	IsActive   bool               `json:"is_active"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	// Tenant isolation: company that owns this product
	CompanyID pgtype.Int8 `json:"company_id"`
}

type Quotation struct {
	ID              int64              `json:"id"`
	DocNumber       string             `json:"doc_number"`
	CompanyID       int64              `json:"company_id"`
	CustomerID      int64              `json:"customer_id"`
	QuoteDate       pgtype.Date        `json:"quote_date"`
	ValidUntil      pgtype.Date        `json:"valid_until"`
	Status          QuotationStatus    `json:"status"`
	Currency        string             `json:"currency"`
	Subtotal        pgtype.Numeric     `json:"subtotal"`
	TaxAmount       pgtype.Numeric     `json:"tax_amount"`
	TotalAmount     pgtype.Numeric     `json:"total_amount"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedBy       int64              `json:"created_by"`
	ApprovedBy      pgtype.Int8        `json:"approved_by"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
	RejectedBy      pgtype.Int8        `json:"rejected_by"`
	RejectedAt      pgtype.Timestamptz `json:"rejected_at"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type QuotationLine struct {
	ID              int64              `json:"id"`
	QuotationID     int64              `json:"quotation_id"`
	ProductID       int64              `json:"product_id"`
	Description     pgtype.Text        `json:"description"`
	Quantity        pgtype.Numeric     `json:"quantity"`
	Uom             string             `json:"uom"`
	UnitPrice       pgtype.Numeric     `json:"unit_price"`
	DiscountPercent pgtype.Numeric     `json:"discount_percent"`
	DiscountAmount  pgtype.Numeric     `json:"discount_amount"`
	TaxPercent      pgtype.Numeric     `json:"tax_percent"`
	TaxAmount       pgtype.Numeric     `json:"tax_amount"`
	LineTotal       pgtype.Numeric     `json:"line_total"`
	Notes           pgtype.Text        `json:"notes"`
	LineOrder       int32              `json:"line_order"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	RoleID       int64              `json:"role_id"`
	PermissionID int64              `json:"permission_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type SalesOrder struct {
	ID                   int64              `json:"id"`
	DocNumber            string             `json:"doc_number"`
	CompanyID            int64              `json:"company_id"`
	CustomerID           int64              `json:"customer_id"`
	QuotationID          pgtype.Int8        `json:"quotation_id"`
	OrderDate            pgtype.Date        `json:"order_date"`
	ExpectedDeliveryDate pgtype.Date        `json:"expected_delivery_date"`
	Status               SalesOrderStatus   `json:"status"`
	Currency             string             `json:"currency"`
	Subtotal             pgtype.Numeric     `json:"subtotal"`
	TaxAmount            pgtype.Numeric     `json:"tax_amount"`
	TotalAmount          pgtype.Numeric     `json:"total_amount"`
	Notes                pgtype.Text        `json:"notes"`
	CreatedBy            int64              `json:"created_by"`
	ConfirmedBy          pgtype.Int8        `json:"confirmed_by"`
	ConfirmedAt          pgtype.Timestamptz `json:"confirmed_at"`
	CancelledBy          pgtype.Int8        `json:"cancelled_by"`
	CancelledAt          pgtype.Timestamptz `json:"cancelled_at"`
	CancellationReason   pgtype.Text        `json:"cancellation_reason"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type SalesOrderLine struct {
	ID           int64          `json:"id"`
	SalesOrderID int64          `json:"sales_order_id"`
	ProductID    int64          `json:"product_id"`
	Description  pgtype.Text    `json:"description"`
	Quantity     pgtype.Numeric `json:"quantity"`
	// Total quantity delivered across all DOs (auto-updated by trigger)
	QuantityDelivered pgtype.Numeric     `json:"quantity_delivered"`
	QuantityInvoiced  pgtype.Numeric     `json:"quantity_invoiced"`
	Uom               string             `json:"uom"`
	UnitPrice         pgtype.Numeric     `json:"unit_price"`
	DiscountPercent   pgtype.Numeric     `json:"discount_percent"`
	DiscountAmount    pgtype.Numeric     `json:"discount_amount"`
	TaxPercent        pgtype.Numeric     `json:"tax_percent"`
	TaxAmount         pgtype.Numeric     `json:"tax_amount"`
	LineTotal         pgtype.Numeric     `json:"line_total"`
	Notes             pgtype.Text        `json:"notes"`
	LineOrder         int32              `json:"line_order"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        string             `json:"id"`
	UserID    int64              `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Ip        pgtype.Text        `json:"ip"`
	Ua        pgtype.Text        `json:"ua"`
}

type SourceLink struct {
	ID        int64              `json:"id"`
	Module    string             `json:"module"`
	RefID     pgtype.UUID        `json:"ref_id"`
	JeID      int64              `json:"je_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Supplier struct {
	ID       int64  `json:"id"`
	Code     string `json:"code"`
	Name     string `json:"name"`
	Phone    string `json:"phone"`
	Email    string `json:"email"`
	Address  string `json:"address"`
	IsActive bool   `json:"is_active"`
	// Tenant isolation: company that owns this supplier
	CompanyID pgtype.Int8 `json:"company_id"`
}

type Tax struct {
	ID   int64          `json:"id"`
	Code string         `json:"code"`
	Name string         `json:"name"`
	Rate pgtype.Numeric `json:"rate"`
}

type Unit struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Name         string             `json:"name"`
}

type UserRole struct {
	UserID    int64              `json:"user_id"`
	RoleID    int64              `json:"role_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Shows all sales and delivery permission assignments by role for easy verification
type VSalesDeliveryPermission struct {
	RoleName              string `json:"role_name"`
	RoleDescription       string `json:"role_description"`
	PermissionName        string `json:"permission_name"`
	PermissionDescription string `json:"permission_description"`
	Module                string `json:"module"`
}

type VarianceRule struct {
	ID               int64              `json:"id"`
	CompanyID        int64              `json:"company_id"`
	Name             string             `json:"name"`
	ComparisonType   string             `json:"comparison_type"`
	BasePeriodID     int64              `json:"base_period_id"`
	ComparePeriodID  pgtype.Int8        `json:"compare_period_id"`
	DimensionFilters []byte             `json:"dimension_filters"`
	ThresholdAmount  pgtype.Numeric     `json:"threshold_amount"`
	ThresholdPercent pgtype.Numeric     `json:"threshold_percent"`
	IsActive         bool               `json:"is_active"`
	CreatedBy        int64              `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type VarianceSnapshot struct {
	ID           int64                  `json:"id"`
	RuleID       int64                  `json:"rule_id"`
	PeriodID     int64                  `json:"period_id"`
	Status       VarianceSnapshotStatus `json:"status"`
	GeneratedAt  pgtype.Timestamptz     `json:"generated_at"`
	GeneratedBy  pgtype.Int8            `json:"generated_by"`
	ErrorMessage pgtype.Text            `json:"error_message"`
	Payload      []byte                 `json:"payload"`
	CreatedAt    pgtype.Timestamptz     `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz     `json:"updated_at"`
}

// Enriched view of delivery orders with related entity details
type VwDeliveryOrdersDetail struct {
	ID               int64               `json:"id"`
	DocNumber        string              `json:"doc_number"`
	CompanyID        int64               `json:"company_id"`
	SalesOrderID     int64               `json:"sales_order_id"`
	SalesOrderNumber string              `json:"sales_order_number"`
	WarehouseID      int64               `json:"warehouse_id"`
	WarehouseName    string              `json:"warehouse_name"`
	CustomerID       int64               `json:"customer_id"`
	CustomerName     string              `json:"customer_name"`
	DeliveryDate     pgtype.Date         `json:"delivery_date"`
	Status           DeliveryOrderStatus `json:"status"`
	DriverName       pgtype.Text         `json:"driver_name"`
	VehicleNumber    pgtype.Text         `json:"vehicle_number"`
	TrackingNumber   pgtype.Text         `json:"tracking_number"`
	Notes            pgtype.Text         `json:"notes"`
	CreatedBy        int64               `json:"created_by"`
	CreatedByName    string              `json:"created_by_name"`
	ConfirmedBy      pgtype.Int8         `json:"confirmed_by"`
	ConfirmedByName  pgtype.Text         `json:"confirmed_by_name"`
	ConfirmedAt      pgtype.Timestamptz  `json:"confirmed_at"`
	DeliveredAt      pgtype.Timestamptz  `json:"delivered_at"`
	CreatedAt        pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz  `json:"updated_at"`
	LineCount        int64               `json:"line_count"`
	TotalQuantity    int64               `json:"total_quantity"`
}

type Warehouse struct {
	// Primary key (BIGINT for consistency)
	ID        int64              `json:"id"`
	BranchID  int64              `json:"branch_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Address   string             `json:"address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
