// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const areAllReviewStepsApproved = `-- name: AreAllReviewStepsApproved :one
SELECT NOT EXISTS (
    SELECT 1
    FROM document_review_steps
    WHERE document_version_id = $1 AND status != 'APPROVED'
)
`

func (q *Queries) AreAllReviewStepsApproved(ctx context.Context, documentVersionID int64) (bool, error) {
	row := q.db.QueryRow(ctx, areAllReviewStepsApproved, documentVersionID)
	var not_exists bool
	err := row.Scan(&not_exists)
	return not_exists, err
}

const deleteDocument = `-- name: DeleteDocument :exec
UPDATE documents
SET status = 'ARCHIVED', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDocument, id)
	return err
}

const deleteDocumentACL = `-- name: DeleteDocumentACL :exec
DELETE FROM document_acls WHERE id = $1
`

func (q *Queries) DeleteDocumentACL(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDocumentACL, id)
	return err
}

const deleteDocumentLink = `-- name: DeleteDocumentLink :exec
DELETE FROM document_links WHERE id = $1
`

func (q *Queries) DeleteDocumentLink(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDocumentLink, id)
	return err
}

const getDefaultNumberingRule = `-- name: GetDefaultNumberingRule :one
SELECT id, company_id, code, name, prefix, suffix, pattern, sequence_start, sequence_current, scope, scope_id, active, created_at, created_by
FROM document_numbering_rules
WHERE company_id = $1 AND scope = 'COMPANY' AND active = true
LIMIT 1
`

func (q *Queries) GetDefaultNumberingRule(ctx context.Context, companyID int64) (DocumentNumberingRule, error) {
	row := q.db.QueryRow(ctx, getDefaultNumberingRule, companyID)
	var i DocumentNumberingRule
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.Prefix,
		&i.Suffix,
		&i.Pattern,
		&i.SequenceStart,
		&i.SequenceCurrent,
		&i.Scope,
		&i.ScopeID,
		&i.Active,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT d.id, d.company_id, d.category_id, d.classification_id, d.numbering_rule_id,
       d.document_number, d.title, d.description, d.owner_id, d.status,
       d.effective_from, d.effective_to, d.current_version_id,
       d.migration_source, d.migration_source_id,
       d.created_at, d.created_by, d.updated_at, d.updated_by,
       c.name AS category_name, cl.name AS classification_name,
       u.name AS owner_name, co.name AS company_name
FROM documents d
LEFT JOIN document_categories c ON d.category_id = c.id
LEFT JOIN document_classifications cl ON d.classification_id = cl.id
LEFT JOIN users u ON d.owner_id = u.id
LEFT JOIN companies co ON d.company_id = co.id
WHERE d.id = $1
`

type GetDocumentRow struct {
	ID                 int64              `json:"id"`
	CompanyID          int64              `json:"company_id"`
	CategoryID         pgtype.Int8        `json:"category_id"`
	ClassificationID   int64              `json:"classification_id"`
	NumberingRuleID    pgtype.Int8        `json:"numbering_rule_id"`
	DocumentNumber     string             `json:"document_number"`
	Title              string             `json:"title"`
	Description        pgtype.Text        `json:"description"`
	OwnerID            int64              `json:"owner_id"`
	Status             string             `json:"status"`
	EffectiveFrom      pgtype.Timestamptz `json:"effective_from"`
	EffectiveTo        pgtype.Timestamptz `json:"effective_to"`
	CurrentVersionID   pgtype.Int8        `json:"current_version_id"`
	MigrationSource    pgtype.Text        `json:"migration_source"`
	MigrationSourceID  pgtype.Text        `json:"migration_source_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedBy          int64              `json:"created_by"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy          int64              `json:"updated_by"`
	CategoryName       pgtype.Text        `json:"category_name"`
	ClassificationName pgtype.Text        `json:"classification_name"`
	OwnerName          pgtype.Text        `json:"owner_name"`
	CompanyName        pgtype.Text        `json:"company_name"`
}

func (q *Queries) GetDocument(ctx context.Context, id int64) (GetDocumentRow, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i GetDocumentRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CategoryID,
		&i.ClassificationID,
		&i.NumberingRuleID,
		&i.DocumentNumber,
		&i.Title,
		&i.Description,
		&i.OwnerID,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CurrentVersionID,
		&i.MigrationSource,
		&i.MigrationSourceID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.CategoryName,
		&i.ClassificationName,
		&i.OwnerName,
		&i.CompanyName,
	)
	return i, err
}

const getDocumentCategory = `-- name: GetDocumentCategory :one
SELECT id, company_id, parent_id, code, name, description, default_classification_id, numbering_rule_id, active, created_at, created_by
FROM document_categories
WHERE id = $1
`

func (q *Queries) GetDocumentCategory(ctx context.Context, id int64) (DocumentCategory, error) {
	row := q.db.QueryRow(ctx, getDocumentCategory, id)
	var i DocumentCategory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.DefaultClassificationID,
		&i.NumberingRuleID,
		&i.Active,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getDocumentClassification = `-- name: GetDocumentClassification :one
SELECT id, company_id, code, name, description, default_retention_policy_id, requires_approval, requires_signature, allowed_extensions, max_size_bytes, sort_order, active, created_at, created_by
FROM document_classifications
WHERE id = $1
`

func (q *Queries) GetDocumentClassification(ctx context.Context, id int64) (DocumentClassification, error) {
	row := q.db.QueryRow(ctx, getDocumentClassification, id)
	var i DocumentClassification
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.DefaultRetentionPolicyID,
		&i.RequiresApproval,
		&i.RequiresSignature,
		&i.AllowedExtensions,
		&i.MaxSizeBytes,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getDocumentReviewStepsForDocument = `-- name: GetDocumentReviewStepsForDocument :many

SELECT rs.id, rs.company_id, rs.document_version_id, rs.step_order, rs.name,
       rs.reviewer_role_id, rs.reviewer_user_id, rs.required_approvals, rs.status, rs.due_at, rs.created_at
FROM document_review_steps rs
JOIN document_versions dv ON dv.id = rs.document_version_id
WHERE dv.document_id = $1 AND rs.status = 'PENDING'
ORDER BY rs.step_order
`

// =============================================================================
// DOCUMENT REVIEW STEPS
// =============================================================================
func (q *Queries) GetDocumentReviewStepsForDocument(ctx context.Context, documentID int64) ([]DocumentReviewStep, error) {
	rows, err := q.db.Query(ctx, getDocumentReviewStepsForDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentReviewStep
	for rows.Next() {
		var i DocumentReviewStep
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DocumentVersionID,
			&i.StepOrder,
			&i.Name,
			&i.ReviewerRoleID,
			&i.ReviewerUserID,
			&i.RequiredApprovals,
			&i.Status,
			&i.DueAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentSignatureChallenge = `-- name: GetDocumentSignatureChallenge :one
SELECT challenge_id, company_id, document_version_id, signer_id, expiry, created_at
FROM document_signature_challenges
WHERE challenge_id = $1
`

type GetDocumentSignatureChallengeRow struct {
	ChallengeID       pgtype.UUID        `json:"challenge_id"`
	CompanyID         int64              `json:"company_id"`
	DocumentVersionID int64              `json:"document_version_id"`
	SignerID          int64              `json:"signer_id"`
	Expiry            pgtype.Timestamptz `json:"expiry"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetDocumentSignatureChallenge(ctx context.Context, challengeID pgtype.UUID) (GetDocumentSignatureChallengeRow, error) {
	row := q.db.QueryRow(ctx, getDocumentSignatureChallenge, challengeID)
	var i GetDocumentSignatureChallengeRow
	err := row.Scan(
		&i.ChallengeID,
		&i.CompanyID,
		&i.DocumentVersionID,
		&i.SignerID,
		&i.Expiry,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentVersion = `-- name: GetDocumentVersion :one
SELECT dv.id, dv.company_id, dv.document_id, dv.version_number, dv.version_label,
       dv.blob_id, dv.status, dv.classification_id, dv.change_summary,
       dv.review_snapshot, dv.approved_by, dv.approved_at, dv.effective_at,
       dv.superseded_at, dv.superseded_by_version_id, dv.created_by, dv.created_at,
       d.document_number AS document_number, d.title AS document_title,
       b.storage_key AS blob_storage_key, u.name AS created_by_name
FROM document_versions dv
LEFT JOIN documents d ON dv.document_id = d.id
LEFT JOIN storage_blobs b ON dv.blob_id = b.id
LEFT JOIN users u ON dv.created_by = u.id
WHERE dv.id = $1
`

type GetDocumentVersionRow struct {
	ID                    int64              `json:"id"`
	CompanyID             int64              `json:"company_id"`
	DocumentID            int64              `json:"document_id"`
	VersionNumber         int32              `json:"version_number"`
	VersionLabel          pgtype.Text        `json:"version_label"`
	BlobID                int64              `json:"blob_id"`
	Status                string             `json:"status"`
	ClassificationID      int64              `json:"classification_id"`
	ChangeSummary         pgtype.Text        `json:"change_summary"`
	ReviewSnapshot        []byte             `json:"review_snapshot"`
	ApprovedBy            pgtype.Int8        `json:"approved_by"`
	ApprovedAt            pgtype.Timestamptz `json:"approved_at"`
	EffectiveAt           pgtype.Timestamptz `json:"effective_at"`
	SupersededAt          pgtype.Timestamptz `json:"superseded_at"`
	SupersededByVersionID pgtype.Int8        `json:"superseded_by_version_id"`
	CreatedBy             int64              `json:"created_by"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	DocumentNumber        pgtype.Text        `json:"document_number"`
	DocumentTitle         pgtype.Text        `json:"document_title"`
	BlobStorageKey        pgtype.Text        `json:"blob_storage_key"`
	CreatedByName         pgtype.Text        `json:"created_by_name"`
}

func (q *Queries) GetDocumentVersion(ctx context.Context, id int64) (GetDocumentVersionRow, error) {
	row := q.db.QueryRow(ctx, getDocumentVersion, id)
	var i GetDocumentVersionRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocumentID,
		&i.VersionNumber,
		&i.VersionLabel,
		&i.BlobID,
		&i.Status,
		&i.ClassificationID,
		&i.ChangeSummary,
		&i.ReviewSnapshot,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.EffectiveAt,
		&i.SupersededAt,
		&i.SupersededByVersionID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DocumentNumber,
		&i.DocumentTitle,
		&i.BlobStorageKey,
		&i.CreatedByName,
	)
	return i, err
}

const getLatestDocumentVersion = `-- name: GetLatestDocumentVersion :one
SELECT dv.id, dv.company_id, dv.document_id, dv.version_number, dv.version_label,
       dv.blob_id, dv.status, dv.classification_id, dv.change_summary,
       dv.review_snapshot, dv.approved_by, dv.approved_at, dv.effective_at,
       dv.superseded_at, dv.superseded_by_version_id, dv.created_by, dv.created_at,
       d.document_number AS document_number, d.title AS document_title,
       b.storage_key AS blob_storage_key, u.name AS created_by_name
FROM document_versions dv
LEFT JOIN documents d ON dv.document_id = d.id
LEFT JOIN storage_blobs b ON dv.blob_id = b.id
LEFT JOIN users u ON dv.created_by = u.id
WHERE dv.document_id = $1
ORDER BY dv.version_number DESC
LIMIT 1
`

type GetLatestDocumentVersionRow struct {
	ID                    int64              `json:"id"`
	CompanyID             int64              `json:"company_id"`
	DocumentID            int64              `json:"document_id"`
	VersionNumber         int32              `json:"version_number"`
	VersionLabel          pgtype.Text        `json:"version_label"`
	BlobID                int64              `json:"blob_id"`
	Status                string             `json:"status"`
	ClassificationID      int64              `json:"classification_id"`
	ChangeSummary         pgtype.Text        `json:"change_summary"`
	ReviewSnapshot        []byte             `json:"review_snapshot"`
	ApprovedBy            pgtype.Int8        `json:"approved_by"`
	ApprovedAt            pgtype.Timestamptz `json:"approved_at"`
	EffectiveAt           pgtype.Timestamptz `json:"effective_at"`
	SupersededAt          pgtype.Timestamptz `json:"superseded_at"`
	SupersededByVersionID pgtype.Int8        `json:"superseded_by_version_id"`
	CreatedBy             int64              `json:"created_by"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	DocumentNumber        pgtype.Text        `json:"document_number"`
	DocumentTitle         pgtype.Text        `json:"document_title"`
	BlobStorageKey        pgtype.Text        `json:"blob_storage_key"`
	CreatedByName         pgtype.Text        `json:"created_by_name"`
}

func (q *Queries) GetLatestDocumentVersion(ctx context.Context, documentID int64) (GetLatestDocumentVersionRow, error) {
	row := q.db.QueryRow(ctx, getLatestDocumentVersion, documentID)
	var i GetLatestDocumentVersionRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocumentID,
		&i.VersionNumber,
		&i.VersionLabel,
		&i.BlobID,
		&i.Status,
		&i.ClassificationID,
		&i.ChangeSummary,
		&i.ReviewSnapshot,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.EffectiveAt,
		&i.SupersededAt,
		&i.SupersededByVersionID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DocumentNumber,
		&i.DocumentTitle,
		&i.BlobStorageKey,
		&i.CreatedByName,
	)
	return i, err
}

const getNumberingRuleForCategory = `-- name: GetNumberingRuleForCategory :one
SELECT id, company_id, code, name, prefix, suffix, pattern, sequence_start, sequence_current, scope, scope_id, active, created_at, created_by
FROM document_numbering_rules
WHERE company_id = $1 AND scope = 'CATEGORY' AND scope_id = $2 AND active = true
LIMIT 1
`

type GetNumberingRuleForCategoryParams struct {
	CompanyID int64       `json:"company_id"`
	ScopeID   pgtype.Int8 `json:"scope_id"`
}

func (q *Queries) GetNumberingRuleForCategory(ctx context.Context, arg GetNumberingRuleForCategoryParams) (DocumentNumberingRule, error) {
	row := q.db.QueryRow(ctx, getNumberingRuleForCategory, arg.CompanyID, arg.ScopeID)
	var i DocumentNumberingRule
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.Prefix,
		&i.Suffix,
		&i.Pattern,
		&i.SequenceStart,
		&i.SequenceCurrent,
		&i.Scope,
		&i.ScopeID,
		&i.Active,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getPendingDispositions = `-- name: GetPendingDispositions :many

SELECT id, company_id, document_version_id, requested_by, reason, status, approved_by, approved_at, executed_at, executed_by, execution_evidence, error_message, created_at
FROM disposition_requests
WHERE status = 'APPROVED'
ORDER BY created_at
LIMIT 50
`

// =============================================================================
// DISPOSITION REQUESTS
// =============================================================================
func (q *Queries) GetPendingDispositions(ctx context.Context) ([]DispositionRequest, error) {
	rows, err := q.db.Query(ctx, getPendingDispositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DispositionRequest
	for rows.Next() {
		var i DispositionRequest
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DocumentVersionID,
			&i.RequestedBy,
			&i.Reason,
			&i.Status,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.ExecutedAt,
			&i.ExecutedBy,
			&i.ExecutionEvidence,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStorageBlob = `-- name: GetStorageBlob :one

SELECT id, company_id, storage_key, storage_driver, bucket, size_bytes,
       checksum_sha256, declared_content_type, detected_content_type,
       encryption_metadata, malware_scan_status, malware_scan_details,
       metadata, reference_count, created_at, created_by
FROM storage_blobs
WHERE id = $1
`

// =============================================================================
// STORAGE BLOBS
// =============================================================================
func (q *Queries) GetStorageBlob(ctx context.Context, id int64) (StorageBlob, error) {
	row := q.db.QueryRow(ctx, getStorageBlob, id)
	var i StorageBlob
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.StorageKey,
		&i.StorageDriver,
		&i.Bucket,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.DeclaredContentType,
		&i.DetectedContentType,
		&i.EncryptionMetadata,
		&i.MalwareScanStatus,
		&i.MalwareScanDetails,
		&i.Metadata,
		&i.ReferenceCount,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many

SELECT role_id FROM user_roles WHERE user_id = $1
`

// =============================================================================
// USER ROLES (for ACL checking)
// =============================================================================
func (q *Queries) GetUserRoles(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var role_id int64
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasActiveLegalHold = `-- name: HasActiveLegalHold :one
SELECT EXISTS (
    SELECT 1 FROM legal_holds lh
    WHERE lh.company_id = $1 AND lh.status = 'ACTIVE'
)
`

func (q *Queries) HasActiveLegalHold(ctx context.Context, companyID int64) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveLegalHold, companyID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const incrementNumberingSequence = `-- name: IncrementNumberingSequence :exec
UPDATE document_numbering_rules
SET sequence_current = sequence_current + 1
WHERE id = $1
`

func (q *Queries) IncrementNumberingSequence(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementNumberingSequence, id)
	return err
}

const insertDocument = `-- name: InsertDocument :one

INSERT INTO documents (company_id, document_number, title, description, category_id, classification_id, numbering_rule_id, owner_id, status, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type InsertDocumentParams struct {
	CompanyID        int64       `json:"company_id"`
	DocumentNumber   string      `json:"document_number"`
	Title            string      `json:"title"`
	Description      pgtype.Text `json:"description"`
	CategoryID       pgtype.Int8 `json:"category_id"`
	ClassificationID int64       `json:"classification_id"`
	NumberingRuleID  pgtype.Int8 `json:"numbering_rule_id"`
	OwnerID          int64       `json:"owner_id"`
	Status           string      `json:"status"`
	CreatedBy        int64       `json:"created_by"`
	UpdatedBy        int64       `json:"updated_by"`
}

// =============================================================================
// DOCUMENTS
// =============================================================================
func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertDocument,
		arg.CompanyID,
		arg.DocumentNumber,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.ClassificationID,
		arg.NumberingRuleID,
		arg.OwnerID,
		arg.Status,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertDocumentACL = `-- name: InsertDocumentACL :one

INSERT INTO document_acls (company_id, document_id, classification_id, principal_type, principal_id, permission, effect, granted_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertDocumentACLParams struct {
	CompanyID        int64       `json:"company_id"`
	DocumentID       pgtype.Int8 `json:"document_id"`
	ClassificationID pgtype.Int8 `json:"classification_id"`
	PrincipalType    string      `json:"principal_type"`
	PrincipalID      int64       `json:"principal_id"`
	Permission       string      `json:"permission"`
	Effect           string      `json:"effect"`
	GrantedBy        int64       `json:"granted_by"`
}

// =============================================================================
// DOCUMENT ACLS
// =============================================================================
func (q *Queries) InsertDocumentACL(ctx context.Context, arg InsertDocumentACLParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertDocumentACL,
		arg.CompanyID,
		arg.DocumentID,
		arg.ClassificationID,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.Permission,
		arg.Effect,
		arg.GrantedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertDocumentAccessEvent = `-- name: InsertDocumentAccessEvent :exec

INSERT INTO document_access_events (company_id, document_version_id, actor_id, action, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5::inet, $6)
`

type InsertDocumentAccessEventParams struct {
	CompanyID         int64       `json:"company_id"`
	DocumentVersionID int64       `json:"document_version_id"`
	ActorID           int64       `json:"actor_id"`
	Action            string      `json:"action"`
	Column5           netip.Addr  `json:"column_5"`
	UserAgent         pgtype.Text `json:"user_agent"`
}

// =============================================================================
// DOCUMENT ACCESS EVENTS
// =============================================================================
func (q *Queries) InsertDocumentAccessEvent(ctx context.Context, arg InsertDocumentAccessEventParams) error {
	_, err := q.db.Exec(ctx, insertDocumentAccessEvent,
		arg.CompanyID,
		arg.DocumentVersionID,
		arg.ActorID,
		arg.Action,
		arg.Column5,
		arg.UserAgent,
	)
	return err
}

const insertDocumentCategory = `-- name: InsertDocumentCategory :one
INSERT INTO document_categories (company_id, parent_id, code, name, description, active, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, company_id, parent_id, code, name, description, default_classification_id, numbering_rule_id, active, created_at, created_by
`

type InsertDocumentCategoryParams struct {
	CompanyID   int64       `json:"company_id"`
	ParentID    pgtype.Int8 `json:"parent_id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Active      bool        `json:"active"`
	CreatedBy   int64       `json:"created_by"`
}

func (q *Queries) InsertDocumentCategory(ctx context.Context, arg InsertDocumentCategoryParams) (DocumentCategory, error) {
	row := q.db.QueryRow(ctx, insertDocumentCategory,
		arg.CompanyID,
		arg.ParentID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Active,
		arg.CreatedBy,
	)
	var i DocumentCategory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.DefaultClassificationID,
		&i.NumberingRuleID,
		&i.Active,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertDocumentLink = `-- name: InsertDocumentLink :one

INSERT INTO document_links (company_id, document_version_id, target_module, target_id, target_company_id, link_type, description, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertDocumentLinkParams struct {
	CompanyID         int64       `json:"company_id"`
	DocumentVersionID int64       `json:"document_version_id"`
	TargetModule      string      `json:"target_module"`
	TargetID          int64       `json:"target_id"`
	TargetCompanyID   int64       `json:"target_company_id"`
	LinkType          string      `json:"link_type"`
	Description       pgtype.Text `json:"description"`
	CreatedBy         int64       `json:"created_by"`
}

// =============================================================================
// DOCUMENT LINKS
// =============================================================================
func (q *Queries) InsertDocumentLink(ctx context.Context, arg InsertDocumentLinkParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertDocumentLink,
		arg.CompanyID,
		arg.DocumentVersionID,
		arg.TargetModule,
		arg.TargetID,
		arg.TargetCompanyID,
		arg.LinkType,
		arg.Description,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertDocumentRetention = `-- name: InsertDocumentRetention :exec

INSERT INTO document_retention (company_id, document_version_id, policy_id, trigger_date, expiry_date)
VALUES ($1, $2, $3, $4, $5)
`

type InsertDocumentRetentionParams struct {
	CompanyID         int64              `json:"company_id"`
	DocumentVersionID int64              `json:"document_version_id"`
	PolicyID          int64              `json:"policy_id"`
	TriggerDate       pgtype.Timestamptz `json:"trigger_date"`
	ExpiryDate        pgtype.Timestamptz `json:"expiry_date"`
}

// =============================================================================
// DOCUMENT RETENTION
// =============================================================================
func (q *Queries) InsertDocumentRetention(ctx context.Context, arg InsertDocumentRetentionParams) error {
	_, err := q.db.Exec(ctx, insertDocumentRetention,
		arg.CompanyID,
		arg.DocumentVersionID,
		arg.PolicyID,
		arg.TriggerDate,
		arg.ExpiryDate,
	)
	return err
}

const insertDocumentReviewStep = `-- name: InsertDocumentReviewStep :exec
INSERT INTO document_review_steps (company_id, document_version_id, step_order, name, reviewer_role_id, reviewer_user_id, required_approvals, status, due_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertDocumentReviewStepParams struct {
	CompanyID         int64              `json:"company_id"`
	DocumentVersionID int64              `json:"document_version_id"`
	StepOrder         int32              `json:"step_order"`
	Name              string             `json:"name"`
	ReviewerRoleID    pgtype.Int8        `json:"reviewer_role_id"`
	ReviewerUserID    pgtype.Int8        `json:"reviewer_user_id"`
	RequiredApprovals int32              `json:"required_approvals"`
	Status            string             `json:"status"`
	DueAt             pgtype.Timestamptz `json:"due_at"`
}

func (q *Queries) InsertDocumentReviewStep(ctx context.Context, arg InsertDocumentReviewStepParams) error {
	_, err := q.db.Exec(ctx, insertDocumentReviewStep,
		arg.CompanyID,
		arg.DocumentVersionID,
		arg.StepOrder,
		arg.Name,
		arg.ReviewerRoleID,
		arg.ReviewerUserID,
		arg.RequiredApprovals,
		arg.Status,
		arg.DueAt,
	)
	return err
}

const insertDocumentSignature = `-- name: InsertDocumentSignature :one
INSERT INTO document_signatures (company_id, document_version_id, challenge_id, signer_id, record_version, record_hash, meaning, policy_version, auth_method)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, company_id, document_version_id, challenge_id, signer_id, record_version, record_hash, meaning, policy_version, auth_method, signed_at
`

type InsertDocumentSignatureParams struct {
	CompanyID         int64       `json:"company_id"`
	DocumentVersionID int64       `json:"document_version_id"`
	ChallengeID       pgtype.UUID `json:"challenge_id"`
	SignerID          int64       `json:"signer_id"`
	RecordVersion     string      `json:"record_version"`
	RecordHash        string      `json:"record_hash"`
	Meaning           string      `json:"meaning"`
	PolicyVersion     int32       `json:"policy_version"`
	AuthMethod        string      `json:"auth_method"`
}

func (q *Queries) InsertDocumentSignature(ctx context.Context, arg InsertDocumentSignatureParams) (DocumentSignature, error) {
	row := q.db.QueryRow(ctx, insertDocumentSignature,
		arg.CompanyID,
		arg.DocumentVersionID,
		arg.ChallengeID,
		arg.SignerID,
		arg.RecordVersion,
		arg.RecordHash,
		arg.Meaning,
		arg.PolicyVersion,
		arg.AuthMethod,
	)
	var i DocumentSignature
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocumentVersionID,
		&i.ChallengeID,
		&i.SignerID,
		&i.RecordVersion,
		&i.RecordHash,
		&i.Meaning,
		&i.PolicyVersion,
		&i.AuthMethod,
		&i.SignedAt,
	)
	return i, err
}

const insertDocumentSignatureChallenge = `-- name: InsertDocumentSignatureChallenge :one

INSERT INTO document_signature_challenges (company_id, document_version_id, signer_id, expiry)
VALUES ($1, $2, $3, $4)
RETURNING challenge_id
`

type InsertDocumentSignatureChallengeParams struct {
	CompanyID         int64              `json:"company_id"`
	DocumentVersionID int64              `json:"document_version_id"`
	SignerID          int64              `json:"signer_id"`
	Expiry            pgtype.Timestamptz `json:"expiry"`
}

// =============================================================================
// DOCUMENT SIGNATURES
// =============================================================================
func (q *Queries) InsertDocumentSignatureChallenge(ctx context.Context, arg InsertDocumentSignatureChallengeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertDocumentSignatureChallenge,
		arg.CompanyID,
		arg.DocumentVersionID,
		arg.SignerID,
		arg.Expiry,
	)
	var challenge_id pgtype.UUID
	err := row.Scan(&challenge_id)
	return challenge_id, err
}

const insertDocumentVersion = `-- name: InsertDocumentVersion :one

INSERT INTO document_versions (company_id, document_id, version_number, blob_id, classification_id, change_summary, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertDocumentVersionParams struct {
	CompanyID        int64       `json:"company_id"`
	DocumentID       int64       `json:"document_id"`
	VersionNumber    int32       `json:"version_number"`
	BlobID           int64       `json:"blob_id"`
	ClassificationID int64       `json:"classification_id"`
	ChangeSummary    pgtype.Text `json:"change_summary"`
	Status           string      `json:"status"`
	CreatedBy        int64       `json:"created_by"`
}

// =============================================================================
// DOCUMENT VERSIONS
// =============================================================================
func (q *Queries) InsertDocumentVersion(ctx context.Context, arg InsertDocumentVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertDocumentVersion,
		arg.CompanyID,
		arg.DocumentID,
		arg.VersionNumber,
		arg.BlobID,
		arg.ClassificationID,
		arg.ChangeSummary,
		arg.Status,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertLegalHold = `-- name: InsertLegalHold :one

INSERT INTO legal_holds (company_id, name, description, issued_by, scope_type, scope_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertLegalHoldParams struct {
	CompanyID   int64       `json:"company_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IssuedBy    int64       `json:"issued_by"`
	ScopeType   string      `json:"scope_type"`
	ScopeID     int64       `json:"scope_id"`
}

// =============================================================================
// LEGAL HOLDS
// =============================================================================
func (q *Queries) InsertLegalHold(ctx context.Context, arg InsertLegalHoldParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertLegalHold,
		arg.CompanyID,
		arg.Name,
		arg.Description,
		arg.IssuedBy,
		arg.ScopeType,
		arg.ScopeID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertReviewDecision = `-- name: InsertReviewDecision :one

INSERT INTO document_review_decisions (company_id, review_step_id, reviewer_id, decision, comment)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertReviewDecisionParams struct {
	CompanyID    int64       `json:"company_id"`
	ReviewStepID int64       `json:"review_step_id"`
	ReviewerID   int64       `json:"reviewer_id"`
	Decision     string      `json:"decision"`
	Comment      pgtype.Text `json:"comment"`
}

// =============================================================================
// DOCUMENT REVIEW DECISIONS
// =============================================================================
func (q *Queries) InsertReviewDecision(ctx context.Context, arg InsertReviewDecisionParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertReviewDecision,
		arg.CompanyID,
		arg.ReviewStepID,
		arg.ReviewerID,
		arg.Decision,
		arg.Comment,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertStorageBlob = `-- name: InsertStorageBlob :one
INSERT INTO storage_blobs (
    company_id, storage_key, storage_driver, bucket, size_bytes, checksum_sha256, 
    declared_content_type, detected_content_type, malware_scan_status, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id
`

type InsertStorageBlobParams struct {
	CompanyID           int64       `json:"company_id"`
	StorageKey          string      `json:"storage_key"`
	StorageDriver       string      `json:"storage_driver"`
	Bucket              pgtype.Text `json:"bucket"`
	SizeBytes           int64       `json:"size_bytes"`
	ChecksumSha256      string      `json:"checksum_sha256"`
	DeclaredContentType pgtype.Text `json:"declared_content_type"`
	DetectedContentType pgtype.Text `json:"detected_content_type"`
	MalwareScanStatus   string      `json:"malware_scan_status"`
	CreatedBy           int64       `json:"created_by"`
}

func (q *Queries) InsertStorageBlob(ctx context.Context, arg InsertStorageBlobParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertStorageBlob,
		arg.CompanyID,
		arg.StorageKey,
		arg.StorageDriver,
		arg.Bucket,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.DeclaredContentType,
		arg.DetectedContentType,
		arg.MalwareScanStatus,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listDocumentACLs = `-- name: ListDocumentACLs :many
SELECT id, company_id, document_id, classification_id, principal_type, principal_id, permission, effect, granted_by, granted_at, expires_at
FROM document_acls
WHERE company_id = $1
  AND ($2::int8 IS NULL OR document_id = $2)
  AND ($3::int8 IS NULL OR classification_id = $3)
ORDER BY granted_at DESC
`

type ListDocumentACLsParams struct {
	CompanyID int64 `json:"company_id"`
	Column2   int64 `json:"column_2"`
	Column3   int64 `json:"column_3"`
}

func (q *Queries) ListDocumentACLs(ctx context.Context, arg ListDocumentACLsParams) ([]DocumentAcl, error) {
	rows, err := q.db.Query(ctx, listDocumentACLs, arg.CompanyID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentAcl
	for rows.Next() {
		var i DocumentAcl
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DocumentID,
			&i.ClassificationID,
			&i.PrincipalType,
			&i.PrincipalID,
			&i.Permission,
			&i.Effect,
			&i.GrantedBy,
			&i.GrantedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentCategories = `-- name: ListDocumentCategories :many

SELECT id, company_id, parent_id, code, name, description, default_classification_id, numbering_rule_id, active, created_at, created_by
FROM document_categories
WHERE company_id = $1
ORDER BY code
`

// =============================================================================
// DOCUMENT CATEGORIES
// =============================================================================
func (q *Queries) ListDocumentCategories(ctx context.Context, companyID int64) ([]DocumentCategory, error) {
	rows, err := q.db.Query(ctx, listDocumentCategories, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentCategory
	for rows.Next() {
		var i DocumentCategory
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ParentID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.DefaultClassificationID,
			&i.NumberingRuleID,
			&i.Active,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentClassifications = `-- name: ListDocumentClassifications :many

SELECT id, company_id, code, name, description, default_retention_policy_id, requires_approval, requires_signature, allowed_extensions, max_size_bytes, sort_order, active, created_at, created_by
FROM document_classifications
ORDER BY sort_order, code
`

// =============================================================================
// DOCUMENT CLASSIFICATIONS
// =============================================================================
func (q *Queries) ListDocumentClassifications(ctx context.Context) ([]DocumentClassification, error) {
	rows, err := q.db.Query(ctx, listDocumentClassifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentClassification
	for rows.Next() {
		var i DocumentClassification
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.DefaultRetentionPolicyID,
			&i.RequiresApproval,
			&i.RequiresSignature,
			&i.AllowedExtensions,
			&i.MaxSizeBytes,
			&i.SortOrder,
			&i.Active,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentLinks = `-- name: ListDocumentLinks :many
SELECT id, company_id, document_version_id, target_module, target_id, target_company_id, link_type, description, created_at, created_by
FROM document_links
WHERE document_version_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDocumentLinks(ctx context.Context, documentVersionID int64) ([]DocumentLink, error) {
	rows, err := q.db.Query(ctx, listDocumentLinks, documentVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentLink
	for rows.Next() {
		var i DocumentLink
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DocumentVersionID,
			&i.TargetModule,
			&i.TargetID,
			&i.TargetCompanyID,
			&i.LinkType,
			&i.Description,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentNumberingRules = `-- name: ListDocumentNumberingRules :many

SELECT id, company_id, code, name, prefix, suffix, pattern, sequence_start, sequence_current, scope, scope_id, active, created_at, created_by
FROM document_numbering_rules
WHERE company_id = $1
ORDER BY created_at
`

// =============================================================================
// DOCUMENT NUMBERING RULES
// =============================================================================
func (q *Queries) ListDocumentNumberingRules(ctx context.Context, companyID int64) ([]DocumentNumberingRule, error) {
	rows, err := q.db.Query(ctx, listDocumentNumberingRules, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentNumberingRule
	for rows.Next() {
		var i DocumentNumberingRule
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Code,
			&i.Name,
			&i.Prefix,
			&i.Suffix,
			&i.Pattern,
			&i.SequenceStart,
			&i.SequenceCurrent,
			&i.Scope,
			&i.ScopeID,
			&i.Active,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentVersions = `-- name: ListDocumentVersions :many
SELECT dv.id, dv.company_id, dv.document_id, dv.version_number, dv.version_label,
       dv.blob_id, dv.status, dv.classification_id, dv.change_summary,
       dv.review_snapshot, dv.approved_by, dv.approved_at, dv.effective_at,
       dv.superseded_at, dv.superseded_by_version_id, dv.created_by, dv.created_at,
       d.document_number AS document_number, d.title AS document_title,
       b.storage_key AS blob_storage_key, u.name AS created_by_name
FROM document_versions dv
LEFT JOIN documents d ON dv.document_id = d.id
LEFT JOIN storage_blobs b ON dv.blob_id = b.id
LEFT JOIN users u ON dv.created_by = u.id
WHERE dv.company_id = $1
  AND dv.document_id = $2
  AND ($3::text IS NULL OR dv.status = $3)
ORDER BY dv.version_number DESC
LIMIT $4 OFFSET $5
`

type ListDocumentVersionsParams struct {
	CompanyID  int64  `json:"company_id"`
	DocumentID int64  `json:"document_id"`
	Column3    string `json:"column_3"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

type ListDocumentVersionsRow struct {
	ID                    int64              `json:"id"`
	CompanyID             int64              `json:"company_id"`
	DocumentID            int64              `json:"document_id"`
	VersionNumber         int32              `json:"version_number"`
	VersionLabel          pgtype.Text        `json:"version_label"`
	BlobID                int64              `json:"blob_id"`
	Status                string             `json:"status"`
	ClassificationID      int64              `json:"classification_id"`
	ChangeSummary         pgtype.Text        `json:"change_summary"`
	ReviewSnapshot        []byte             `json:"review_snapshot"`
	ApprovedBy            pgtype.Int8        `json:"approved_by"`
	ApprovedAt            pgtype.Timestamptz `json:"approved_at"`
	EffectiveAt           pgtype.Timestamptz `json:"effective_at"`
	SupersededAt          pgtype.Timestamptz `json:"superseded_at"`
	SupersededByVersionID pgtype.Int8        `json:"superseded_by_version_id"`
	CreatedBy             int64              `json:"created_by"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	DocumentNumber        pgtype.Text        `json:"document_number"`
	DocumentTitle         pgtype.Text        `json:"document_title"`
	BlobStorageKey        pgtype.Text        `json:"blob_storage_key"`
	CreatedByName         pgtype.Text        `json:"created_by_name"`
}

func (q *Queries) ListDocumentVersions(ctx context.Context, arg ListDocumentVersionsParams) ([]ListDocumentVersionsRow, error) {
	rows, err := q.db.Query(ctx, listDocumentVersions,
		arg.CompanyID,
		arg.DocumentID,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentVersionsRow
	for rows.Next() {
		var i ListDocumentVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DocumentID,
			&i.VersionNumber,
			&i.VersionLabel,
			&i.BlobID,
			&i.Status,
			&i.ClassificationID,
			&i.ChangeSummary,
			&i.ReviewSnapshot,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.EffectiveAt,
			&i.SupersededAt,
			&i.SupersededByVersionID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DocumentNumber,
			&i.DocumentTitle,
			&i.BlobStorageKey,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT d.id, d.company_id, d.category_id, d.classification_id, d.numbering_rule_id,
       d.document_number, d.title, d.description, d.owner_id, d.status,
       d.effective_from, d.effective_to, d.current_version_id,
       d.migration_source, d.migration_source_id,
       d.created_at, d.created_by, d.updated_at, d.updated_by,
       c.name AS category_name, cl.name AS classification_name,
       u.name AS owner_name, co.name AS company_name
FROM documents d
LEFT JOIN document_categories c ON d.category_id = c.id
LEFT JOIN document_classifications cl ON d.classification_id = cl.id
LEFT JOIN users u ON d.owner_id = u.id
LEFT JOIN companies co ON d.company_id = co.id
WHERE d.company_id = $1
  AND ($2::int8 IS NULL OR d.category_id = $2)
  AND ($3::int8 IS NULL OR d.classification_id = $3)
  AND ($4::int8 IS NULL OR d.owner_id = $4)
  AND ($5::text IS NULL OR d.status = $5)
  AND ($6::text IS NULL OR d.title ILIKE '%' || $6 || '%'
       OR d.description ILIKE '%' || $6 || '%'
       OR d.document_number ILIKE '%' || $6 || '%')
ORDER BY d.updated_at DESC
LIMIT $7 OFFSET $8
`

type ListDocumentsParams struct {
	CompanyID int64  `json:"company_id"`
	Column2   int64  `json:"column_2"`
	Column3   int64  `json:"column_3"`
	Column4   int64  `json:"column_4"`
	Column5   string `json:"column_5"`
	Column6   string `json:"column_6"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type ListDocumentsRow struct {
	ID                 int64              `json:"id"`
	CompanyID          int64              `json:"company_id"`
	CategoryID         pgtype.Int8        `json:"category_id"`
	ClassificationID   int64              `json:"classification_id"`
	NumberingRuleID    pgtype.Int8        `json:"numbering_rule_id"`
	DocumentNumber     string             `json:"document_number"`
	Title              string             `json:"title"`
	Description        pgtype.Text        `json:"description"`
	OwnerID            int64              `json:"owner_id"`
	Status             string             `json:"status"`
	EffectiveFrom      pgtype.Timestamptz `json:"effective_from"`
	EffectiveTo        pgtype.Timestamptz `json:"effective_to"`
	CurrentVersionID   pgtype.Int8        `json:"current_version_id"`
	MigrationSource    pgtype.Text        `json:"migration_source"`
	MigrationSourceID  pgtype.Text        `json:"migration_source_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedBy          int64              `json:"created_by"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy          int64              `json:"updated_by"`
	CategoryName       pgtype.Text        `json:"category_name"`
	ClassificationName pgtype.Text        `json:"classification_name"`
	OwnerName          pgtype.Text        `json:"owner_name"`
	CompanyName        pgtype.Text        `json:"company_name"`
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]ListDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listDocuments,
		arg.CompanyID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsRow
	for rows.Next() {
		var i ListDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CategoryID,
			&i.ClassificationID,
			&i.NumberingRuleID,
			&i.DocumentNumber,
			&i.Title,
			&i.Description,
			&i.OwnerID,
			&i.Status,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.CurrentVersionID,
			&i.MigrationSource,
			&i.MigrationSourceID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.CategoryName,
			&i.ClassificationName,
			&i.OwnerName,
			&i.CompanyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseLegalHold = `-- name: ReleaseLegalHold :exec
UPDATE legal_holds
SET status = 'RELEASED', released_by = $2, released_at = NOW()
WHERE id = $1
`

type ReleaseLegalHoldParams struct {
	ID         int64       `json:"id"`
	ReleasedBy pgtype.Int8 `json:"released_by"`
}

func (q *Queries) ReleaseLegalHold(ctx context.Context, arg ReleaseLegalHoldParams) error {
	_, err := q.db.Exec(ctx, releaseLegalHold, arg.ID, arg.ReleasedBy)
	return err
}

const setCurrentDocumentVersion = `-- name: SetCurrentDocumentVersion :exec
UPDATE documents
SET current_version_id = $2, updated_at = NOW()
WHERE id = $1
`

type SetCurrentDocumentVersionParams struct {
	ID               int64       `json:"id"`
	CurrentVersionID pgtype.Int8 `json:"current_version_id"`
}

func (q *Queries) SetCurrentDocumentVersion(ctx context.Context, arg SetCurrentDocumentVersionParams) error {
	_, err := q.db.Exec(ctx, setCurrentDocumentVersion, arg.ID, arg.CurrentVersionID)
	return err
}

const updateDispositionExecution = `-- name: UpdateDispositionExecution :exec
UPDATE disposition_requests
SET status = $2, executed_at = $3, executed_by = $4, execution_evidence = $5, error_message = $6
WHERE id = $1
`

type UpdateDispositionExecutionParams struct {
	ID                int64              `json:"id"`
	Status            string             `json:"status"`
	ExecutedAt        pgtype.Timestamptz `json:"executed_at"`
	ExecutedBy        pgtype.Int8        `json:"executed_by"`
	ExecutionEvidence []byte             `json:"execution_evidence"`
	ErrorMessage      pgtype.Text        `json:"error_message"`
}

func (q *Queries) UpdateDispositionExecution(ctx context.Context, arg UpdateDispositionExecutionParams) error {
	_, err := q.db.Exec(ctx, updateDispositionExecution,
		arg.ID,
		arg.Status,
		arg.ExecutedAt,
		arg.ExecutedBy,
		arg.ExecutionEvidence,
		arg.ErrorMessage,
	)
	return err
}

const updateDocument = `-- name: UpdateDocument :exec
UPDATE documents
SET title = $2, description = $3, category_id = $4, classification_id = $5,
    owner_id = $6, updated_by = $7, updated_at = NOW()
WHERE id = $1
`

type UpdateDocumentParams struct {
	ID               int64       `json:"id"`
	Title            string      `json:"title"`
	Description      pgtype.Text `json:"description"`
	CategoryID       pgtype.Int8 `json:"category_id"`
	ClassificationID int64       `json:"classification_id"`
	OwnerID          int64       `json:"owner_id"`
	UpdatedBy        int64       `json:"updated_by"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) error {
	_, err := q.db.Exec(ctx, updateDocument,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.ClassificationID,
		arg.OwnerID,
		arg.UpdatedBy,
	)
	return err
}

const updateDocumentVersionStatus = `-- name: UpdateDocumentVersionStatus :exec
UPDATE document_versions
SET status = $2
WHERE id = $1
`

type UpdateDocumentVersionStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateDocumentVersionStatus(ctx context.Context, arg UpdateDocumentVersionStatusParams) error {
	_, err := q.db.Exec(ctx, updateDocumentVersionStatus, arg.ID, arg.Status)
	return err
}

const updateReviewStepStatus = `-- name: UpdateReviewStepStatus :exec
UPDATE document_review_steps
SET status = $2
WHERE id = $1
`

type UpdateReviewStepStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateReviewStepStatus(ctx context.Context, arg UpdateReviewStepStatusParams) error {
	_, err := q.db.Exec(ctx, updateReviewStepStatus, arg.ID, arg.Status)
	return err
}
