// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance_ap_q3.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPException = `-- name: CreateAPException :one
INSERT INTO ap_exceptions (
    ap_invoice_id, ap_matching_run_id, exception_type, severity, status, 
    owner_id, sla_due_at, reason, evidence, comments
) VALUES (
    $1, $2, $3, $4, $5, 
    $6, $7, $8, $9, $10
) RETURNING id
`

type CreateAPExceptionParams struct {
	ApInvoiceID     int64              `json:"ap_invoice_id"`
	ApMatchingRunID pgtype.Int8        `json:"ap_matching_run_id"`
	ExceptionType   string             `json:"exception_type"`
	Severity        string             `json:"severity"`
	Status          string             `json:"status"`
	OwnerID         pgtype.Int8        `json:"owner_id"`
	SlaDueAt        pgtype.Timestamptz `json:"sla_due_at"`
	Reason          string             `json:"reason"`
	Evidence        pgtype.Text        `json:"evidence"`
	Comments        []string           `json:"comments"`
}

func (q *Queries) CreateAPException(ctx context.Context, arg CreateAPExceptionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAPException,
		arg.ApInvoiceID,
		arg.ApMatchingRunID,
		arg.ExceptionType,
		arg.Severity,
		arg.Status,
		arg.OwnerID,
		arg.SlaDueAt,
		arg.Reason,
		arg.Evidence,
		arg.Comments,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAPException = `-- name: GetAPException :one
SELECT 
    id, ap_invoice_id, ap_matching_run_id, exception_type, severity, status,
    owner_id, sla_due_at, reason, evidence, comments,
    created_at, updated_at, resolved_at, resolved_by
FROM ap_exceptions
WHERE id = $1
`

func (q *Queries) GetAPException(ctx context.Context, id int64) (ApException, error) {
	row := q.db.QueryRow(ctx, getAPException, id)
	var i ApException
	err := row.Scan(
		&i.ID,
		&i.ApInvoiceID,
		&i.ApMatchingRunID,
		&i.ExceptionType,
		&i.Severity,
		&i.Status,
		&i.OwnerID,
		&i.SlaDueAt,
		&i.Reason,
		&i.Evidence,
		&i.Comments,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
	)
	return i, err
}

const getLatestMatchingRun = `-- name: GetLatestMatchingRun :one
SELECT 
    id, ap_invoice_id, policy_id, status,
    invoice_total, po_total, grn_total,
    reasons, action_recommended, run_at, run_by
FROM ap_matching_runs
WHERE ap_invoice_id = $1
ORDER BY run_at DESC
LIMIT 1
`

func (q *Queries) GetLatestMatchingRun(ctx context.Context, apInvoiceID int64) (ApMatchingRun, error) {
	row := q.db.QueryRow(ctx, getLatestMatchingRun, apInvoiceID)
	var i ApMatchingRun
	err := row.Scan(
		&i.ID,
		&i.ApInvoiceID,
		&i.PolicyID,
		&i.Status,
		&i.InvoiceTotal,
		&i.PoTotal,
		&i.GrnTotal,
		&i.Reasons,
		&i.ActionRecommended,
		&i.RunAt,
		&i.RunBy,
	)
	return i, err
}

const listAPExceptions = `-- name: ListAPExceptions :many
SELECT 
    id, ap_invoice_id, ap_matching_run_id, exception_type, severity, status,
    owner_id, sla_due_at, reason, evidence, comments,
    created_at, updated_at, resolved_at, resolved_by
FROM ap_exceptions
WHERE 
    ($1::TEXT = '' OR status = $1)
    AND ($2::BIGINT = 0 OR owner_id = $2)
    AND ($3::BIGINT = 0 OR ap_invoice_id = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListAPExceptionsParams struct {
	Column1 string `json:"column_1"`
	Column2 int64  `json:"column_2"`
	Column3 int64  `json:"column_3"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListAPExceptions(ctx context.Context, arg ListAPExceptionsParams) ([]ApException, error) {
	rows, err := q.db.Query(ctx, listAPExceptions,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApException
	for rows.Next() {
		var i ApException
		if err := rows.Scan(
			&i.ID,
			&i.ApInvoiceID,
			&i.ApMatchingRunID,
			&i.ExceptionType,
			&i.Severity,
			&i.Status,
			&i.OwnerID,
			&i.SlaDueAt,
			&i.Reason,
			&i.Evidence,
			&i.Comments,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
			&i.ResolvedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPExceptionStatus = `-- name: UpdateAPExceptionStatus :exec
UPDATE ap_exceptions
SET 
    status = $2,
    resolved_at = CASE WHEN $2 IN ('RESOLVED', 'REJECTED') THEN NOW() ELSE resolved_at END,
    resolved_by = CASE WHEN $2 IN ('RESOLVED', 'REJECTED') THEN $3 ELSE resolved_by END,
    updated_at = NOW()
WHERE id = $1
`

type UpdateAPExceptionStatusParams struct {
	ID         int64       `json:"id"`
	Status     string      `json:"status"`
	ResolvedBy pgtype.Int8 `json:"resolved_by"`
}

func (q *Queries) UpdateAPExceptionStatus(ctx context.Context, arg UpdateAPExceptionStatusParams) error {
	_, err := q.db.Exec(ctx, updateAPExceptionStatus, arg.ID, arg.Status, arg.ResolvedBy)
	return err
}
