// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance_treasury_export.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateTreasuryPaymentBatchExport = `-- name: UpdateTreasuryPaymentBatchExport :one
UPDATE treasury_payment_batches
SET status = 'EXPORTED',
    exported_file_hash = $2,
    exported_by = $3,
    exported_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, company_id, reference_code, status, currency, total_amount, revision_number, proposed_by, approved_by, approved_at, created_at, updated_at, exported_file_hash, exported_at, exported_by, settled_at, settled_by, payment_connection_id, source_bank_account_id
`

type UpdateTreasuryPaymentBatchExportParams struct {
	ID               int64       `json:"id"`
	ExportedFileHash pgtype.Text `json:"exported_file_hash"`
	ExportedBy       pgtype.Int8 `json:"exported_by"`
}

func (q *Queries) UpdateTreasuryPaymentBatchExport(ctx context.Context, arg UpdateTreasuryPaymentBatchExportParams) (TreasuryPaymentBatch, error) {
	row := q.db.QueryRow(ctx, updateTreasuryPaymentBatchExport, arg.ID, arg.ExportedFileHash, arg.ExportedBy)
	var i TreasuryPaymentBatch
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ReferenceCode,
		&i.Status,
		&i.Currency,
		&i.TotalAmount,
		&i.RevisionNumber,
		&i.ProposedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExportedFileHash,
		&i.ExportedAt,
		&i.ExportedBy,
		&i.SettledAt,
		&i.SettledBy,
		&i.PaymentConnectionID,
		&i.SourceBankAccountID,
	)
	return i, err
}
