// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance_forecasting.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createForecastAdjustment = `-- name: CreateForecastAdjustment :one
INSERT INTO forecast_adjustments (company_id, scenario_id, adjustment_type, description, amount, currency, expected_date)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, company_id, scenario_id, adjustment_type, description, amount, currency, expected_date, created_at, updated_at
`

type CreateForecastAdjustmentParams struct {
	CompanyID      int64          `json:"company_id"`
	ScenarioID     int64          `json:"scenario_id"`
	AdjustmentType string         `json:"adjustment_type"`
	Description    string         `json:"description"`
	Amount         pgtype.Numeric `json:"amount"`
	Currency       string         `json:"currency"`
	ExpectedDate   pgtype.Date    `json:"expected_date"`
}

func (q *Queries) CreateForecastAdjustment(ctx context.Context, arg CreateForecastAdjustmentParams) (ForecastAdjustment, error) {
	row := q.db.QueryRow(ctx, createForecastAdjustment,
		arg.CompanyID,
		arg.ScenarioID,
		arg.AdjustmentType,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.ExpectedDate,
	)
	var i ForecastAdjustment
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ScenarioID,
		&i.AdjustmentType,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.ExpectedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createForecastDailyBucket = `-- name: CreateForecastDailyBucket :one
INSERT INTO forecast_daily_buckets (run_id, bank_account_id, currency, bucket_date, opening_balance, total_inflow, total_outflow, closing_balance)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, run_id, bank_account_id, currency, bucket_date, opening_balance, total_inflow, total_outflow, closing_balance, created_at
`

type CreateForecastDailyBucketParams struct {
	RunID          int64          `json:"run_id"`
	BankAccountID  pgtype.Int8    `json:"bank_account_id"`
	Currency       string         `json:"currency"`
	BucketDate     pgtype.Date    `json:"bucket_date"`
	OpeningBalance pgtype.Numeric `json:"opening_balance"`
	TotalInflow    pgtype.Numeric `json:"total_inflow"`
	TotalOutflow   pgtype.Numeric `json:"total_outflow"`
	ClosingBalance pgtype.Numeric `json:"closing_balance"`
}

func (q *Queries) CreateForecastDailyBucket(ctx context.Context, arg CreateForecastDailyBucketParams) (ForecastDailyBucket, error) {
	row := q.db.QueryRow(ctx, createForecastDailyBucket,
		arg.RunID,
		arg.BankAccountID,
		arg.Currency,
		arg.BucketDate,
		arg.OpeningBalance,
		arg.TotalInflow,
		arg.TotalOutflow,
		arg.ClosingBalance,
	)
	var i ForecastDailyBucket
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.BankAccountID,
		&i.Currency,
		&i.BucketDate,
		&i.OpeningBalance,
		&i.TotalInflow,
		&i.TotalOutflow,
		&i.ClosingBalance,
		&i.CreatedAt,
	)
	return i, err
}

const createForecastRun = `-- name: CreateForecastRun :one
INSERT INTO forecast_runs (company_id, scenario_id, status, fx_snapshot)
VALUES ($1, $2, $3, $4)
RETURNING id, company_id, scenario_id, status, fx_snapshot, completed_at, error_details, created_at
`

type CreateForecastRunParams struct {
	CompanyID  int64  `json:"company_id"`
	ScenarioID int64  `json:"scenario_id"`
	Status     string `json:"status"`
	FxSnapshot []byte `json:"fx_snapshot"`
}

func (q *Queries) CreateForecastRun(ctx context.Context, arg CreateForecastRunParams) (ForecastRun, error) {
	row := q.db.QueryRow(ctx, createForecastRun,
		arg.CompanyID,
		arg.ScenarioID,
		arg.Status,
		arg.FxSnapshot,
	)
	var i ForecastRun
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ScenarioID,
		&i.Status,
		&i.FxSnapshot,
		&i.CompletedAt,
		&i.ErrorDetails,
		&i.CreatedAt,
	)
	return i, err
}

const createForecastScenario = `-- name: CreateForecastScenario :one
INSERT INTO forecast_scenarios (company_id, name, policy_version)
VALUES ($1, $2, $3)
RETURNING id, company_id, name, policy_version, created_at, updated_at
`

type CreateForecastScenarioParams struct {
	CompanyID     int64  `json:"company_id"`
	Name          string `json:"name"`
	PolicyVersion string `json:"policy_version"`
}

func (q *Queries) CreateForecastScenario(ctx context.Context, arg CreateForecastScenarioParams) (ForecastScenario, error) {
	row := q.db.QueryRow(ctx, createForecastScenario, arg.CompanyID, arg.Name, arg.PolicyVersion)
	var i ForecastScenario
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createForecastSourceLine = `-- name: CreateForecastSourceLine :one
INSERT INTO forecast_source_lines (run_id, daily_bucket_id, source_type, source_ref, amount, currency, expected_date, certainty)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, run_id, daily_bucket_id, source_type, source_ref, amount, currency, expected_date, certainty, created_at
`

type CreateForecastSourceLineParams struct {
	RunID         int64          `json:"run_id"`
	DailyBucketID int64          `json:"daily_bucket_id"`
	SourceType    string         `json:"source_type"`
	SourceRef     string         `json:"source_ref"`
	Amount        pgtype.Numeric `json:"amount"`
	Currency      string         `json:"currency"`
	ExpectedDate  pgtype.Date    `json:"expected_date"`
	Certainty     string         `json:"certainty"`
}

func (q *Queries) CreateForecastSourceLine(ctx context.Context, arg CreateForecastSourceLineParams) (ForecastSourceLine, error) {
	row := q.db.QueryRow(ctx, createForecastSourceLine,
		arg.RunID,
		arg.DailyBucketID,
		arg.SourceType,
		arg.SourceRef,
		arg.Amount,
		arg.Currency,
		arg.ExpectedDate,
		arg.Certainty,
	)
	var i ForecastSourceLine
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.DailyBucketID,
		&i.SourceType,
		&i.SourceRef,
		&i.Amount,
		&i.Currency,
		&i.ExpectedDate,
		&i.Certainty,
		&i.CreatedAt,
	)
	return i, err
}

const getForecastRun = `-- name: GetForecastRun :one
SELECT id, company_id, scenario_id, status, fx_snapshot, completed_at, error_details, created_at FROM forecast_runs WHERE id = $1
`

func (q *Queries) GetForecastRun(ctx context.Context, id int64) (ForecastRun, error) {
	row := q.db.QueryRow(ctx, getForecastRun, id)
	var i ForecastRun
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ScenarioID,
		&i.Status,
		&i.FxSnapshot,
		&i.CompletedAt,
		&i.ErrorDetails,
		&i.CreatedAt,
	)
	return i, err
}

const getForecastScenario = `-- name: GetForecastScenario :one
SELECT id, company_id, name, policy_version, created_at, updated_at FROM forecast_scenarios WHERE id = $1
`

func (q *Queries) GetForecastScenario(ctx context.Context, id int64) (ForecastScenario, error) {
	row := q.db.QueryRow(ctx, getForecastScenario, id)
	var i ForecastScenario
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listForecastAdjustments = `-- name: ListForecastAdjustments :many
SELECT id, company_id, scenario_id, adjustment_type, description, amount, currency, expected_date, created_at, updated_at FROM forecast_adjustments WHERE scenario_id = $1
`

func (q *Queries) ListForecastAdjustments(ctx context.Context, scenarioID int64) ([]ForecastAdjustment, error) {
	rows, err := q.db.Query(ctx, listForecastAdjustments, scenarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForecastAdjustment
	for rows.Next() {
		var i ForecastAdjustment
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ScenarioID,
			&i.AdjustmentType,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.ExpectedDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForecastDailyBuckets = `-- name: ListForecastDailyBuckets :many
SELECT id, run_id, bank_account_id, currency, bucket_date, opening_balance, total_inflow, total_outflow, closing_balance, created_at FROM forecast_daily_buckets WHERE run_id = $1 ORDER BY bucket_date
`

func (q *Queries) ListForecastDailyBuckets(ctx context.Context, runID int64) ([]ForecastDailyBucket, error) {
	rows, err := q.db.Query(ctx, listForecastDailyBuckets, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForecastDailyBucket
	for rows.Next() {
		var i ForecastDailyBucket
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.BankAccountID,
			&i.Currency,
			&i.BucketDate,
			&i.OpeningBalance,
			&i.TotalInflow,
			&i.TotalOutflow,
			&i.ClosingBalance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForecastScenarios = `-- name: ListForecastScenarios :many
SELECT id, company_id, name, policy_version, created_at, updated_at FROM forecast_scenarios WHERE company_id = $1 ORDER BY id
`

func (q *Queries) ListForecastScenarios(ctx context.Context, companyID int64) ([]ForecastScenario, error) {
	rows, err := q.db.Query(ctx, listForecastScenarios, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForecastScenario
	for rows.Next() {
		var i ForecastScenario
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.PolicyVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForecastSourceLines = `-- name: ListForecastSourceLines :many
SELECT id, run_id, daily_bucket_id, source_type, source_ref, amount, currency, expected_date, certainty, created_at FROM forecast_source_lines WHERE run_id = $1 AND daily_bucket_id = $2
`

type ListForecastSourceLinesParams struct {
	RunID         int64 `json:"run_id"`
	DailyBucketID int64 `json:"daily_bucket_id"`
}

func (q *Queries) ListForecastSourceLines(ctx context.Context, arg ListForecastSourceLinesParams) ([]ForecastSourceLine, error) {
	rows, err := q.db.Query(ctx, listForecastSourceLines, arg.RunID, arg.DailyBucketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForecastSourceLine
	for rows.Next() {
		var i ForecastSourceLine
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.DailyBucketID,
			&i.SourceType,
			&i.SourceRef,
			&i.Amount,
			&i.Currency,
			&i.ExpectedDate,
			&i.Certainty,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateForecastRunStatus = `-- name: UpdateForecastRunStatus :exec
UPDATE forecast_runs SET status = $2, completed_at = $3, error_details = $4 WHERE id = $1
`

type UpdateForecastRunStatusParams struct {
	ID           int64              `json:"id"`
	Status       string             `json:"status"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	ErrorDetails pgtype.Text        `json:"error_details"`
}

func (q *Queries) UpdateForecastRunStatus(ctx context.Context, arg UpdateForecastRunStatusParams) error {
	_, err := q.db.Exec(ctx, updateForecastRunStatus,
		arg.ID,
		arg.Status,
		arg.CompletedAt,
		arg.ErrorDetails,
	)
	return err
}
