// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance_ap_q2.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMatchingPolicy = `-- name: CreateMatchingPolicy :one
INSERT INTO ap_matching_policies (
    name, company_id, supplier_id, category_id,
    qty_tolerance_pct, price_tolerance_pct, tax_tolerance_pct,
    freight_tolerance_pct, total_tolerance_amt,
    effective_from, effective_to
) VALUES (
    $1, $2, $3, $4, 
    $5, $6, $7, 
    $8, $9, 
    $10, $11
) RETURNING id
`

type CreateMatchingPolicyParams struct {
	Name                string         `json:"name"`
	CompanyID           pgtype.Int8    `json:"company_id"`
	SupplierID          pgtype.Int8    `json:"supplier_id"`
	CategoryID          pgtype.Int8    `json:"category_id"`
	QtyTolerancePct     pgtype.Numeric `json:"qty_tolerance_pct"`
	PriceTolerancePct   pgtype.Numeric `json:"price_tolerance_pct"`
	TaxTolerancePct     pgtype.Numeric `json:"tax_tolerance_pct"`
	FreightTolerancePct pgtype.Numeric `json:"freight_tolerance_pct"`
	TotalToleranceAmt   pgtype.Numeric `json:"total_tolerance_amt"`
	EffectiveFrom       pgtype.Date    `json:"effective_from"`
	EffectiveTo         pgtype.Date    `json:"effective_to"`
}

func (q *Queries) CreateMatchingPolicy(ctx context.Context, arg CreateMatchingPolicyParams) (int64, error) {
	row := q.db.QueryRow(ctx, createMatchingPolicy,
		arg.Name,
		arg.CompanyID,
		arg.SupplierID,
		arg.CategoryID,
		arg.QtyTolerancePct,
		arg.PriceTolerancePct,
		arg.TaxTolerancePct,
		arg.FreightTolerancePct,
		arg.TotalToleranceAmt,
		arg.EffectiveFrom,
		arg.EffectiveTo,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createMatchingRun = `-- name: CreateMatchingRun :one
INSERT INTO ap_matching_runs (
    ap_invoice_id, policy_id, status, 
    invoice_total, po_total, grn_total,
    reasons, action_recommended, run_by
) VALUES (
    $1, $2, $3, 
    $4, $5, $6,
    $7, $8, $9
) RETURNING id
`

type CreateMatchingRunParams struct {
	ApInvoiceID       int64          `json:"ap_invoice_id"`
	PolicyID          pgtype.Int8    `json:"policy_id"`
	Status            string         `json:"status"`
	InvoiceTotal      pgtype.Numeric `json:"invoice_total"`
	PoTotal           pgtype.Numeric `json:"po_total"`
	GrnTotal          pgtype.Numeric `json:"grn_total"`
	Reasons           []string       `json:"reasons"`
	ActionRecommended string         `json:"action_recommended"`
	RunBy             pgtype.Int8    `json:"run_by"`
}

func (q *Queries) CreateMatchingRun(ctx context.Context, arg CreateMatchingRunParams) (int64, error) {
	row := q.db.QueryRow(ctx, createMatchingRun,
		arg.ApInvoiceID,
		arg.PolicyID,
		arg.Status,
		arg.InvoiceTotal,
		arg.PoTotal,
		arg.GrnTotal,
		arg.Reasons,
		arg.ActionRecommended,
		arg.RunBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createMatchingRunLine = `-- name: CreateMatchingRunLine :one
INSERT INTO ap_matching_run_lines (
    ap_matching_run_id, ap_invoice_line_id, po_line_id, grn_line_id,
    invoice_qty, invoice_price, po_qty, po_price, grn_qty,
    status, reasons
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9,
    $10, $11
) RETURNING id
`

type CreateMatchingRunLineParams struct {
	ApMatchingRunID int64          `json:"ap_matching_run_id"`
	ApInvoiceLineID int64          `json:"ap_invoice_line_id"`
	PoLineID        pgtype.Int8    `json:"po_line_id"`
	GrnLineID       pgtype.Int8    `json:"grn_line_id"`
	InvoiceQty      pgtype.Numeric `json:"invoice_qty"`
	InvoicePrice    pgtype.Numeric `json:"invoice_price"`
	PoQty           pgtype.Numeric `json:"po_qty"`
	PoPrice         pgtype.Numeric `json:"po_price"`
	GrnQty          pgtype.Numeric `json:"grn_qty"`
	Status          string         `json:"status"`
	Reasons         []string       `json:"reasons"`
}

func (q *Queries) CreateMatchingRunLine(ctx context.Context, arg CreateMatchingRunLineParams) (int64, error) {
	row := q.db.QueryRow(ctx, createMatchingRunLine,
		arg.ApMatchingRunID,
		arg.ApInvoiceLineID,
		arg.PoLineID,
		arg.GrnLineID,
		arg.InvoiceQty,
		arg.InvoicePrice,
		arg.PoQty,
		arg.PoPrice,
		arg.GrnQty,
		arg.Status,
		arg.Reasons,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getActiveMatchingPolicy = `-- name: GetActiveMatchingPolicy :one
SELECT 
    id, name, company_id, supplier_id, category_id,
    qty_tolerance_pct, price_tolerance_pct, tax_tolerance_pct,
    freight_tolerance_pct, total_tolerance_amt,
    effective_from, effective_to, created_at, updated_at
FROM ap_matching_policies
WHERE 
    (effective_from <= CURRENT_DATE) AND (effective_to IS NULL OR effective_to >= CURRENT_DATE)
    AND (company_id = $1 OR company_id IS NULL)
    AND (supplier_id = $2 OR supplier_id IS NULL)
ORDER BY 
    company_id DESC NULLS LAST,
    supplier_id DESC NULLS LAST,
    category_id DESC NULLS LAST,
    effective_from DESC
LIMIT 1
`

type GetActiveMatchingPolicyParams struct {
	CompanyID  pgtype.Int8 `json:"company_id"`
	SupplierID pgtype.Int8 `json:"supplier_id"`
}

func (q *Queries) GetActiveMatchingPolicy(ctx context.Context, arg GetActiveMatchingPolicyParams) (ApMatchingPolicy, error) {
	row := q.db.QueryRow(ctx, getActiveMatchingPolicy, arg.CompanyID, arg.SupplierID)
	var i ApMatchingPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CompanyID,
		&i.SupplierID,
		&i.CategoryID,
		&i.QtyTolerancePct,
		&i.PriceTolerancePct,
		&i.TaxTolerancePct,
		&i.FreightTolerancePct,
		&i.TotalToleranceAmt,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMatchingRun = `-- name: GetMatchingRun :one
SELECT 
    id, ap_invoice_id, policy_id, status,
    invoice_total, po_total, grn_total,
    reasons, action_recommended, run_at, run_by
FROM ap_matching_runs
WHERE id = $1
`

func (q *Queries) GetMatchingRun(ctx context.Context, id int64) (ApMatchingRun, error) {
	row := q.db.QueryRow(ctx, getMatchingRun, id)
	var i ApMatchingRun
	err := row.Scan(
		&i.ID,
		&i.ApInvoiceID,
		&i.PolicyID,
		&i.Status,
		&i.InvoiceTotal,
		&i.PoTotal,
		&i.GrnTotal,
		&i.Reasons,
		&i.ActionRecommended,
		&i.RunAt,
		&i.RunBy,
	)
	return i, err
}

const listMatchingRunLines = `-- name: ListMatchingRunLines :many
SELECT 
    id, ap_matching_run_id, ap_invoice_line_id, po_line_id, grn_line_id,
    invoice_qty, invoice_price, po_qty, po_price, grn_qty,
    status, reasons
FROM ap_matching_run_lines
WHERE ap_matching_run_id = $1
`

func (q *Queries) ListMatchingRunLines(ctx context.Context, apMatchingRunID int64) ([]ApMatchingRunLine, error) {
	rows, err := q.db.Query(ctx, listMatchingRunLines, apMatchingRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApMatchingRunLine
	for rows.Next() {
		var i ApMatchingRunLine
		if err := rows.Scan(
			&i.ID,
			&i.ApMatchingRunID,
			&i.ApInvoiceLineID,
			&i.PoLineID,
			&i.GrnLineID,
			&i.InvoiceQty,
			&i.InvoicePrice,
			&i.PoQty,
			&i.PoPrice,
			&i.GrnQty,
			&i.Status,
			&i.Reasons,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
