// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory_adjustments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAdjustment = `-- name: GetAdjustment :one
SELECT adj.id, adj.uuid, adj.number, adj.warehouse_id, adj.status, adj.note, adj.adjustment_at, adj.created_by, adj.posted_by, adj.posted_at, adj.created_at, w.name as warehouse_name, u.email as creator_email
FROM inventory_adjustments adj
JOIN warehouses w ON adj.warehouse_id = w.id
JOIN users u ON adj.created_by = u.id
WHERE adj.id = $1
`

type GetAdjustmentRow struct {
	ID            int64              `json:"id"`
	Uuid          pgtype.UUID        `json:"uuid"`
	Number        string             `json:"number"`
	WarehouseID   int32              `json:"warehouse_id"`
	Status        string             `json:"status"`
	Note          string             `json:"note"`
	AdjustmentAt  pgtype.Timestamptz `json:"adjustment_at"`
	CreatedBy     int64              `json:"created_by"`
	PostedBy      pgtype.Int8        `json:"posted_by"`
	PostedAt      pgtype.Timestamptz `json:"posted_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	WarehouseName string             `json:"warehouse_name"`
	CreatorEmail  string             `json:"creator_email"`
}

func (q *Queries) GetAdjustment(ctx context.Context, id int64) (GetAdjustmentRow, error) {
	row := q.db.QueryRow(ctx, getAdjustment, id)
	var i GetAdjustmentRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Number,
		&i.WarehouseID,
		&i.Status,
		&i.Note,
		&i.AdjustmentAt,
		&i.CreatedBy,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedAt,
		&i.WarehouseName,
		&i.CreatorEmail,
	)
	return i, err
}

const getAdjustmentLines = `-- name: GetAdjustmentLines :many
SELECT adjl.id, adjl.adjustment_id, adjl.product_id, adjl.qty, adjl.note, p.name as product_name
FROM inventory_adjustment_lines adjl
JOIN products p ON adjl.product_id = p.id
WHERE adjl.adjustment_id = $1
`

type GetAdjustmentLinesRow struct {
	ID           int64          `json:"id"`
	AdjustmentID int64          `json:"adjustment_id"`
	ProductID    int32          `json:"product_id"`
	Qty          pgtype.Numeric `json:"qty"`
	Note         string         `json:"note"`
	ProductName  string         `json:"product_name"`
}

func (q *Queries) GetAdjustmentLines(ctx context.Context, adjustmentID int64) ([]GetAdjustmentLinesRow, error) {
	rows, err := q.db.Query(ctx, getAdjustmentLines, adjustmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdjustmentLinesRow
	for rows.Next() {
		var i GetAdjustmentLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.AdjustmentID,
			&i.ProductID,
			&i.Qty,
			&i.Note,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAdjustment = `-- name: InsertAdjustment :one
INSERT INTO inventory_adjustments (
    number, warehouse_id, status, note, adjustment_at, created_by, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW()
) RETURNING id
`

type InsertAdjustmentParams struct {
	Number       string             `json:"number"`
	WarehouseID  int32              `json:"warehouse_id"`
	Status       string             `json:"status"`
	Note         string             `json:"note"`
	AdjustmentAt pgtype.Timestamptz `json:"adjustment_at"`
	CreatedBy    int64              `json:"created_by"`
}

func (q *Queries) InsertAdjustment(ctx context.Context, arg InsertAdjustmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAdjustment,
		arg.Number,
		arg.WarehouseID,
		arg.Status,
		arg.Note,
		arg.AdjustmentAt,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertAdjustmentLine = `-- name: InsertAdjustmentLine :exec
INSERT INTO inventory_adjustment_lines (
    adjustment_id, product_id, qty, note
) VALUES (
    $1, $2, $3, $4
)
`

type InsertAdjustmentLineParams struct {
	AdjustmentID int64          `json:"adjustment_id"`
	ProductID    int32          `json:"product_id"`
	Qty          pgtype.Numeric `json:"qty"`
	Note         string         `json:"note"`
}

func (q *Queries) InsertAdjustmentLine(ctx context.Context, arg InsertAdjustmentLineParams) error {
	_, err := q.db.Exec(ctx, insertAdjustmentLine,
		arg.AdjustmentID,
		arg.ProductID,
		arg.Qty,
		arg.Note,
	)
	return err
}

const listAdjustments = `-- name: ListAdjustments :many
SELECT adj.id, adj.uuid, adj.number, adj.warehouse_id, adj.status, adj.note, adj.adjustment_at, adj.created_by, adj.posted_by, adj.posted_at, adj.created_at, w.name as warehouse_name
FROM inventory_adjustments adj
JOIN warehouses w ON adj.warehouse_id = w.id
ORDER BY adj.created_at DESC
`

type ListAdjustmentsRow struct {
	ID            int64              `json:"id"`
	Uuid          pgtype.UUID        `json:"uuid"`
	Number        string             `json:"number"`
	WarehouseID   int32              `json:"warehouse_id"`
	Status        string             `json:"status"`
	Note          string             `json:"note"`
	AdjustmentAt  pgtype.Timestamptz `json:"adjustment_at"`
	CreatedBy     int64              `json:"created_by"`
	PostedBy      pgtype.Int8        `json:"posted_by"`
	PostedAt      pgtype.Timestamptz `json:"posted_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	WarehouseName string             `json:"warehouse_name"`
}

func (q *Queries) ListAdjustments(ctx context.Context) ([]ListAdjustmentsRow, error) {
	rows, err := q.db.Query(ctx, listAdjustments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdjustmentsRow
	for rows.Next() {
		var i ListAdjustmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Number,
			&i.WarehouseID,
			&i.Status,
			&i.Note,
			&i.AdjustmentAt,
			&i.CreatedBy,
			&i.PostedBy,
			&i.PostedAt,
			&i.CreatedAt,
			&i.WarehouseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdjustmentStatus = `-- name: UpdateAdjustmentStatus :exec
UPDATE inventory_adjustments
SET status = $2, posted_by = $3, posted_at = $4
WHERE id = $1
`

type UpdateAdjustmentStatusParams struct {
	ID       int64              `json:"id"`
	Status   string             `json:"status"`
	PostedBy pgtype.Int8        `json:"posted_by"`
	PostedAt pgtype.Timestamptz `json:"posted_at"`
}

func (q *Queries) UpdateAdjustmentStatus(ctx context.Context, arg UpdateAdjustmentStatusParams) error {
	_, err := q.db.Exec(ctx, updateAdjustmentStatus,
		arg.ID,
		arg.Status,
		arg.PostedBy,
		arg.PostedAt,
	)
	return err
}
