// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: procurement_contracts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approvePOVariance = `-- name: ApprovePOVariance :exec
UPDATE po_contract_variances
SET approval_status = 'APPROVED', approved_by = $2, approved_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type ApprovePOVarianceParams struct {
	ID         int64       `json:"id"`
	ApprovedBy pgtype.Int8 `json:"approved_by"`
}

func (q *Queries) ApprovePOVariance(ctx context.Context, arg ApprovePOVarianceParams) error {
	_, err := q.db.Exec(ctx, approvePOVariance, arg.ID, arg.ApprovedBy)
	return err
}

const approveSupplierContract = `-- name: ApproveSupplierContract :exec
UPDATE supplier_contracts
SET status = 'ACTIVE', approved_by = $2, approved_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status = 'APPROVAL'
`

type ApproveSupplierContractParams struct {
	ID         int64       `json:"id"`
	ApprovedBy pgtype.Int8 `json:"approved_by"`
}

func (q *Queries) ApproveSupplierContract(ctx context.Context, arg ApproveSupplierContractParams) error {
	_, err := q.db.Exec(ctx, approveSupplierContract, arg.ID, arg.ApprovedBy)
	return err
}

const createPOVariance = `-- name: CreatePOVariance :one

INSERT INTO po_contract_variances (
    company_id, po_id, po_line_id, contract_id,
    variance_type, variance_percentage, variance_reason, note,
    created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW())
RETURNING id
`

type CreatePOVarianceParams struct {
	CompanyID          int64          `json:"company_id"`
	PoID               int64          `json:"po_id"`
	PoLineID           int64          `json:"po_line_id"`
	ContractID         pgtype.Int8    `json:"contract_id"`
	VarianceType       string         `json:"variance_type"`
	VariancePercentage pgtype.Numeric `json:"variance_percentage"`
	VarianceReason     string         `json:"variance_reason"`
	Note               string         `json:"note"`
}

// =============================================================================
// PO CONTRACT VARIANCES
// =============================================================================
func (q *Queries) CreatePOVariance(ctx context.Context, arg CreatePOVarianceParams) (int64, error) {
	row := q.db.QueryRow(ctx, createPOVariance,
		arg.CompanyID,
		arg.PoID,
		arg.PoLineID,
		arg.ContractID,
		arg.VarianceType,
		arg.VariancePercentage,
		arg.VarianceReason,
		arg.Note,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createSupplierContract = `-- name: CreateSupplierContract :one

INSERT INTO supplier_contracts (
    company_id, supplier_id, version, status, currency,
    effective_from, effective_to, payment_terms, incoterms,
    renewal_notice_days, created_by, note, created_at, updated_at
) VALUES ($1, $2, 1, 'DRAFT', $3, $4, $5, $6, $7, $8, $9, $10, NOW(), NOW())
RETURNING id
`

type CreateSupplierContractParams struct {
	CompanyID         int64       `json:"company_id"`
	SupplierID        int64       `json:"supplier_id"`
	Currency          string      `json:"currency"`
	EffectiveFrom     pgtype.Date `json:"effective_from"`
	EffectiveTo       pgtype.Date `json:"effective_to"`
	PaymentTerms      string      `json:"payment_terms"`
	Incoterms         string      `json:"incoterms"`
	RenewalNoticeDays int32       `json:"renewal_notice_days"`
	CreatedBy         int64       `json:"created_by"`
	Note              string      `json:"note"`
}

// =============================================================================
// SUPPLIER CONTRACTS (Phase 3: Vendor Intelligence)
// =============================================================================
func (q *Queries) CreateSupplierContract(ctx context.Context, arg CreateSupplierContractParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSupplierContract,
		arg.CompanyID,
		arg.SupplierID,
		arg.Currency,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.PaymentTerms,
		arg.Incoterms,
		arg.RenewalNoticeDays,
		arg.CreatedBy,
		arg.Note,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createSupplierScorecard = `-- name: CreateSupplierScorecard :one

INSERT INTO supplier_scorecards (
    company_id, supplier_id, version, period_start, period_end,
    status, created_by, created_at
) VALUES ($1, $2, (
    SELECT COALESCE(MAX(version), 0) + 1
    FROM supplier_scorecards
    WHERE company_id = $1 AND supplier_id = $2
), $3, $4, 'DRAFT', $5, NOW())
RETURNING id
`

type CreateSupplierScorecardParams struct {
	CompanyID   int64       `json:"company_id"`
	SupplierID  int64       `json:"supplier_id"`
	PeriodStart pgtype.Date `json:"period_start"`
	PeriodEnd   pgtype.Date `json:"period_end"`
	CreatedBy   int64       `json:"created_by"`
}

// =============================================================================
// SUPPLIER SCORECARDS
// =============================================================================
func (q *Queries) CreateSupplierScorecard(ctx context.Context, arg CreateSupplierScorecardParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSupplierScorecard,
		arg.CompanyID,
		arg.SupplierID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteContractPriceLines = `-- name: DeleteContractPriceLines :exec
DELETE FROM contract_price_lines WHERE contract_id = $1
`

func (q *Queries) DeleteContractPriceLines(ctx context.Context, contractID int64) error {
	_, err := q.db.Exec(ctx, deleteContractPriceLines, contractID)
	return err
}

const getContractPriceLineForProduct = `-- name: GetContractPriceLineForProduct :one
SELECT id, contract_id, product_id, min_quantity, unit_price, tax_rate,
       lead_time_days, moq
FROM contract_price_lines
WHERE contract_id = $1 AND product_id = $2 AND min_quantity <= $3
ORDER BY min_quantity DESC
LIMIT 1
`

type GetContractPriceLineForProductParams struct {
	ContractID  int64          `json:"contract_id"`
	ProductID   int64          `json:"product_id"`
	MinQuantity pgtype.Numeric `json:"min_quantity"`
}

func (q *Queries) GetContractPriceLineForProduct(ctx context.Context, arg GetContractPriceLineForProductParams) (ContractPriceLine, error) {
	row := q.db.QueryRow(ctx, getContractPriceLineForProduct, arg.ContractID, arg.ProductID, arg.MinQuantity)
	var i ContractPriceLine
	err := row.Scan(
		&i.ID,
		&i.ContractID,
		&i.ProductID,
		&i.MinQuantity,
		&i.UnitPrice,
		&i.TaxRate,
		&i.LeadTimeDays,
		&i.Moq,
	)
	return i, err
}

const getContractPriceLines = `-- name: GetContractPriceLines :many
SELECT id, contract_id, product_id, min_quantity, unit_price, tax_rate,
       lead_time_days, moq
FROM contract_price_lines
WHERE contract_id = $1
ORDER BY product_id, min_quantity
`

func (q *Queries) GetContractPriceLines(ctx context.Context, contractID int64) ([]ContractPriceLine, error) {
	rows, err := q.db.Query(ctx, getContractPriceLines, contractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContractPriceLine
	for rows.Next() {
		var i ContractPriceLine
		if err := rows.Scan(
			&i.ID,
			&i.ContractID,
			&i.ProductID,
			&i.MinQuantity,
			&i.UnitPrice,
			&i.TaxRate,
			&i.LeadTimeDays,
			&i.Moq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestSupplierScorecard = `-- name: GetLatestSupplierScorecard :one
SELECT id, company_id, supplier_id, version, period_start, period_end, status,
       delivery_otif_score, delivery_otif_weight, delivery_otif_sample_size,
       quality_score, quality_weight, quality_sample_size,
       price_adherence_score, price_adherence_weight, price_adherence_sample_size,
       rfq_responsiveness_score, rfq_responsiveness_weight, rfq_responsiveness_sample_size,
       reviewer_assessment_score, reviewer_assessment_weight,
       overall_score, published_by, published_at, note, created_by, created_at
FROM supplier_scorecards
WHERE company_id = $1 AND supplier_id = $2
ORDER BY version DESC
LIMIT 1
`

type GetLatestSupplierScorecardParams struct {
	CompanyID  int64 `json:"company_id"`
	SupplierID int64 `json:"supplier_id"`
}

func (q *Queries) GetLatestSupplierScorecard(ctx context.Context, arg GetLatestSupplierScorecardParams) (SupplierScorecard, error) {
	row := q.db.QueryRow(ctx, getLatestSupplierScorecard, arg.CompanyID, arg.SupplierID)
	var i SupplierScorecard
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SupplierID,
		&i.Version,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.DeliveryOtifScore,
		&i.DeliveryOtifWeight,
		&i.DeliveryOtifSampleSize,
		&i.QualityScore,
		&i.QualityWeight,
		&i.QualitySampleSize,
		&i.PriceAdherenceScore,
		&i.PriceAdherenceWeight,
		&i.PriceAdherenceSampleSize,
		&i.RfqResponsivenessScore,
		&i.RfqResponsivenessWeight,
		&i.RfqResponsivenessSampleSize,
		&i.ReviewerAssessmentScore,
		&i.ReviewerAssessmentWeight,
		&i.OverallScore,
		&i.PublishedBy,
		&i.PublishedAt,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPOVariance = `-- name: GetPOVariance :one
SELECT id, company_id, po_id, po_line_id, contract_id,
       variance_type, variance_percentage, variance_reason,
       approval_status, approved_by, approved_at, note,
       created_at, updated_at
FROM po_contract_variances
WHERE id = $1
`

func (q *Queries) GetPOVariance(ctx context.Context, id int64) (PoContractVariance, error) {
	row := q.db.QueryRow(ctx, getPOVariance, id)
	var i PoContractVariance
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.PoID,
		&i.PoLineID,
		&i.ContractID,
		&i.VarianceType,
		&i.VariancePercentage,
		&i.VarianceReason,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPriceHistoryBySource = `-- name: GetPriceHistoryBySource :many
SELECT id, company_id, supplier_id, product_id, source_type, source_id,
       currency, unit_price, quantity, tax_rate, moq, lead_time_days,
       fx_rate, base_currency_price, observation_date, note, created_at
FROM price_history
WHERE source_type = $1 AND source_id = $2
ORDER BY observation_date DESC
`

type GetPriceHistoryBySourceParams struct {
	SourceType string `json:"source_type"`
	SourceID   int64  `json:"source_id"`
}

func (q *Queries) GetPriceHistoryBySource(ctx context.Context, arg GetPriceHistoryBySourceParams) ([]PriceHistory, error) {
	rows, err := q.db.Query(ctx, getPriceHistoryBySource, arg.SourceType, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PriceHistory
	for rows.Next() {
		var i PriceHistory
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SupplierID,
			&i.ProductID,
			&i.SourceType,
			&i.SourceID,
			&i.Currency,
			&i.UnitPrice,
			&i.Quantity,
			&i.TaxRate,
			&i.Moq,
			&i.LeadTimeDays,
			&i.FxRate,
			&i.BaseCurrencyPrice,
			&i.ObservationDate,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSupplierContract = `-- name: GetSupplierContract :one
SELECT id, company_id, supplier_id, version, status, currency,
       effective_from, effective_to, payment_terms, incoterms,
       renewal_notice_days, expiry_notification_sent,
       created_by, approved_by, approved_at, terminated_at, note,
       created_at, updated_at
FROM supplier_contracts
WHERE id = $1
`

func (q *Queries) GetSupplierContract(ctx context.Context, id int64) (SupplierContract, error) {
	row := q.db.QueryRow(ctx, getSupplierContract, id)
	var i SupplierContract
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SupplierID,
		&i.Version,
		&i.Status,
		&i.Currency,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.PaymentTerms,
		&i.Incoterms,
		&i.RenewalNoticeDays,
		&i.ExpiryNotificationSent,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.TerminatedAt,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplierContractByVersion = `-- name: GetSupplierContractByVersion :one
SELECT id, company_id, supplier_id, version, status, currency,
       effective_from, effective_to, payment_terms, incoterms,
       renewal_notice_days, expiry_notification_sent,
       created_by, approved_by, approved_at, terminated_at, note,
       created_at, updated_at
FROM supplier_contracts
WHERE company_id = $1 AND supplier_id = $2 AND version = $3
`

type GetSupplierContractByVersionParams struct {
	CompanyID  int64 `json:"company_id"`
	SupplierID int64 `json:"supplier_id"`
	Version    int32 `json:"version"`
}

func (q *Queries) GetSupplierContractByVersion(ctx context.Context, arg GetSupplierContractByVersionParams) (SupplierContract, error) {
	row := q.db.QueryRow(ctx, getSupplierContractByVersion, arg.CompanyID, arg.SupplierID, arg.Version)
	var i SupplierContract
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SupplierID,
		&i.Version,
		&i.Status,
		&i.Currency,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.PaymentTerms,
		&i.Incoterms,
		&i.RenewalNoticeDays,
		&i.ExpiryNotificationSent,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.TerminatedAt,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplierScorecard = `-- name: GetSupplierScorecard :one
SELECT id, company_id, supplier_id, version, period_start, period_end, status,
       delivery_otif_score, delivery_otif_weight, delivery_otif_sample_size,
       quality_score, quality_weight, quality_sample_size,
       price_adherence_score, price_adherence_weight, price_adherence_sample_size,
       rfq_responsiveness_score, rfq_responsiveness_weight, rfq_responsiveness_sample_size,
       reviewer_assessment_score, reviewer_assessment_weight,
       overall_score, published_by, published_at, note, created_by, created_at
FROM supplier_scorecards
WHERE id = $1
`

func (q *Queries) GetSupplierScorecard(ctx context.Context, id int64) (SupplierScorecard, error) {
	row := q.db.QueryRow(ctx, getSupplierScorecard, id)
	var i SupplierScorecard
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SupplierID,
		&i.Version,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.DeliveryOtifScore,
		&i.DeliveryOtifWeight,
		&i.DeliveryOtifSampleSize,
		&i.QualityScore,
		&i.QualityWeight,
		&i.QualitySampleSize,
		&i.PriceAdherenceScore,
		&i.PriceAdherenceWeight,
		&i.PriceAdherenceSampleSize,
		&i.RfqResponsivenessScore,
		&i.RfqResponsivenessWeight,
		&i.RfqResponsivenessSampleSize,
		&i.ReviewerAssessmentScore,
		&i.ReviewerAssessmentWeight,
		&i.OverallScore,
		&i.PublishedBy,
		&i.PublishedAt,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertContractPriceLine = `-- name: InsertContractPriceLine :exec

INSERT INTO contract_price_lines (
    contract_id, product_id, min_quantity, unit_price, tax_rate,
    lead_time_days, moq
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertContractPriceLineParams struct {
	ContractID   int64          `json:"contract_id"`
	ProductID    int64          `json:"product_id"`
	MinQuantity  pgtype.Numeric `json:"min_quantity"`
	UnitPrice    pgtype.Numeric `json:"unit_price"`
	TaxRate      pgtype.Numeric `json:"tax_rate"`
	LeadTimeDays int32          `json:"lead_time_days"`
	Moq          pgtype.Numeric `json:"moq"`
}

// =============================================================================
// CONTRACT PRICE LINES
// =============================================================================
func (q *Queries) InsertContractPriceLine(ctx context.Context, arg InsertContractPriceLineParams) error {
	_, err := q.db.Exec(ctx, insertContractPriceLine,
		arg.ContractID,
		arg.ProductID,
		arg.MinQuantity,
		arg.UnitPrice,
		arg.TaxRate,
		arg.LeadTimeDays,
		arg.Moq,
	)
	return err
}

const listActiveContractsBySupplier = `-- name: ListActiveContractsBySupplier :many
SELECT id, company_id, supplier_id, version, status, currency,
       effective_from, effective_to, payment_terms, incoterms,
       renewal_notice_days, expiry_notification_sent,
       created_by, approved_by, approved_at, terminated_at, note,
       created_at, updated_at
FROM supplier_contracts
WHERE company_id = $1 AND supplier_id = $2 AND status = 'ACTIVE'
  AND effective_from <= CURRENT_DATE
  AND (effective_to IS NULL OR effective_to >= CURRENT_DATE)
ORDER BY version DESC
`

type ListActiveContractsBySupplierParams struct {
	CompanyID  int64 `json:"company_id"`
	SupplierID int64 `json:"supplier_id"`
}

func (q *Queries) ListActiveContractsBySupplier(ctx context.Context, arg ListActiveContractsBySupplierParams) ([]SupplierContract, error) {
	rows, err := q.db.Query(ctx, listActiveContractsBySupplier, arg.CompanyID, arg.SupplierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplierContract
	for rows.Next() {
		var i SupplierContract
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SupplierID,
			&i.Version,
			&i.Status,
			&i.Currency,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.PaymentTerms,
			&i.Incoterms,
			&i.RenewalNoticeDays,
			&i.ExpiryNotificationSent,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.TerminatedAt,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPOVariancesByPO = `-- name: ListPOVariancesByPO :many
SELECT id, company_id, po_id, po_line_id, contract_id,
       variance_type, variance_percentage, variance_reason,
       approval_status, approved_by, approved_at, note,
       created_at, updated_at
FROM po_contract_variances
WHERE po_id = $1
ORDER BY po_line_id
`

func (q *Queries) ListPOVariancesByPO(ctx context.Context, poID int64) ([]PoContractVariance, error) {
	rows, err := q.db.Query(ctx, listPOVariancesByPO, poID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PoContractVariance
	for rows.Next() {
		var i PoContractVariance
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.PoID,
			&i.PoLineID,
			&i.ContractID,
			&i.VarianceType,
			&i.VariancePercentage,
			&i.VarianceReason,
			&i.ApprovalStatus,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingVariances = `-- name: ListPendingVariances :many
SELECT id, company_id, po_id, po_line_id, contract_id,
       variance_type, variance_percentage, variance_reason,
       approval_status, approved_by, approved_at, note,
       created_at, updated_at
FROM po_contract_variances
WHERE company_id = $1 AND approval_status = 'PENDING'
ORDER BY created_at DESC
`

func (q *Queries) ListPendingVariances(ctx context.Context, companyID int64) ([]PoContractVariance, error) {
	rows, err := q.db.Query(ctx, listPendingVariances, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PoContractVariance
	for rows.Next() {
		var i PoContractVariance
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.PoID,
			&i.PoLineID,
			&i.ContractID,
			&i.VarianceType,
			&i.VariancePercentage,
			&i.VarianceReason,
			&i.ApprovalStatus,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceHistoryBySupplierProduct = `-- name: ListPriceHistoryBySupplierProduct :many
SELECT id, company_id, supplier_id, product_id, source_type, source_id,
       currency, unit_price, quantity, tax_rate, moq, lead_time_days,
       fx_rate, base_currency_price, observation_date, note, created_at
FROM price_history
WHERE company_id = $1 AND supplier_id = $2 AND product_id = $3
ORDER BY observation_date DESC
`

type ListPriceHistoryBySupplierProductParams struct {
	CompanyID  int64 `json:"company_id"`
	SupplierID int64 `json:"supplier_id"`
	ProductID  int64 `json:"product_id"`
}

func (q *Queries) ListPriceHistoryBySupplierProduct(ctx context.Context, arg ListPriceHistoryBySupplierProductParams) ([]PriceHistory, error) {
	rows, err := q.db.Query(ctx, listPriceHistoryBySupplierProduct, arg.CompanyID, arg.SupplierID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PriceHistory
	for rows.Next() {
		var i PriceHistory
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SupplierID,
			&i.ProductID,
			&i.SourceType,
			&i.SourceID,
			&i.Currency,
			&i.UnitPrice,
			&i.Quantity,
			&i.TaxRate,
			&i.Moq,
			&i.LeadTimeDays,
			&i.FxRate,
			&i.BaseCurrencyPrice,
			&i.ObservationDate,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceHistoryTrend = `-- name: ListPriceHistoryTrend :many
SELECT observation_date, currency, unit_price, base_currency_price,
       source_type, source_id
FROM price_history
WHERE company_id = $1 AND supplier_id = $2 AND product_id = $3
ORDER BY observation_date DESC
LIMIT $4
`

type ListPriceHistoryTrendParams struct {
	CompanyID  int64 `json:"company_id"`
	SupplierID int64 `json:"supplier_id"`
	ProductID  int64 `json:"product_id"`
	Limit      int32 `json:"limit"`
}

type ListPriceHistoryTrendRow struct {
	ObservationDate   pgtype.Date    `json:"observation_date"`
	Currency          string         `json:"currency"`
	UnitPrice         pgtype.Numeric `json:"unit_price"`
	BaseCurrencyPrice pgtype.Numeric `json:"base_currency_price"`
	SourceType        string         `json:"source_type"`
	SourceID          int64          `json:"source_id"`
}

func (q *Queries) ListPriceHistoryTrend(ctx context.Context, arg ListPriceHistoryTrendParams) ([]ListPriceHistoryTrendRow, error) {
	rows, err := q.db.Query(ctx, listPriceHistoryTrend,
		arg.CompanyID,
		arg.SupplierID,
		arg.ProductID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPriceHistoryTrendRow
	for rows.Next() {
		var i ListPriceHistoryTrendRow
		if err := rows.Scan(
			&i.ObservationDate,
			&i.Currency,
			&i.UnitPrice,
			&i.BaseCurrencyPrice,
			&i.SourceType,
			&i.SourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierContracts = `-- name: ListSupplierContracts :many
SELECT id, company_id, supplier_id, version, status, currency,
       effective_from, effective_to, payment_terms, incoterms,
       renewal_notice_days, expiry_notification_sent,
       created_by, approved_by, approved_at, terminated_at, note,
       created_at, updated_at
FROM supplier_contracts
WHERE company_id = $1
ORDER BY supplier_id, version DESC
`

func (q *Queries) ListSupplierContracts(ctx context.Context, companyID int64) ([]SupplierContract, error) {
	rows, err := q.db.Query(ctx, listSupplierContracts, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplierContract
	for rows.Next() {
		var i SupplierContract
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SupplierID,
			&i.Version,
			&i.Status,
			&i.Currency,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.PaymentTerms,
			&i.Incoterms,
			&i.RenewalNoticeDays,
			&i.ExpiryNotificationSent,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.TerminatedAt,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierScorecards = `-- name: ListSupplierScorecards :many
SELECT id, company_id, supplier_id, version, period_start, period_end, status,
       delivery_otif_score, delivery_otif_weight, delivery_otif_sample_size,
       quality_score, quality_weight, quality_sample_size,
       price_adherence_score, price_adherence_weight, price_adherence_sample_size,
       rfq_responsiveness_score, rfq_responsiveness_weight, rfq_responsiveness_sample_size,
       reviewer_assessment_score, reviewer_assessment_weight,
       overall_score, published_by, published_at, note, created_by, created_at
FROM supplier_scorecards
WHERE company_id = $1 AND supplier_id = $2
ORDER BY version DESC
`

type ListSupplierScorecardsParams struct {
	CompanyID  int64 `json:"company_id"`
	SupplierID int64 `json:"supplier_id"`
}

func (q *Queries) ListSupplierScorecards(ctx context.Context, arg ListSupplierScorecardsParams) ([]SupplierScorecard, error) {
	rows, err := q.db.Query(ctx, listSupplierScorecards, arg.CompanyID, arg.SupplierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplierScorecard
	for rows.Next() {
		var i SupplierScorecard
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SupplierID,
			&i.Version,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.DeliveryOtifScore,
			&i.DeliveryOtifWeight,
			&i.DeliveryOtifSampleSize,
			&i.QualityScore,
			&i.QualityWeight,
			&i.QualitySampleSize,
			&i.PriceAdherenceScore,
			&i.PriceAdherenceWeight,
			&i.PriceAdherenceSampleSize,
			&i.RfqResponsivenessScore,
			&i.RfqResponsivenessWeight,
			&i.RfqResponsivenessSampleSize,
			&i.ReviewerAssessmentScore,
			&i.ReviewerAssessmentWeight,
			&i.OverallScore,
			&i.PublishedBy,
			&i.PublishedAt,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishSupplierScorecard = `-- name: PublishSupplierScorecard :exec
UPDATE supplier_scorecards
SET status = 'PUBLISHED', published_by = $2, published_at = NOW()
WHERE id = $1 AND status = 'DRAFT'
`

type PublishSupplierScorecardParams struct {
	ID          int64       `json:"id"`
	PublishedBy pgtype.Int8 `json:"published_by"`
}

func (q *Queries) PublishSupplierScorecard(ctx context.Context, arg PublishSupplierScorecardParams) error {
	_, err := q.db.Exec(ctx, publishSupplierScorecard, arg.ID, arg.PublishedBy)
	return err
}

const recordPriceHistory = `-- name: RecordPriceHistory :one

INSERT INTO price_history (
    company_id, supplier_id, product_id, source_type, source_id,
    currency, unit_price, quantity, tax_rate, moq, lead_time_days,
    fx_rate, base_currency_price, observation_date, note, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, NOW())
RETURNING id
`

type RecordPriceHistoryParams struct {
	CompanyID         int64          `json:"company_id"`
	SupplierID        int64          `json:"supplier_id"`
	ProductID         int64          `json:"product_id"`
	SourceType        string         `json:"source_type"`
	SourceID          int64          `json:"source_id"`
	Currency          string         `json:"currency"`
	UnitPrice         pgtype.Numeric `json:"unit_price"`
	Quantity          pgtype.Numeric `json:"quantity"`
	TaxRate           pgtype.Numeric `json:"tax_rate"`
	Moq               pgtype.Numeric `json:"moq"`
	LeadTimeDays      int32          `json:"lead_time_days"`
	FxRate            pgtype.Numeric `json:"fx_rate"`
	BaseCurrencyPrice pgtype.Numeric `json:"base_currency_price"`
	ObservationDate   pgtype.Date    `json:"observation_date"`
	Note              string         `json:"note"`
}

// =============================================================================
// PRICE HISTORY (Immutable)
// =============================================================================
func (q *Queries) RecordPriceHistory(ctx context.Context, arg RecordPriceHistoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, recordPriceHistory,
		arg.CompanyID,
		arg.SupplierID,
		arg.ProductID,
		arg.SourceType,
		arg.SourceID,
		arg.Currency,
		arg.UnitPrice,
		arg.Quantity,
		arg.TaxRate,
		arg.Moq,
		arg.LeadTimeDays,
		arg.FxRate,
		arg.BaseCurrencyPrice,
		arg.ObservationDate,
		arg.Note,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const rejectPOVariance = `-- name: RejectPOVariance :exec
UPDATE po_contract_variances
SET approval_status = 'REJECTED', approved_by = $2, approved_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type RejectPOVarianceParams struct {
	ID         int64       `json:"id"`
	ApprovedBy pgtype.Int8 `json:"approved_by"`
}

func (q *Queries) RejectPOVariance(ctx context.Context, arg RejectPOVarianceParams) error {
	_, err := q.db.Exec(ctx, rejectPOVariance, arg.ID, arg.ApprovedBy)
	return err
}

const setContractExpiryNotificationSent = `-- name: SetContractExpiryNotificationSent :exec
UPDATE supplier_contracts
SET expiry_notification_sent = TRUE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SetContractExpiryNotificationSent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setContractExpiryNotificationSent, id)
	return err
}

const terminateSupplierContract = `-- name: TerminateSupplierContract :exec
UPDATE supplier_contracts
SET status = 'TERMINATED', terminated_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status = 'ACTIVE'
`

func (q *Queries) TerminateSupplierContract(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, terminateSupplierContract, id)
	return err
}

const updateScorecardScores = `-- name: UpdateScorecardScores :exec
UPDATE supplier_scorecards
SET delivery_otif_score = $2,
    delivery_otif_sample_size = $3,
    quality_score = $4,
    quality_sample_size = $5,
    price_adherence_score = $6,
    price_adherence_sample_size = $7,
    rfq_responsiveness_score = $8,
    rfq_responsiveness_sample_size = $9,
    reviewer_assessment_score = $10,
    overall_score = $11
WHERE id = $1
`

type UpdateScorecardScoresParams struct {
	ID                          int64          `json:"id"`
	DeliveryOtifScore           pgtype.Numeric `json:"delivery_otif_score"`
	DeliveryOtifSampleSize      int32          `json:"delivery_otif_sample_size"`
	QualityScore                pgtype.Numeric `json:"quality_score"`
	QualitySampleSize           int32          `json:"quality_sample_size"`
	PriceAdherenceScore         pgtype.Numeric `json:"price_adherence_score"`
	PriceAdherenceSampleSize    int32          `json:"price_adherence_sample_size"`
	RfqResponsivenessScore      pgtype.Numeric `json:"rfq_responsiveness_score"`
	RfqResponsivenessSampleSize int32          `json:"rfq_responsiveness_sample_size"`
	ReviewerAssessmentScore     pgtype.Numeric `json:"reviewer_assessment_score"`
	OverallScore                pgtype.Numeric `json:"overall_score"`
}

func (q *Queries) UpdateScorecardScores(ctx context.Context, arg UpdateScorecardScoresParams) error {
	_, err := q.db.Exec(ctx, updateScorecardScores,
		arg.ID,
		arg.DeliveryOtifScore,
		arg.DeliveryOtifSampleSize,
		arg.QualityScore,
		arg.QualitySampleSize,
		arg.PriceAdherenceScore,
		arg.PriceAdherenceSampleSize,
		arg.RfqResponsivenessScore,
		arg.RfqResponsivenessSampleSize,
		arg.ReviewerAssessmentScore,
		arg.OverallScore,
	)
	return err
}

const updateSupplierContractStatus = `-- name: UpdateSupplierContractStatus :exec
UPDATE supplier_contracts
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateSupplierContractStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateSupplierContractStatus(ctx context.Context, arg UpdateSupplierContractStatusParams) error {
	_, err := q.db.Exec(ctx, updateSupplierContractStatus, arg.ID, arg.Status)
	return err
}
