// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: procurement.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelGoodsReturnGRN = `-- name: CancelGoodsReturnGRN :exec
UPDATE goods_return_grns
SET status = 'CANCELLED', voided_by = $2, voided_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status IN ('DRAFT', 'CONFIRMED')
`

type CancelGoodsReturnGRNParams struct {
	ID       int64       `json:"id"`
	VoidedBy pgtype.Int8 `json:"voided_by"`
}

func (q *Queries) CancelGoodsReturnGRN(ctx context.Context, arg CancelGoodsReturnGRNParams) error {
	_, err := q.db.Exec(ctx, cancelGoodsReturnGRN, arg.ID, arg.VoidedBy)
	return err
}

const confirmGoodsReturnGRN = `-- name: ConfirmGoodsReturnGRN :exec
UPDATE goods_return_grns
SET status = 'CONFIRMED', confirmed_by = $2, confirmed_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status = 'DRAFT'
`

type ConfirmGoodsReturnGRNParams struct {
	ID          int64       `json:"id"`
	ConfirmedBy pgtype.Int8 `json:"confirmed_by"`
}

func (q *Queries) ConfirmGoodsReturnGRN(ctx context.Context, arg ConfirmGoodsReturnGRNParams) error {
	_, err := q.db.Exec(ctx, confirmGoodsReturnGRN, arg.ID, arg.ConfirmedBy)
	return err
}

const createGRN = `-- name: CreateGRN :one

INSERT INTO grns (number, po_id, supplier_id, warehouse_id, status, received_at, note, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
RETURNING id
`

type CreateGRNParams struct {
	Number      string             `json:"number"`
	PoID        pgtype.Int8        `json:"po_id"`
	SupplierID  int64              `json:"supplier_id"`
	WarehouseID int64              `json:"warehouse_id"`
	Status      string             `json:"status"`
	ReceivedAt  pgtype.Timestamptz `json:"received_at"`
	Note        string             `json:"note"`
}

// =============================================================================
// GOODS RECEIPTS (GRN)
// =============================================================================
func (q *Queries) CreateGRN(ctx context.Context, arg CreateGRNParams) (int64, error) {
	row := q.db.QueryRow(ctx, createGRN,
		arg.Number,
		arg.PoID,
		arg.SupplierID,
		arg.WarehouseID,
		arg.Status,
		arg.ReceivedAt,
		arg.Note,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createGoodsReturnGRN = `-- name: CreateGoodsReturnGRN :one
INSERT INTO goods_return_grns (
    number, company_id, supplier_id, grn_id, warehouse_id,
    return_date, status, reason, notes, created_by, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), NOW())
RETURNING id
`

type CreateGoodsReturnGRNParams struct {
	Number      string               `json:"number"`
	CompanyID   int64                `json:"company_id"`
	SupplierID  int64                `json:"supplier_id"`
	GrnID       int64                `json:"grn_id"`
	WarehouseID int64                `json:"warehouse_id"`
	ReturnDate  pgtype.Date          `json:"return_date"`
	Status      GoodsReturnGrnStatus `json:"status"`
	Reason      string               `json:"reason"`
	Notes       pgtype.Text          `json:"notes"`
	CreatedBy   int64                `json:"created_by"`
}

func (q *Queries) CreateGoodsReturnGRN(ctx context.Context, arg CreateGoodsReturnGRNParams) (int64, error) {
	row := q.db.QueryRow(ctx, createGoodsReturnGRN,
		arg.Number,
		arg.CompanyID,
		arg.SupplierID,
		arg.GrnID,
		arg.WarehouseID,
		arg.ReturnDate,
		arg.Status,
		arg.Reason,
		arg.Notes,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createGoodsReturnGRNLine = `-- name: CreateGoodsReturnGRNLine :one
INSERT INTO goods_return_grn_lines (
    goods_return_grn_id, grn_line_id, product_id, quantity_returned, unit_cost,
    notes, line_order, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
RETURNING id
`

type CreateGoodsReturnGRNLineParams struct {
	GoodsReturnGrnID int64          `json:"goods_return_grn_id"`
	GrnLineID        int64          `json:"grn_line_id"`
	ProductID        int64          `json:"product_id"`
	QuantityReturned pgtype.Numeric `json:"quantity_returned"`
	UnitCost         pgtype.Numeric `json:"unit_cost"`
	Notes            pgtype.Text    `json:"notes"`
	LineOrder        int32          `json:"line_order"`
}

func (q *Queries) CreateGoodsReturnGRNLine(ctx context.Context, arg CreateGoodsReturnGRNLineParams) (int64, error) {
	row := q.db.QueryRow(ctx, createGoodsReturnGRNLine,
		arg.GoodsReturnGrnID,
		arg.GrnLineID,
		arg.ProductID,
		arg.QuantityReturned,
		arg.UnitCost,
		arg.Notes,
		arg.LineOrder,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createPO = `-- name: CreatePO :one

INSERT INTO pos (number, supplier_id, status, currency, expected_date, note, created_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
RETURNING id
`

type CreatePOParams struct {
	Number       string      `json:"number"`
	SupplierID   int64       `json:"supplier_id"`
	Status       string      `json:"status"`
	Currency     string      `json:"currency"`
	ExpectedDate pgtype.Date `json:"expected_date"`
	Note         string      `json:"note"`
}

// =============================================================================
// PURCHASE ORDERS (PO)
// =============================================================================
func (q *Queries) CreatePO(ctx context.Context, arg CreatePOParams) (int64, error) {
	row := q.db.QueryRow(ctx, createPO,
		arg.Number,
		arg.SupplierID,
		arg.Status,
		arg.Currency,
		arg.ExpectedDate,
		arg.Note,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createPR = `-- name: CreatePR :one

INSERT INTO prs (number, supplier_id, request_by, status, note, created_at)
VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING id
`

type CreatePRParams struct {
	Number     string      `json:"number"`
	SupplierID pgtype.Int8 `json:"supplier_id"`
	RequestBy  int64       `json:"request_by"`
	Status     string      `json:"status"`
	Note       string      `json:"note"`
}

// =============================================================================
// PURCHASE REQUESTS (PR)
// =============================================================================
func (q *Queries) CreatePR(ctx context.Context, arg CreatePRParams) (int64, error) {
	row := q.db.QueryRow(ctx, createPR,
		arg.Number,
		arg.SupplierID,
		arg.RequestBy,
		arg.Status,
		arg.Note,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const gRNExistsByNumber = `-- name: GRNExistsByNumber :one
SELECT EXISTS(SELECT 1 FROM grns WHERE number = $1) AS exists
`

func (q *Queries) GRNExistsByNumber(ctx context.Context, number string) (bool, error) {
	row := q.db.QueryRow(ctx, gRNExistsByNumber, number)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const generateGoodsReturnGRNNumber = `-- name: GenerateGoodsReturnGRNNumber :one
SELECT generate_goods_return_grn_number()
`

func (q *Queries) GenerateGoodsReturnGRNNumber(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, generateGoodsReturnGRNNumber)
	var generate_goods_return_grn_number string
	err := row.Scan(&generate_goods_return_grn_number)
	return generate_goods_return_grn_number, err
}

const getGRN = `-- name: GetGRN :one
SELECT id, number, po_id, supplier_id, warehouse_id, status, received_at, note
FROM grns WHERE id = $1
`

type GetGRNRow struct {
	ID          int64              `json:"id"`
	Number      string             `json:"number"`
	PoID        pgtype.Int8        `json:"po_id"`
	SupplierID  int64              `json:"supplier_id"`
	WarehouseID int64              `json:"warehouse_id"`
	Status      string             `json:"status"`
	ReceivedAt  pgtype.Timestamptz `json:"received_at"`
	Note        string             `json:"note"`
}

func (q *Queries) GetGRN(ctx context.Context, id int64) (GetGRNRow, error) {
	row := q.db.QueryRow(ctx, getGRN, id)
	var i GetGRNRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.PoID,
		&i.SupplierID,
		&i.WarehouseID,
		&i.Status,
		&i.ReceivedAt,
		&i.Note,
	)
	return i, err
}

const getGRNLine = `-- name: GetGRNLine :one

SELECT id, grn_id, product_id, qty, unit_cost, lot_number, expiry_date, serial_numbers
FROM grn_lines
WHERE id = $1
`

// =============================================================================
// GOODS RETURNS (from GRN)
// =============================================================================
func (q *Queries) GetGRNLine(ctx context.Context, id int64) (GrnLine, error) {
	row := q.db.QueryRow(ctx, getGRNLine, id)
	var i GrnLine
	err := row.Scan(
		&i.ID,
		&i.GrnID,
		&i.ProductID,
		&i.Qty,
		&i.UnitCost,
		&i.LotNumber,
		&i.ExpiryDate,
		&i.SerialNumbers,
	)
	return i, err
}

const getGRNLines = `-- name: GetGRNLines :many
SELECT id, grn_id, product_id, qty, unit_cost
FROM grn_lines WHERE grn_id = $1 ORDER BY id
`

type GetGRNLinesRow struct {
	ID        int64          `json:"id"`
	GrnID     int64          `json:"grn_id"`
	ProductID int64          `json:"product_id"`
	Qty       pgtype.Numeric `json:"qty"`
	UnitCost  pgtype.Numeric `json:"unit_cost"`
}

func (q *Queries) GetGRNLines(ctx context.Context, grnID int64) ([]GetGRNLinesRow, error) {
	rows, err := q.db.Query(ctx, getGRNLines, grnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGRNLinesRow
	for rows.Next() {
		var i GetGRNLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.GrnID,
			&i.ProductID,
			&i.Qty,
			&i.UnitCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGoodsReturnGRN = `-- name: GetGoodsReturnGRN :one
SELECT
    r.id, r.number, r.company_id, r.supplier_id, r.grn_id, r.warehouse_id,
    r.return_date, r.status, r.reason, r.notes,
    r.created_by, r.confirmed_by, r.confirmed_at, r.voided_by, r.voided_at,
    r.created_at, r.updated_at
FROM goods_return_grns r
WHERE r.id = $1
`

func (q *Queries) GetGoodsReturnGRN(ctx context.Context, id int64) (GoodsReturnGrn, error) {
	row := q.db.QueryRow(ctx, getGoodsReturnGRN, id)
	var i GoodsReturnGrn
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.CompanyID,
		&i.SupplierID,
		&i.GrnID,
		&i.WarehouseID,
		&i.ReturnDate,
		&i.Status,
		&i.Reason,
		&i.Notes,
		&i.CreatedBy,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
		&i.VoidedBy,
		&i.VoidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPO = `-- name: GetPO :one
SELECT id, number, supplier_id, status, currency, expected_date, note
FROM pos WHERE id = $1
`

type GetPORow struct {
	ID           int64       `json:"id"`
	Number       string      `json:"number"`
	SupplierID   int64       `json:"supplier_id"`
	Status       string      `json:"status"`
	Currency     string      `json:"currency"`
	ExpectedDate pgtype.Date `json:"expected_date"`
	Note         string      `json:"note"`
}

func (q *Queries) GetPO(ctx context.Context, id int64) (GetPORow, error) {
	row := q.db.QueryRow(ctx, getPO, id)
	var i GetPORow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.SupplierID,
		&i.Status,
		&i.Currency,
		&i.ExpectedDate,
		&i.Note,
	)
	return i, err
}

const getPOLines = `-- name: GetPOLines :many
SELECT id, po_id, product_id, qty, price, tax_id, note
FROM po_lines WHERE po_id = $1 ORDER BY id
`

func (q *Queries) GetPOLines(ctx context.Context, poID int64) ([]PoLine, error) {
	rows, err := q.db.Query(ctx, getPOLines, poID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PoLine
	for rows.Next() {
		var i PoLine
		if err := rows.Scan(
			&i.ID,
			&i.PoID,
			&i.ProductID,
			&i.Qty,
			&i.Price,
			&i.TaxID,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPR = `-- name: GetPR :one
SELECT id, number, supplier_id, request_by, status, note
FROM prs WHERE id = $1
`

type GetPRRow struct {
	ID         int64       `json:"id"`
	Number     string      `json:"number"`
	SupplierID pgtype.Int8 `json:"supplier_id"`
	RequestBy  int64       `json:"request_by"`
	Status     string      `json:"status"`
	Note       string      `json:"note"`
}

func (q *Queries) GetPR(ctx context.Context, id int64) (GetPRRow, error) {
	row := q.db.QueryRow(ctx, getPR, id)
	var i GetPRRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.SupplierID,
		&i.RequestBy,
		&i.Status,
		&i.Note,
	)
	return i, err
}

const getPRLines = `-- name: GetPRLines :many
SELECT id, pr_id, product_id, qty, note
FROM pr_lines WHERE pr_id = $1 ORDER BY id
`

func (q *Queries) GetPRLines(ctx context.Context, prID int64) ([]PrLine, error) {
	rows, err := q.db.Query(ctx, getPRLines, prID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrLine
	for rows.Next() {
		var i PrLine
		if err := rows.Scan(
			&i.ID,
			&i.PrID,
			&i.ProductID,
			&i.Qty,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertGRNLine = `-- name: InsertGRNLine :exec
INSERT INTO grn_lines (grn_id, product_id, qty, unit_cost)
VALUES ($1, $2, $3, $4)
`

type InsertGRNLineParams struct {
	GrnID     int64          `json:"grn_id"`
	ProductID int64          `json:"product_id"`
	Qty       pgtype.Numeric `json:"qty"`
	UnitCost  pgtype.Numeric `json:"unit_cost"`
}

func (q *Queries) InsertGRNLine(ctx context.Context, arg InsertGRNLineParams) error {
	_, err := q.db.Exec(ctx, insertGRNLine,
		arg.GrnID,
		arg.ProductID,
		arg.Qty,
		arg.UnitCost,
	)
	return err
}

const insertPOLine = `-- name: InsertPOLine :exec
INSERT INTO po_lines (po_id, product_id, qty, price, tax_id, note)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertPOLineParams struct {
	PoID      int64          `json:"po_id"`
	ProductID int64          `json:"product_id"`
	Qty       pgtype.Numeric `json:"qty"`
	Price     pgtype.Numeric `json:"price"`
	TaxID     pgtype.Int8    `json:"tax_id"`
	Note      string         `json:"note"`
}

func (q *Queries) InsertPOLine(ctx context.Context, arg InsertPOLineParams) error {
	_, err := q.db.Exec(ctx, insertPOLine,
		arg.PoID,
		arg.ProductID,
		arg.Qty,
		arg.Price,
		arg.TaxID,
		arg.Note,
	)
	return err
}

const insertPRLine = `-- name: InsertPRLine :exec
INSERT INTO pr_lines (pr_id, product_id, qty, note)
VALUES ($1, $2, $3, $4)
`

type InsertPRLineParams struct {
	PrID      int64          `json:"pr_id"`
	ProductID int64          `json:"product_id"`
	Qty       pgtype.Numeric `json:"qty"`
	Note      string         `json:"note"`
}

func (q *Queries) InsertPRLine(ctx context.Context, arg InsertPRLineParams) error {
	_, err := q.db.Exec(ctx, insertPRLine,
		arg.PrID,
		arg.ProductID,
		arg.Qty,
		arg.Note,
	)
	return err
}

const listGoodsReturnGRNLines = `-- name: ListGoodsReturnGRNLines :many
SELECT id, goods_return_grn_id, grn_line_id, product_id,
       quantity_returned, unit_cost, notes, line_order, created_at, updated_at
FROM goods_return_grn_lines
WHERE goods_return_grn_id = $1
ORDER BY line_order
`

func (q *Queries) ListGoodsReturnGRNLines(ctx context.Context, goodsReturnGrnID int64) ([]GoodsReturnGrnLine, error) {
	rows, err := q.db.Query(ctx, listGoodsReturnGRNLines, goodsReturnGrnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoodsReturnGrnLine
	for rows.Next() {
		var i GoodsReturnGrnLine
		if err := rows.Scan(
			&i.ID,
			&i.GoodsReturnGrnID,
			&i.GrnLineID,
			&i.ProductID,
			&i.QuantityReturned,
			&i.UnitCost,
			&i.Notes,
			&i.LineOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoodsReturnGRNs = `-- name: ListGoodsReturnGRNs :many
SELECT
    r.id, r.number, r.company_id, r.supplier_id, r.grn_id, r.warehouse_id,
    r.return_date, r.status, r.reason, r.notes,
    r.created_by, r.confirmed_by, r.confirmed_at, r.voided_by, r.voided_at,
    r.created_at, r.updated_at
FROM goods_return_grns r
ORDER BY r.created_at DESC
`

func (q *Queries) ListGoodsReturnGRNs(ctx context.Context) ([]GoodsReturnGrn, error) {
	rows, err := q.db.Query(ctx, listGoodsReturnGRNs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoodsReturnGrn
	for rows.Next() {
		var i GoodsReturnGrn
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.CompanyID,
			&i.SupplierID,
			&i.GrnID,
			&i.WarehouseID,
			&i.ReturnDate,
			&i.Status,
			&i.Reason,
			&i.Notes,
			&i.CreatedBy,
			&i.ConfirmedBy,
			&i.ConfirmedAt,
			&i.VoidedBy,
			&i.VoidedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pOExistsByNumber = `-- name: POExistsByNumber :one
SELECT EXISTS(SELECT 1 FROM pos WHERE number = $1) AS exists
`

func (q *Queries) POExistsByNumber(ctx context.Context, number string) (bool, error) {
	row := q.db.QueryRow(ctx, pOExistsByNumber, number)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const pRExistsByNumber = `-- name: PRExistsByNumber :one
SELECT EXISTS(SELECT 1 FROM prs WHERE number = $1) AS exists
`

func (q *Queries) PRExistsByNumber(ctx context.Context, number string) (bool, error) {
	row := q.db.QueryRow(ctx, pRExistsByNumber, number)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setPOApproval = `-- name: SetPOApproval :exec
UPDATE pos SET approved_by = $1, approved_at = $2 WHERE id = $3
`

type SetPOApprovalParams struct {
	ApprovedBy pgtype.Int8        `json:"approved_by"`
	ApprovedAt pgtype.Timestamptz `json:"approved_at"`
	ID         int64              `json:"id"`
}

func (q *Queries) SetPOApproval(ctx context.Context, arg SetPOApprovalParams) error {
	_, err := q.db.Exec(ctx, setPOApproval, arg.ApprovedBy, arg.ApprovedAt, arg.ID)
	return err
}

const updateGRNStatus = `-- name: UpdateGRNStatus :exec
UPDATE grns SET status = $1 WHERE id = $2
`

type UpdateGRNStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateGRNStatus(ctx context.Context, arg UpdateGRNStatusParams) error {
	_, err := q.db.Exec(ctx, updateGRNStatus, arg.Status, arg.ID)
	return err
}

const updateGoodsReturnGRNStatus = `-- name: UpdateGoodsReturnGRNStatus :exec
UPDATE goods_return_grns
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateGoodsReturnGRNStatusParams struct {
	ID     int64                `json:"id"`
	Status GoodsReturnGrnStatus `json:"status"`
}

func (q *Queries) UpdateGoodsReturnGRNStatus(ctx context.Context, arg UpdateGoodsReturnGRNStatusParams) error {
	_, err := q.db.Exec(ctx, updateGoodsReturnGRNStatus, arg.ID, arg.Status)
	return err
}

const updatePOStatus = `-- name: UpdatePOStatus :exec
UPDATE pos SET status = $1 WHERE id = $2
`

type UpdatePOStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdatePOStatus(ctx context.Context, arg UpdatePOStatusParams) error {
	_, err := q.db.Exec(ctx, updatePOStatus, arg.Status, arg.ID)
	return err
}

const updatePRStatus = `-- name: UpdatePRStatus :exec
UPDATE prs SET status = $1 WHERE id = $2
`

type UpdatePRStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdatePRStatus(ctx context.Context, arg UpdatePRStatusParams) error {
	_, err := q.db.Exec(ctx, updatePRStatus, arg.Status, arg.ID)
	return err
}
