// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: procurement_scorecards.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const calculateOTIFScore = `-- name: CalculateOTIFScore :one
SELECT COUNT(*) as total_receipts,
       COALESCE(SUM(CASE WHEN g.received_at::date <= p.expected_date THEN 1 ELSE 0 END), 0)::BIGINT as ontime_receipts
FROM grns g
JOIN pos p ON p.id = g.po_id
WHERE g.company_id = $1 AND g.supplier_id = $2
  AND g.status = 'POSTED'
  AND p.expected_date IS NOT NULL
  AND g.received_at >= $3 AND g.received_at <= $4
`

type CalculateOTIFScoreParams struct {
	CompanyID    pgtype.Int8        `json:"company_id"`
	SupplierID   int64              `json:"supplier_id"`
	ReceivedAt   pgtype.Timestamptz `json:"received_at"`
	ReceivedAt_2 pgtype.Timestamptz `json:"received_at_2"`
}

type CalculateOTIFScoreRow struct {
	TotalReceipts  int64 `json:"total_receipts"`
	OntimeReceipts int64 `json:"ontime_receipts"`
}

func (q *Queries) CalculateOTIFScore(ctx context.Context, arg CalculateOTIFScoreParams) (CalculateOTIFScoreRow, error) {
	row := q.db.QueryRow(ctx, calculateOTIFScore,
		arg.CompanyID,
		arg.SupplierID,
		arg.ReceivedAt,
		arg.ReceivedAt_2,
	)
	var i CalculateOTIFScoreRow
	err := row.Scan(&i.TotalReceipts, &i.OntimeReceipts)
	return i, err
}

const calculatePriceAdherenceScore = `-- name: CalculatePriceAdherenceScore :one
SELECT COUNT(*) as total_pos,
       COALESCE(SUM(CASE WHEN NOT EXISTS (
           SELECT 1
           FROM po_contract_variances pending
           WHERE pending.po_line_id = pl.id
             AND pending.approval_status = 'PENDING'
       ) THEN 1 ELSE 0 END), 0)::BIGINT as compliant_pos
FROM po_lines pl
JOIN pos p ON p.id = pl.po_id
WHERE p.company_id = $1 AND p.supplier_id = $2
  AND p.status <> 'CANCELLED'
  AND p.created_at >= $3 AND p.created_at <= $4
`

type CalculatePriceAdherenceScoreParams struct {
	CompanyID   pgtype.Int8        `json:"company_id"`
	SupplierID  int64              `json:"supplier_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type CalculatePriceAdherenceScoreRow struct {
	TotalPos     int64 `json:"total_pos"`
	CompliantPos int64 `json:"compliant_pos"`
}

func (q *Queries) CalculatePriceAdherenceScore(ctx context.Context, arg CalculatePriceAdherenceScoreParams) (CalculatePriceAdherenceScoreRow, error) {
	row := q.db.QueryRow(ctx, calculatePriceAdherenceScore,
		arg.CompanyID,
		arg.SupplierID,
		arg.CreatedAt,
		arg.CreatedAt_2,
	)
	var i CalculatePriceAdherenceScoreRow
	err := row.Scan(&i.TotalPos, &i.CompliantPos)
	return i, err
}

const calculateQualityScore = `-- name: CalculateQualityScore :one
SELECT COALESCE(SUM(gl.qty - COALESCE(returned.quantity_returned, 0)), 0)::BIGINT as accepted_qty,
       COALESCE(SUM(COALESCE(returned.quantity_returned, 0)), 0)::BIGINT as rejected_qty
FROM grn_lines gl
JOIN grns g ON g.id = gl.grn_id
LEFT JOIN (
    SELECT rgl.grn_line_id, SUM(rgl.quantity_returned) AS quantity_returned
    FROM goods_return_grn_lines rgl
    JOIN goods_return_grns r ON r.id = rgl.goods_return_grn_id
    WHERE r.status = 'CONFIRMED'
    GROUP BY rgl.grn_line_id
) returned ON returned.grn_line_id = gl.id
WHERE g.company_id = $1 AND g.supplier_id = $2
  AND g.status = 'POSTED'
  AND g.received_at >= $3 AND g.received_at <= $4
`

type CalculateQualityScoreParams struct {
	CompanyID    pgtype.Int8        `json:"company_id"`
	SupplierID   int64              `json:"supplier_id"`
	ReceivedAt   pgtype.Timestamptz `json:"received_at"`
	ReceivedAt_2 pgtype.Timestamptz `json:"received_at_2"`
}

type CalculateQualityScoreRow struct {
	AcceptedQty int64 `json:"accepted_qty"`
	RejectedQty int64 `json:"rejected_qty"`
}

func (q *Queries) CalculateQualityScore(ctx context.Context, arg CalculateQualityScoreParams) (CalculateQualityScoreRow, error) {
	row := q.db.QueryRow(ctx, calculateQualityScore,
		arg.CompanyID,
		arg.SupplierID,
		arg.ReceivedAt,
		arg.ReceivedAt_2,
	)
	var i CalculateQualityScoreRow
	err := row.Scan(&i.AcceptedQty, &i.RejectedQty)
	return i, err
}

const calculateRFQResponsivenessScore = `-- name: CalculateRFQResponsivenessScore :one
SELECT COUNT(*) as total_rfqs,
       COALESCE(SUM(CASE WHEN rb.id IS NOT NULL THEN 1 ELSE 0 END), 0)::BIGINT as responded_rfqs
FROM rfq_suppliers rs
JOIN rfqs r ON r.id = rs.rfq_id
LEFT JOIN rfq_bids rb ON rb.rfq_id = r.id AND rb.supplier_id = rs.supplier_id AND rb.status = 'SUBMITTED'
WHERE r.company_id = $1 AND rs.supplier_id = $2 AND r.created_at >= $3 AND r.created_at <= $4
`

type CalculateRFQResponsivenessScoreParams struct {
	CompanyID   int64              `json:"company_id"`
	SupplierID  int64              `json:"supplier_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type CalculateRFQResponsivenessScoreRow struct {
	TotalRfqs     int64 `json:"total_rfqs"`
	RespondedRfqs int64 `json:"responded_rfqs"`
}

func (q *Queries) CalculateRFQResponsivenessScore(ctx context.Context, arg CalculateRFQResponsivenessScoreParams) (CalculateRFQResponsivenessScoreRow, error) {
	row := q.db.QueryRow(ctx, calculateRFQResponsivenessScore,
		arg.CompanyID,
		arg.SupplierID,
		arg.CreatedAt,
		arg.CreatedAt_2,
	)
	var i CalculateRFQResponsivenessScoreRow
	err := row.Scan(&i.TotalRfqs, &i.RespondedRfqs)
	return i, err
}
