// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: qms.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditsWithPrefix = `-- name: CountAuditsWithPrefix :one
SELECT COUNT(*) FROM audits WHERE company_id = $1 AND number LIKE $2 || '%'
`

type CountAuditsWithPrefixParams struct {
	CompanyID int64       `json:"company_id"`
	Column2   pgtype.Text `json:"column_2"`
}

func (q *Queries) CountAuditsWithPrefix(ctx context.Context, arg CountAuditsWithPrefixParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditsWithPrefix, arg.CompanyID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCAPAsWithPrefix = `-- name: CountCAPAsWithPrefix :one
SELECT COUNT(*) FROM capas WHERE company_id = $1 AND number LIKE $2 || '%'
`

type CountCAPAsWithPrefixParams struct {
	CompanyID int64       `json:"company_id"`
	Column2   pgtype.Text `json:"column_2"`
}

func (q *Queries) CountCAPAsWithPrefix(ctx context.Context, arg CountCAPAsWithPrefixParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCAPAsWithPrefix, arg.CompanyID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNCRsWithPrefix = `-- name: CountNCRsWithPrefix :one
SELECT COUNT(*) FROM ncrs WHERE company_id = $1 AND number LIKE $2 || '%'
`

type CountNCRsWithPrefixParams struct {
	CompanyID int64       `json:"company_id"`
	Column2   pgtype.Text `json:"column_2"`
}

func (q *Queries) CountNCRsWithPrefix(ctx context.Context, arg CountNCRsWithPrefixParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNCRsWithPrefix, arg.CompanyID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createATEIntegration = `-- name: CreateATEIntegration :one
INSERT INTO qms_ate_integrations (
    company_id, equipment_name, ip_address, protocol, status, last_ping_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id
`

type CreateATEIntegrationParams struct {
	CompanyID     int64              `json:"company_id"`
	EquipmentName string             `json:"equipment_name"`
	IpAddress     string             `json:"ip_address"`
	Protocol      string             `json:"protocol"`
	Status        string             `json:"status"`
	LastPingAt    pgtype.Timestamptz `json:"last_ping_at"`
}

func (q *Queries) CreateATEIntegration(ctx context.Context, arg CreateATEIntegrationParams) (int64, error) {
	row := q.db.QueryRow(ctx, createATEIntegration,
		arg.CompanyID,
		arg.EquipmentName,
		arg.IpAddress,
		arg.Protocol,
		arg.Status,
		arg.LastPingAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createATETestResult = `-- name: CreateATETestResult :one
INSERT INTO qms_ate_test_results (
    equipment_id, product_serial, test_sequence, pass, raw_data, tested_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id
`

type CreateATETestResultParams struct {
	EquipmentID   int64              `json:"equipment_id"`
	ProductSerial string             `json:"product_serial"`
	TestSequence  string             `json:"test_sequence"`
	Pass          bool               `json:"pass"`
	RawData       string             `json:"raw_data"`
	TestedAt      pgtype.Timestamptz `json:"tested_at"`
}

func (q *Queries) CreateATETestResult(ctx context.Context, arg CreateATETestResultParams) (int64, error) {
	row := q.db.QueryRow(ctx, createATETestResult,
		arg.EquipmentID,
		arg.ProductSerial,
		arg.TestSequence,
		arg.Pass,
		arg.RawData,
		arg.TestedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createLabSample = `-- name: CreateLabSample :one
INSERT INTO qms_lab_samples (
    company_id, sample_number, source_type, source_id, status, priority, assigned_lab, collected_by, collected_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id
`

type CreateLabSampleParams struct {
	CompanyID    int64              `json:"company_id"`
	SampleNumber string             `json:"sample_number"`
	SourceType   string             `json:"source_type"`
	SourceID     int64              `json:"source_id"`
	Status       string             `json:"status"`
	Priority     string             `json:"priority"`
	AssignedLab  string             `json:"assigned_lab"`
	CollectedBy  int64              `json:"collected_by"`
	CollectedAt  pgtype.Timestamptz `json:"collected_at"`
}

func (q *Queries) CreateLabSample(ctx context.Context, arg CreateLabSampleParams) (int64, error) {
	row := q.db.QueryRow(ctx, createLabSample,
		arg.CompanyID,
		arg.SampleNumber,
		arg.SourceType,
		arg.SourceID,
		arg.Status,
		arg.Priority,
		arg.AssignedLab,
		arg.CollectedBy,
		arg.CollectedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createLabTest = `-- name: CreateLabTest :one
INSERT INTO qms_lab_tests (
    sample_id, test_name, method, result_value, is_pass, tested_by, tested_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id
`

type CreateLabTestParams struct {
	SampleID    int64              `json:"sample_id"`
	TestName    string             `json:"test_name"`
	Method      string             `json:"method"`
	ResultValue string             `json:"result_value"`
	IsPass      bool               `json:"is_pass"`
	TestedBy    int64              `json:"tested_by"`
	TestedAt    pgtype.Timestamptz `json:"tested_at"`
}

func (q *Queries) CreateLabTest(ctx context.Context, arg CreateLabTestParams) (int64, error) {
	row := q.db.QueryRow(ctx, createLabTest,
		arg.SampleID,
		arg.TestName,
		arg.Method,
		arg.ResultValue,
		arg.IsPass,
		arg.TestedBy,
		arg.TestedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createSPCChart = `-- name: CreateSPCChart :one
INSERT INTO qms_spc_charts (
    company_id, name, characteristic, ucl, lcl, uwl, lwl, target_value, sample_interval_min, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id
`

type CreateSPCChartParams struct {
	CompanyID         int64          `json:"company_id"`
	Name              string         `json:"name"`
	Characteristic    string         `json:"characteristic"`
	Ucl               pgtype.Numeric `json:"ucl"`
	Lcl               pgtype.Numeric `json:"lcl"`
	Uwl               pgtype.Numeric `json:"uwl"`
	Lwl               pgtype.Numeric `json:"lwl"`
	TargetValue       pgtype.Numeric `json:"target_value"`
	SampleIntervalMin int32          `json:"sample_interval_min"`
	IsActive          bool           `json:"is_active"`
}

func (q *Queries) CreateSPCChart(ctx context.Context, arg CreateSPCChartParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSPCChart,
		arg.CompanyID,
		arg.Name,
		arg.Characteristic,
		arg.Ucl,
		arg.Lcl,
		arg.Uwl,
		arg.Lwl,
		arg.TargetValue,
		arg.SampleIntervalMin,
		arg.IsActive,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createSPCSample = `-- name: CreateSPCSample :one
INSERT INTO qms_spc_samples (
    chart_id, value, sampled_at, operator_id, is_outlier, notes
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id
`

type CreateSPCSampleParams struct {
	ChartID    int64              `json:"chart_id"`
	Value      pgtype.Numeric     `json:"value"`
	SampledAt  pgtype.Timestamptz `json:"sampled_at"`
	OperatorID int64              `json:"operator_id"`
	IsOutlier  bool               `json:"is_outlier"`
	Notes      pgtype.Text        `json:"notes"`
}

func (q *Queries) CreateSPCSample(ctx context.Context, arg CreateSPCSampleParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSPCSample,
		arg.ChartID,
		arg.Value,
		arg.SampledAt,
		arg.OperatorID,
		arg.IsOutlier,
		arg.Notes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getATEIntegration = `-- name: GetATEIntegration :one
SELECT id, company_id, equipment_name, ip_address, protocol, status, last_ping_at, created_at FROM qms_ate_integrations WHERE id = $1
`

func (q *Queries) GetATEIntegration(ctx context.Context, id int64) (QmsAteIntegration, error) {
	row := q.db.QueryRow(ctx, getATEIntegration, id)
	var i QmsAteIntegration
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EquipmentName,
		&i.IpAddress,
		&i.Protocol,
		&i.Status,
		&i.LastPingAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAudit = `-- name: GetAudit :one
SELECT id, company_id, number, title, description, audit_type, status, standard,
       scope, lead_auditor_id, audit_team_ids, auditee_id,
       planned_start, planned_end, actual_start, actual_end,
       report_number, report_date, created_by, created_at, updated_at
FROM audits
WHERE id = $1
`

func (q *Queries) GetAudit(ctx context.Context, id int64) (Audit, error) {
	row := q.db.QueryRow(ctx, getAudit, id)
	var i Audit
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.AuditType,
		&i.Status,
		&i.Standard,
		&i.Scope,
		&i.LeadAuditorID,
		&i.AuditTeamIds,
		&i.AuditeeID,
		&i.PlannedStart,
		&i.PlannedEnd,
		&i.ActualStart,
		&i.ActualEnd,
		&i.ReportNumber,
		&i.ReportDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuditFinding = `-- name: GetAuditFinding :one
SELECT id, audit_id, finding_number, category, clause, description, evidence,
       requirement, risk_level, status, response, response_due_date, response_date,
       assigned_to, verified_by, verified_at, created_at, updated_at
FROM audit_findings
WHERE id = $1
`

func (q *Queries) GetAuditFinding(ctx context.Context, id int64) (AuditFinding, error) {
	row := q.db.QueryRow(ctx, getAuditFinding, id)
	var i AuditFinding
	err := row.Scan(
		&i.ID,
		&i.AuditID,
		&i.FindingNumber,
		&i.Category,
		&i.Clause,
		&i.Description,
		&i.Evidence,
		&i.Requirement,
		&i.RiskLevel,
		&i.Status,
		&i.Response,
		&i.ResponseDueDate,
		&i.ResponseDate,
		&i.AssignedTo,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCAPA = `-- name: GetCAPA :one
SELECT id, company_id, number, title, description, source_type, source_id, source_reference,
       status, priority, owner_id, team_members, root_cause, root_cause_method,
       corrective_action, preventive_action, verification_method, verification_result,
       effectiveness_check, target_date, completion_date, effectiveness_date,
       created_by, created_at, updated_at
FROM capas
WHERE id = $1
`

func (q *Queries) GetCAPA(ctx context.Context, id int64) (Capa, error) {
	row := q.db.QueryRow(ctx, getCAPA, id)
	var i Capa
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.SourceType,
		&i.SourceID,
		&i.SourceReference,
		&i.Status,
		&i.Priority,
		&i.OwnerID,
		&i.TeamMembers,
		&i.RootCause,
		&i.RootCauseMethod,
		&i.CorrectiveAction,
		&i.PreventiveAction,
		&i.VerificationMethod,
		&i.VerificationResult,
		&i.EffectivenessCheck,
		&i.TargetDate,
		&i.CompletionDate,
		&i.EffectivenessDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerComplaint = `-- name: GetCustomerComplaint :one
SELECT id, company_id, complaint_number, customer_id, title, description,
       status, severity, assigned_to, response_evidence, received_at, closed_at,
       created_by, created_at, updated_at
FROM customer_complaints
WHERE id = $1
`

type GetCustomerComplaintRow struct {
	ID               int64              `json:"id"`
	CompanyID        int64              `json:"company_id"`
	ComplaintNumber  string             `json:"complaint_number"`
	CustomerID       int64              `json:"customer_id"`
	Title            string             `json:"title"`
	Description      string             `json:"description"`
	Status           string             `json:"status"`
	Severity         string             `json:"severity"`
	AssignedTo       pgtype.Int8        `json:"assigned_to"`
	ResponseEvidence pgtype.Text        `json:"response_evidence"`
	ReceivedAt       pgtype.Timestamptz `json:"received_at"`
	ClosedAt         pgtype.Timestamptz `json:"closed_at"`
	CreatedBy        int64              `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCustomerComplaint(ctx context.Context, id int64) (GetCustomerComplaintRow, error) {
	row := q.db.QueryRow(ctx, getCustomerComplaint, id)
	var i GetCustomerComplaintRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ComplaintNumber,
		&i.CustomerID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Severity,
		&i.AssignedTo,
		&i.ResponseEvidence,
		&i.ReceivedAt,
		&i.ClosedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLabSample = `-- name: GetLabSample :one
SELECT id, company_id, sample_number, source_type, source_id, status, priority, assigned_lab, collected_by, collected_at, completed_at, created_at FROM qms_lab_samples WHERE id = $1
`

func (q *Queries) GetLabSample(ctx context.Context, id int64) (QmsLabSample, error) {
	row := q.db.QueryRow(ctx, getLabSample, id)
	var i QmsLabSample
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SampleNumber,
		&i.SourceType,
		&i.SourceID,
		&i.Status,
		&i.Priority,
		&i.AssignedLab,
		&i.CollectedBy,
		&i.CollectedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNCR = `-- name: GetNCR :one
SELECT id, company_id, number, title, description, source_type, source_id, source_reference,
       category, severity, status, detected_by, detected_at, detected_location,
       responsible_party_id, assigned_to, target_closure_date, actual_closure_date,
       root_cause, containment_action, created_by, created_at, updated_at
FROM ncrs
WHERE id = $1
`

func (q *Queries) GetNCR(ctx context.Context, id int64) (Ncr, error) {
	row := q.db.QueryRow(ctx, getNCR, id)
	var i Ncr
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.SourceType,
		&i.SourceID,
		&i.SourceReference,
		&i.Category,
		&i.Severity,
		&i.Status,
		&i.DetectedBy,
		&i.DetectedAt,
		&i.DetectedLocation,
		&i.ResponsiblePartyID,
		&i.AssignedTo,
		&i.TargetClosureDate,
		&i.ActualClosureDate,
		&i.RootCause,
		&i.ContainmentAction,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNCRDisposition = `-- name: GetNCRDisposition :one
SELECT id, ncr_id, disposition_type, description, approved_by, approved_at, created_at
FROM ncr_dispositions
WHERE ncr_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetNCRDisposition(ctx context.Context, ncrID int64) (NcrDisposition, error) {
	row := q.db.QueryRow(ctx, getNCRDisposition, ncrID)
	var i NcrDisposition
	err := row.Scan(
		&i.ID,
		&i.NcrID,
		&i.DispositionType,
		&i.Description,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getQMSInspection = `-- name: GetQMSInspection :one
SELECT id, company_id, name, description, reference_module, reference_id,
       status, inspector_id, scheduled_at, started_at, completed_at,
       created_by, created_at, updated_at
FROM qms_inspections
WHERE id = $1
`

type GetQMSInspectionRow struct {
	ID              int64              `json:"id"`
	CompanyID       int64              `json:"company_id"`
	Name            string             `json:"name"`
	Description     pgtype.Text        `json:"description"`
	ReferenceModule pgtype.Text        `json:"reference_module"`
	ReferenceID     pgtype.Int8        `json:"reference_id"`
	Status          string             `json:"status"`
	InspectorID     pgtype.Int8        `json:"inspector_id"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	CreatedBy       int64              `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetQMSInspection(ctx context.Context, id int64) (GetQMSInspectionRow, error) {
	row := q.db.QueryRow(ctx, getQMSInspection, id)
	var i GetQMSInspectionRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.ReferenceModule,
		&i.ReferenceID,
		&i.Status,
		&i.InspectorID,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQMSInspectionPlan = `-- name: GetQMSInspectionPlan :one
SELECT id, company_id, name, description, reference_module, reference_id, is_active, created_at, updated_at, created_by
FROM qms_inspection_plans
WHERE id = $1
`

func (q *Queries) GetQMSInspectionPlan(ctx context.Context, id int64) (QmsInspectionPlan, error) {
	row := q.db.QueryRow(ctx, getQMSInspectionPlan, id)
	var i QmsInspectionPlan
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.ReferenceModule,
		&i.ReferenceID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getQualityObjective = `-- name: GetQualityObjective :one
SELECT id, company_id, name, description, metric_type, target_value, current_value,
       unit, frequency, owner_id, status, start_date, end_date, created_at, updated_at
FROM quality_objectives
WHERE id = $1
`

func (q *Queries) GetQualityObjective(ctx context.Context, id int64) (QualityObjective, error) {
	row := q.db.QueryRow(ctx, getQualityObjective, id)
	var i QualityObjective
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.MetricType,
		&i.TargetValue,
		&i.CurrentValue,
		&i.Unit,
		&i.Frequency,
		&i.OwnerID,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQualityObjectiveMeasurement = `-- name: GetQualityObjectiveMeasurement :one
SELECT id, objective_id, value, measurement_date, notes, recorded_by, created_at
FROM quality_objective_measurements
WHERE id = $1
`

func (q *Queries) GetQualityObjectiveMeasurement(ctx context.Context, id int64) (QualityObjectiveMeasurement, error) {
	row := q.db.QueryRow(ctx, getQualityObjectiveMeasurement, id)
	var i QualityObjectiveMeasurement
	err := row.Scan(
		&i.ID,
		&i.ObjectiveID,
		&i.Value,
		&i.MeasurementDate,
		&i.Notes,
		&i.RecordedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getSPCChart = `-- name: GetSPCChart :one
SELECT id, company_id, name, characteristic, ucl, lcl, uwl, lwl, target_value, sample_interval_min, is_active, created_at FROM qms_spc_charts WHERE id = $1
`

func (q *Queries) GetSPCChart(ctx context.Context, id int64) (QmsSpcChart, error) {
	row := q.db.QueryRow(ctx, getSPCChart, id)
	var i QmsSpcChart
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Characteristic,
		&i.Ucl,
		&i.Lcl,
		&i.Uwl,
		&i.Lwl,
		&i.TargetValue,
		&i.SampleIntervalMin,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getSPCSamples = `-- name: GetSPCSamples :many
SELECT id, chart_id, value, sampled_at, operator_id, is_outlier, notes FROM qms_spc_samples WHERE chart_id = $1 ORDER BY sampled_at DESC LIMIT $2
`

type GetSPCSamplesParams struct {
	ChartID int64 `json:"chart_id"`
	Limit   int32 `json:"limit"`
}

func (q *Queries) GetSPCSamples(ctx context.Context, arg GetSPCSamplesParams) ([]QmsSpcSample, error) {
	rows, err := q.db.Query(ctx, getSPCSamples, arg.ChartID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QmsSpcSample
	for rows.Next() {
		var i QmsSpcSample
		if err := rows.Scan(
			&i.ID,
			&i.ChartID,
			&i.Value,
			&i.SampledAt,
			&i.OperatorID,
			&i.IsOutlier,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSupplierAudit = `-- name: GetSupplierAudit :one
SELECT id, company_id, supplier_id, audit_number, audit_type, status, standard,
       planned_date, actual_date, score, lead_auditor_id, report_number, created_by, created_at, updated_at
FROM supplier_audits
WHERE id = $1
`

func (q *Queries) GetSupplierAudit(ctx context.Context, id int64) (SupplierAudit, error) {
	row := q.db.QueryRow(ctx, getSupplierAudit, id)
	var i SupplierAudit
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SupplierID,
		&i.AuditNumber,
		&i.AuditType,
		&i.Status,
		&i.Standard,
		&i.PlannedDate,
		&i.ActualDate,
		&i.Score,
		&i.LeadAuditorID,
		&i.ReportNumber,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplierQuality = `-- name: GetSupplierQuality :one
SELECT id, company_id, supplier_id, status, quality_rating, risk_level,
       approved_date, expiry_date, last_audit_date, next_audit_date, notes, created_by, created_at, updated_at
FROM supplier_quality
WHERE id = $1
`

func (q *Queries) GetSupplierQuality(ctx context.Context, id int64) (SupplierQuality, error) {
	row := q.db.QueryRow(ctx, getSupplierQuality, id)
	var i SupplierQuality
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SupplierID,
		&i.Status,
		&i.QualityRating,
		&i.RiskLevel,
		&i.ApprovedDate,
		&i.ExpiryDate,
		&i.LastAuditDate,
		&i.NextAuditDate,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplierQualityBySupplier = `-- name: GetSupplierQualityBySupplier :one
SELECT id, company_id, supplier_id, status, quality_rating, risk_level,
       approved_date, expiry_date, last_audit_date, next_audit_date, notes, created_by, created_at, updated_at
FROM supplier_quality
WHERE company_id = $1 AND supplier_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetSupplierQualityBySupplierParams struct {
	CompanyID  int64 `json:"company_id"`
	SupplierID int64 `json:"supplier_id"`
}

func (q *Queries) GetSupplierQualityBySupplier(ctx context.Context, arg GetSupplierQualityBySupplierParams) (SupplierQuality, error) {
	row := q.db.QueryRow(ctx, getSupplierQualityBySupplier, arg.CompanyID, arg.SupplierID)
	var i SupplierQuality
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SupplierID,
		&i.Status,
		&i.QualityRating,
		&i.RiskLevel,
		&i.ApprovedDate,
		&i.ExpiryDate,
		&i.LastAuditDate,
		&i.NextAuditDate,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAudit = `-- name: InsertAudit :one

INSERT INTO audits (company_id, number, title, description, audit_type, status, standard,
                    scope, lead_auditor_id, audit_team_ids, auditee_id,
                    planned_start, planned_end, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id
`

type InsertAuditParams struct {
	CompanyID     int64       `json:"company_id"`
	Number        string      `json:"number"`
	Title         string      `json:"title"`
	Description   pgtype.Text `json:"description"`
	AuditType     string      `json:"audit_type"`
	Status        string      `json:"status"`
	Standard      pgtype.Text `json:"standard"`
	Scope         pgtype.Text `json:"scope"`
	LeadAuditorID int64       `json:"lead_auditor_id"`
	AuditTeamIds  []int64     `json:"audit_team_ids"`
	AuditeeID     pgtype.Int8 `json:"auditee_id"`
	PlannedStart  pgtype.Date `json:"planned_start"`
	PlannedEnd    pgtype.Date `json:"planned_end"`
	CreatedBy     int64       `json:"created_by"`
}

// =============================================================================
// AUDITS
// =============================================================================
func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAudit,
		arg.CompanyID,
		arg.Number,
		arg.Title,
		arg.Description,
		arg.AuditType,
		arg.Status,
		arg.Standard,
		arg.Scope,
		arg.LeadAuditorID,
		arg.AuditTeamIds,
		arg.AuditeeID,
		arg.PlannedStart,
		arg.PlannedEnd,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertAuditFinding = `-- name: InsertAuditFinding :one

INSERT INTO audit_findings (audit_id, finding_number, category, clause, description,
                            evidence, requirement, risk_level, status, assigned_to, response_due_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type InsertAuditFindingParams struct {
	AuditID         int64       `json:"audit_id"`
	FindingNumber   pgtype.Text `json:"finding_number"`
	Category        string      `json:"category"`
	Clause          pgtype.Text `json:"clause"`
	Description     string      `json:"description"`
	Evidence        pgtype.Text `json:"evidence"`
	Requirement     pgtype.Text `json:"requirement"`
	RiskLevel       string      `json:"risk_level"`
	Status          string      `json:"status"`
	AssignedTo      pgtype.Int8 `json:"assigned_to"`
	ResponseDueDate pgtype.Date `json:"response_due_date"`
}

// =============================================================================
// AUDIT FINDINGS
// =============================================================================
func (q *Queries) InsertAuditFinding(ctx context.Context, arg InsertAuditFindingParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAuditFinding,
		arg.AuditID,
		arg.FindingNumber,
		arg.Category,
		arg.Clause,
		arg.Description,
		arg.Evidence,
		arg.Requirement,
		arg.RiskLevel,
		arg.Status,
		arg.AssignedTo,
		arg.ResponseDueDate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertCAPA = `-- name: InsertCAPA :one

INSERT INTO capas (company_id, number, title, description, source_type, source_id, source_reference,
                   status, priority, owner_id, team_members, root_cause_method, target_date, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id
`

type InsertCAPAParams struct {
	CompanyID       int64       `json:"company_id"`
	Number          string      `json:"number"`
	Title           string      `json:"title"`
	Description     pgtype.Text `json:"description"`
	SourceType      string      `json:"source_type"`
	SourceID        pgtype.Int8 `json:"source_id"`
	SourceReference pgtype.Text `json:"source_reference"`
	Status          string      `json:"status"`
	Priority        string      `json:"priority"`
	OwnerID         int64       `json:"owner_id"`
	TeamMembers     []int64     `json:"team_members"`
	RootCauseMethod pgtype.Text `json:"root_cause_method"`
	TargetDate      pgtype.Date `json:"target_date"`
	CreatedBy       int64       `json:"created_by"`
}

// =============================================================================
// CORRECTIVE ACTIONS (CAPA)
// =============================================================================
func (q *Queries) InsertCAPA(ctx context.Context, arg InsertCAPAParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertCAPA,
		arg.CompanyID,
		arg.Number,
		arg.Title,
		arg.Description,
		arg.SourceType,
		arg.SourceID,
		arg.SourceReference,
		arg.Status,
		arg.Priority,
		arg.OwnerID,
		arg.TeamMembers,
		arg.RootCauseMethod,
		arg.TargetDate,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertCustomerComplaint = `-- name: InsertCustomerComplaint :one

INSERT INTO customer_complaints (company_id, complaint_number, customer_id, title, description,
                                 status, severity, assigned_to, received_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id
`

type InsertCustomerComplaintParams struct {
	CompanyID       int64              `json:"company_id"`
	ComplaintNumber string             `json:"complaint_number"`
	CustomerID      int64              `json:"customer_id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	Status          string             `json:"status"`
	Severity        string             `json:"severity"`
	AssignedTo      pgtype.Int8        `json:"assigned_to"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
	CreatedBy       int64              `json:"created_by"`
}

// =============================================================================
// CUSTOMER COMPLAINTS
// =============================================================================
func (q *Queries) InsertCustomerComplaint(ctx context.Context, arg InsertCustomerComplaintParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertCustomerComplaint,
		arg.CompanyID,
		arg.ComplaintNumber,
		arg.CustomerID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Severity,
		arg.AssignedTo,
		arg.ReceivedAt,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertNCR = `-- name: InsertNCR :one

INSERT INTO ncrs (company_id, number, title, description, source_type, source_id, source_reference,
                  category, severity, status, detected_by, detected_at, detected_location,
                  responsible_party_id, assigned_to, target_closure_date, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id
`

type InsertNCRParams struct {
	CompanyID          int64              `json:"company_id"`
	Number             string             `json:"number"`
	Title              string             `json:"title"`
	Description        pgtype.Text        `json:"description"`
	SourceType         string             `json:"source_type"`
	SourceID           pgtype.Int8        `json:"source_id"`
	SourceReference    pgtype.Text        `json:"source_reference"`
	Category           string             `json:"category"`
	Severity           string             `json:"severity"`
	Status             string             `json:"status"`
	DetectedBy         int64              `json:"detected_by"`
	DetectedAt         pgtype.Timestamptz `json:"detected_at"`
	DetectedLocation   pgtype.Text        `json:"detected_location"`
	ResponsiblePartyID pgtype.Int8        `json:"responsible_party_id"`
	AssignedTo         pgtype.Int8        `json:"assigned_to"`
	TargetClosureDate  pgtype.Date        `json:"target_closure_date"`
	CreatedBy          int64              `json:"created_by"`
}

// =============================================================================
// QMS NON-CONFORMANCE REPORTS
// =============================================================================
func (q *Queries) InsertNCR(ctx context.Context, arg InsertNCRParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertNCR,
		arg.CompanyID,
		arg.Number,
		arg.Title,
		arg.Description,
		arg.SourceType,
		arg.SourceID,
		arg.SourceReference,
		arg.Category,
		arg.Severity,
		arg.Status,
		arg.DetectedBy,
		arg.DetectedAt,
		arg.DetectedLocation,
		arg.ResponsiblePartyID,
		arg.AssignedTo,
		arg.TargetClosureDate,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertNCRDisposition = `-- name: InsertNCRDisposition :one

INSERT INTO ncr_dispositions (ncr_id, disposition_type, description, approved_by, approved_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertNCRDispositionParams struct {
	NcrID           int64              `json:"ncr_id"`
	DispositionType string             `json:"disposition_type"`
	Description     pgtype.Text        `json:"description"`
	ApprovedBy      int64              `json:"approved_by"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
}

// =============================================================================
// NCR DISPOSITIONS
// =============================================================================
func (q *Queries) InsertNCRDisposition(ctx context.Context, arg InsertNCRDispositionParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertNCRDisposition,
		arg.NcrID,
		arg.DispositionType,
		arg.Description,
		arg.ApprovedBy,
		arg.ApprovedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertQMSHold = `-- name: InsertQMSHold :one

INSERT INTO qms_holds (company_id, reference_module, reference_id, reason, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertQMSHoldParams struct {
	CompanyID       int64  `json:"company_id"`
	ReferenceModule string `json:"reference_module"`
	ReferenceID     int64  `json:"reference_id"`
	Reason          string `json:"reason"`
	CreatedBy       int64  `json:"created_by"`
}

// =============================================================================
// QMS HOLDS
// =============================================================================
func (q *Queries) InsertQMSHold(ctx context.Context, arg InsertQMSHoldParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertQMSHold,
		arg.CompanyID,
		arg.ReferenceModule,
		arg.ReferenceID,
		arg.Reason,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertQMSInspection = `-- name: InsertQMSInspection :one

INSERT INTO qms_inspections (company_id, name, description, reference_module, reference_id,
                             status, inspector_id, scheduled_at, started_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id
`

type InsertQMSInspectionParams struct {
	CompanyID       int64              `json:"company_id"`
	Name            string             `json:"name"`
	Description     pgtype.Text        `json:"description"`
	ReferenceModule pgtype.Text        `json:"reference_module"`
	ReferenceID     pgtype.Int8        `json:"reference_id"`
	Status          string             `json:"status"`
	InspectorID     pgtype.Int8        `json:"inspector_id"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CreatedBy       int64              `json:"created_by"`
}

// =============================================================================
// QMS INSPECTIONS
// =============================================================================
func (q *Queries) InsertQMSInspection(ctx context.Context, arg InsertQMSInspectionParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertQMSInspection,
		arg.CompanyID,
		arg.Name,
		arg.Description,
		arg.ReferenceModule,
		arg.ReferenceID,
		arg.Status,
		arg.InspectorID,
		arg.ScheduledAt,
		arg.StartedAt,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertQMSInspectionPlan = `-- name: InsertQMSInspectionPlan :one

INSERT INTO qms_inspection_plans (company_id, name, description, reference_module, reference_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertQMSInspectionPlanParams struct {
	CompanyID       int64       `json:"company_id"`
	Name            string      `json:"name"`
	Description     pgtype.Text `json:"description"`
	ReferenceModule pgtype.Text `json:"reference_module"`
	ReferenceID     pgtype.Int8 `json:"reference_id"`
	CreatedBy       int64       `json:"created_by"`
}

// =============================================================================
// QMS INSPECTION PLANS
// =============================================================================
func (q *Queries) InsertQMSInspectionPlan(ctx context.Context, arg InsertQMSInspectionPlanParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertQMSInspectionPlan,
		arg.CompanyID,
		arg.Name,
		arg.Description,
		arg.ReferenceModule,
		arg.ReferenceID,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertQMSInspectionResult = `-- name: InsertQMSInspectionResult :one

INSERT INTO qms_inspection_results (company_id, inspection_id, characteristic_name, expected_value, actual_value, is_conforming, notes, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertQMSInspectionResultParams struct {
	CompanyID          int64       `json:"company_id"`
	InspectionID       int64       `json:"inspection_id"`
	CharacteristicName string      `json:"characteristic_name"`
	ExpectedValue      pgtype.Text `json:"expected_value"`
	ActualValue        pgtype.Text `json:"actual_value"`
	IsConforming       bool        `json:"is_conforming"`
	Notes              pgtype.Text `json:"notes"`
	CreatedBy          int64       `json:"created_by"`
}

// =============================================================================
// QMS INSPECTION RESULTS
// =============================================================================
func (q *Queries) InsertQMSInspectionResult(ctx context.Context, arg InsertQMSInspectionResultParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertQMSInspectionResult,
		arg.CompanyID,
		arg.InspectionID,
		arg.CharacteristicName,
		arg.ExpectedValue,
		arg.ActualValue,
		arg.IsConforming,
		arg.Notes,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertQualityObjective = `-- name: InsertQualityObjective :one

INSERT INTO quality_objectives (company_id, name, description, metric_type, target_value,
                                unit, frequency, owner_id, status, start_date, end_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type InsertQualityObjectiveParams struct {
	CompanyID   int64       `json:"company_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	MetricType  string      `json:"metric_type"`
	TargetValue float64     `json:"target_value"`
	Unit        pgtype.Text `json:"unit"`
	Frequency   string      `json:"frequency"`
	OwnerID     int64       `json:"owner_id"`
	Status      string      `json:"status"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
}

// =============================================================================
// QUALITY OBJECTIVES
// =============================================================================
func (q *Queries) InsertQualityObjective(ctx context.Context, arg InsertQualityObjectiveParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertQualityObjective,
		arg.CompanyID,
		arg.Name,
		arg.Description,
		arg.MetricType,
		arg.TargetValue,
		arg.Unit,
		arg.Frequency,
		arg.OwnerID,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertQualityObjectiveMeasurement = `-- name: InsertQualityObjectiveMeasurement :one

INSERT INTO quality_objective_measurements (objective_id, value, measurement_date, notes, recorded_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertQualityObjectiveMeasurementParams struct {
	ObjectiveID     int64       `json:"objective_id"`
	Value           float64     `json:"value"`
	MeasurementDate pgtype.Date `json:"measurement_date"`
	Notes           pgtype.Text `json:"notes"`
	RecordedBy      int64       `json:"recorded_by"`
}

// =============================================================================
// QUALITY OBJECTIVE MEASUREMENTS
// =============================================================================
func (q *Queries) InsertQualityObjectiveMeasurement(ctx context.Context, arg InsertQualityObjectiveMeasurementParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertQualityObjectiveMeasurement,
		arg.ObjectiveID,
		arg.Value,
		arg.MeasurementDate,
		arg.Notes,
		arg.RecordedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSupplierAudit = `-- name: InsertSupplierAudit :one

INSERT INTO supplier_audits (company_id, supplier_id, audit_number, audit_type, status,
                             standard, planned_date, actual_date, score, lead_auditor_id, report_number, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id
`

type InsertSupplierAuditParams struct {
	CompanyID     int64       `json:"company_id"`
	SupplierID    int64       `json:"supplier_id"`
	AuditNumber   pgtype.Text `json:"audit_number"`
	AuditType     string      `json:"audit_type"`
	Status        string      `json:"status"`
	Standard      pgtype.Text `json:"standard"`
	PlannedDate   pgtype.Date `json:"planned_date"`
	ActualDate    pgtype.Date `json:"actual_date"`
	Score         float64     `json:"score"`
	LeadAuditorID int64       `json:"lead_auditor_id"`
	ReportNumber  pgtype.Text `json:"report_number"`
	CreatedBy     int64       `json:"created_by"`
}

// =============================================================================
// SUPPLIER AUDITS
// =============================================================================
func (q *Queries) InsertSupplierAudit(ctx context.Context, arg InsertSupplierAuditParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertSupplierAudit,
		arg.CompanyID,
		arg.SupplierID,
		arg.AuditNumber,
		arg.AuditType,
		arg.Status,
		arg.Standard,
		arg.PlannedDate,
		arg.ActualDate,
		arg.Score,
		arg.LeadAuditorID,
		arg.ReportNumber,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSupplierQuality = `-- name: InsertSupplierQuality :one

INSERT INTO supplier_quality (company_id, supplier_id, status, quality_rating, risk_level,
                              approved_date, expiry_date, last_audit_date, next_audit_date, notes, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type InsertSupplierQualityParams struct {
	CompanyID     int64       `json:"company_id"`
	SupplierID    int64       `json:"supplier_id"`
	Status        string      `json:"status"`
	QualityRating float64     `json:"quality_rating"`
	RiskLevel     string      `json:"risk_level"`
	ApprovedDate  pgtype.Date `json:"approved_date"`
	ExpiryDate    pgtype.Date `json:"expiry_date"`
	LastAuditDate pgtype.Date `json:"last_audit_date"`
	NextAuditDate pgtype.Date `json:"next_audit_date"`
	Notes         pgtype.Text `json:"notes"`
	CreatedBy     int64       `json:"created_by"`
}

// =============================================================================
// SUPPLIER QUALITY
// =============================================================================
func (q *Queries) InsertSupplierQuality(ctx context.Context, arg InsertSupplierQualityParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertSupplierQuality,
		arg.CompanyID,
		arg.SupplierID,
		arg.Status,
		arg.QualityRating,
		arg.RiskLevel,
		arg.ApprovedDate,
		arg.ExpiryDate,
		arg.LastAuditDate,
		arg.NextAuditDate,
		arg.Notes,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAuditFindings = `-- name: ListAuditFindings :many
SELECT id, audit_id, finding_number, category, clause, description, evidence,
       requirement, risk_level, status, response, response_due_date, response_date,
       assigned_to, verified_by, verified_at, created_at, updated_at
FROM audit_findings
WHERE audit_id = $1
ORDER BY created_at
`

func (q *Queries) ListAuditFindings(ctx context.Context, auditID int64) ([]AuditFinding, error) {
	rows, err := q.db.Query(ctx, listAuditFindings, auditID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditFinding
	for rows.Next() {
		var i AuditFinding
		if err := rows.Scan(
			&i.ID,
			&i.AuditID,
			&i.FindingNumber,
			&i.Category,
			&i.Clause,
			&i.Description,
			&i.Evidence,
			&i.Requirement,
			&i.RiskLevel,
			&i.Status,
			&i.Response,
			&i.ResponseDueDate,
			&i.ResponseDate,
			&i.AssignedTo,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAudits = `-- name: ListAudits :many
SELECT id, company_id, number, title, description, audit_type, status, standard,
       scope, lead_auditor_id, audit_team_ids, auditee_id,
       planned_start, planned_end, actual_start, actual_end,
       report_number, report_date, created_by, created_at, updated_at
FROM audits
WHERE company_id = $1
  AND ($2::text IS NULL OR status = $2)
  AND ($3::text IS NULL OR audit_type = $3)
ORDER BY planned_start DESC NULLS LAST
LIMIT $4 OFFSET $5
`

type ListAuditsParams struct {
	CompanyID int64  `json:"company_id"`
	Column2   string `json:"column_2"`
	Column3   string `json:"column_3"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListAudits(ctx context.Context, arg ListAuditsParams) ([]Audit, error) {
	rows, err := q.db.Query(ctx, listAudits,
		arg.CompanyID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Audit
	for rows.Next() {
		var i Audit
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.AuditType,
			&i.Status,
			&i.Standard,
			&i.Scope,
			&i.LeadAuditorID,
			&i.AuditTeamIds,
			&i.AuditeeID,
			&i.PlannedStart,
			&i.PlannedEnd,
			&i.ActualStart,
			&i.ActualEnd,
			&i.ReportNumber,
			&i.ReportDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCAPAs = `-- name: ListCAPAs :many
SELECT id, company_id, number, title, description, source_type, source_id, source_reference,
       status, priority, owner_id, team_members, root_cause, root_cause_method,
       corrective_action, preventive_action, verification_method, verification_result,
       effectiveness_check, target_date, completion_date, effectiveness_date,
       created_by, created_at, updated_at
FROM capas
WHERE company_id = $1
  AND ($2::text IS NULL OR source_type = $2)
  AND ($3::text IS NULL OR status = $3)
  AND ($4::text IS NULL OR priority = $4)
  AND ($5::int8 IS NULL OR owner_id = $5)
  AND ($6::timestamptz IS NULL OR created_at >= $6)
  AND ($7::timestamptz IS NULL OR created_at <= $7)
ORDER BY created_at DESC
LIMIT $8 OFFSET $9
`

type ListCAPAsParams struct {
	CompanyID int64              `json:"company_id"`
	Column2   string             `json:"column_2"`
	Column3   string             `json:"column_3"`
	Column4   string             `json:"column_4"`
	Column5   int64              `json:"column_5"`
	Column6   pgtype.Timestamptz `json:"column_6"`
	Column7   pgtype.Timestamptz `json:"column_7"`
	Limit     int32              `json:"limit"`
	Offset    int32              `json:"offset"`
}

func (q *Queries) ListCAPAs(ctx context.Context, arg ListCAPAsParams) ([]Capa, error) {
	rows, err := q.db.Query(ctx, listCAPAs,
		arg.CompanyID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capa
	for rows.Next() {
		var i Capa
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.SourceType,
			&i.SourceID,
			&i.SourceReference,
			&i.Status,
			&i.Priority,
			&i.OwnerID,
			&i.TeamMembers,
			&i.RootCause,
			&i.RootCauseMethod,
			&i.CorrectiveAction,
			&i.PreventiveAction,
			&i.VerificationMethod,
			&i.VerificationResult,
			&i.EffectivenessCheck,
			&i.TargetDate,
			&i.CompletionDate,
			&i.EffectivenessDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerComplaints = `-- name: ListCustomerComplaints :many
SELECT id, company_id, complaint_number, customer_id, title, description,
       status, severity, assigned_to, response_evidence, received_at, closed_at,
       created_by, created_at, updated_at
FROM customer_complaints
WHERE company_id = $1
  AND ($2::text IS NULL OR status = $2)
  AND ($3::text IS NULL OR severity = $3)
  AND ($4::int8 IS NULL OR customer_id = $4)
ORDER BY received_at DESC
LIMIT $5 OFFSET $6
`

type ListCustomerComplaintsParams struct {
	CompanyID int64  `json:"company_id"`
	Column2   string `json:"column_2"`
	Column3   string `json:"column_3"`
	Column4   int64  `json:"column_4"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type ListCustomerComplaintsRow struct {
	ID               int64              `json:"id"`
	CompanyID        int64              `json:"company_id"`
	ComplaintNumber  string             `json:"complaint_number"`
	CustomerID       int64              `json:"customer_id"`
	Title            string             `json:"title"`
	Description      string             `json:"description"`
	Status           string             `json:"status"`
	Severity         string             `json:"severity"`
	AssignedTo       pgtype.Int8        `json:"assigned_to"`
	ResponseEvidence pgtype.Text        `json:"response_evidence"`
	ReceivedAt       pgtype.Timestamptz `json:"received_at"`
	ClosedAt         pgtype.Timestamptz `json:"closed_at"`
	CreatedBy        int64              `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCustomerComplaints(ctx context.Context, arg ListCustomerComplaintsParams) ([]ListCustomerComplaintsRow, error) {
	rows, err := q.db.Query(ctx, listCustomerComplaints,
		arg.CompanyID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomerComplaintsRow
	for rows.Next() {
		var i ListCustomerComplaintsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ComplaintNumber,
			&i.CustomerID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Severity,
			&i.AssignedTo,
			&i.ResponseEvidence,
			&i.ReceivedAt,
			&i.ClosedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNCRs = `-- name: ListNCRs :many
SELECT id, company_id, number, title, description, source_type, source_id, source_reference,
       category, severity, status, detected_by, detected_at, detected_location,
       responsible_party_id, assigned_to, target_closure_date, actual_closure_date,
       root_cause, containment_action, created_by, created_at, updated_at
FROM ncrs
WHERE company_id = $1
  AND ($2::text IS NULL OR source_type = $2)
  AND ($3::text IS NULL OR category = $3)
  AND ($4::text IS NULL OR severity = $4)
  AND ($5::text IS NULL OR status = $5)
  AND ($6::int8 IS NULL OR assigned_to = $6)
  AND ($7::timestamptz IS NULL OR detected_at >= $7)
  AND ($8::timestamptz IS NULL OR detected_at <= $8)
ORDER BY detected_at DESC
LIMIT $9 OFFSET $10
`

type ListNCRsParams struct {
	CompanyID int64              `json:"company_id"`
	Column2   string             `json:"column_2"`
	Column3   string             `json:"column_3"`
	Column4   string             `json:"column_4"`
	Column5   string             `json:"column_5"`
	Column6   int64              `json:"column_6"`
	Column7   pgtype.Timestamptz `json:"column_7"`
	Column8   pgtype.Timestamptz `json:"column_8"`
	Limit     int32              `json:"limit"`
	Offset    int32              `json:"offset"`
}

func (q *Queries) ListNCRs(ctx context.Context, arg ListNCRsParams) ([]Ncr, error) {
	rows, err := q.db.Query(ctx, listNCRs,
		arg.CompanyID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ncr
	for rows.Next() {
		var i Ncr
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.SourceType,
			&i.SourceID,
			&i.SourceReference,
			&i.Category,
			&i.Severity,
			&i.Status,
			&i.DetectedBy,
			&i.DetectedAt,
			&i.DetectedLocation,
			&i.ResponsiblePartyID,
			&i.AssignedTo,
			&i.TargetClosureDate,
			&i.ActualClosureDate,
			&i.RootCause,
			&i.ContainmentAction,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQMSHolds = `-- name: ListQMSHolds :many
SELECT id, company_id, reference_module, reference_id, reason, status, created_by, created_at, released_by, released_at
FROM qms_holds
WHERE company_id = $1
  AND ($2::text IS NULL OR reference_module = $2)
  AND ($3::int8 IS NULL OR reference_id = $3)
ORDER BY created_at DESC
`

type ListQMSHoldsParams struct {
	CompanyID int64  `json:"company_id"`
	Column2   string `json:"column_2"`
	Column3   int64  `json:"column_3"`
}

func (q *Queries) ListQMSHolds(ctx context.Context, arg ListQMSHoldsParams) ([]QmsHold, error) {
	rows, err := q.db.Query(ctx, listQMSHolds, arg.CompanyID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QmsHold
	for rows.Next() {
		var i QmsHold
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ReferenceModule,
			&i.ReferenceID,
			&i.Reason,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ReleasedBy,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQMSInspectionResults = `-- name: ListQMSInspectionResults :many
SELECT id, company_id, inspection_id, characteristic_name, expected_value, actual_value, is_conforming, notes, created_by, created_at
FROM qms_inspection_results
WHERE inspection_id = $1
ORDER BY created_at ASC
`

type ListQMSInspectionResultsRow struct {
	ID                 int64              `json:"id"`
	CompanyID          int64              `json:"company_id"`
	InspectionID       int64              `json:"inspection_id"`
	CharacteristicName string             `json:"characteristic_name"`
	ExpectedValue      pgtype.Text        `json:"expected_value"`
	ActualValue        pgtype.Text        `json:"actual_value"`
	IsConforming       bool               `json:"is_conforming"`
	Notes              pgtype.Text        `json:"notes"`
	CreatedBy          int64              `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListQMSInspectionResults(ctx context.Context, inspectionID int64) ([]ListQMSInspectionResultsRow, error) {
	rows, err := q.db.Query(ctx, listQMSInspectionResults, inspectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQMSInspectionResultsRow
	for rows.Next() {
		var i ListQMSInspectionResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.InspectionID,
			&i.CharacteristicName,
			&i.ExpectedValue,
			&i.ActualValue,
			&i.IsConforming,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQMSInspections = `-- name: ListQMSInspections :many
SELECT id, company_id, name, description, reference_module, reference_id,
       status, inspector_id, scheduled_at, started_at, completed_at,
       created_by, created_at, updated_at
FROM qms_inspections
WHERE company_id = $1
  AND ($2::text IS NULL OR status = $2)
  AND ($3::text IS NULL OR reference_module = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListQMSInspectionsParams struct {
	CompanyID int64  `json:"company_id"`
	Column2   string `json:"column_2"`
	Column3   string `json:"column_3"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type ListQMSInspectionsRow struct {
	ID              int64              `json:"id"`
	CompanyID       int64              `json:"company_id"`
	Name            string             `json:"name"`
	Description     pgtype.Text        `json:"description"`
	ReferenceModule pgtype.Text        `json:"reference_module"`
	ReferenceID     pgtype.Int8        `json:"reference_id"`
	Status          string             `json:"status"`
	InspectorID     pgtype.Int8        `json:"inspector_id"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	CreatedBy       int64              `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListQMSInspections(ctx context.Context, arg ListQMSInspectionsParams) ([]ListQMSInspectionsRow, error) {
	rows, err := q.db.Query(ctx, listQMSInspections,
		arg.CompanyID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQMSInspectionsRow
	for rows.Next() {
		var i ListQMSInspectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Description,
			&i.ReferenceModule,
			&i.ReferenceID,
			&i.Status,
			&i.InspectorID,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQualityObjectiveMeasurements = `-- name: ListQualityObjectiveMeasurements :many
SELECT id, objective_id, value, measurement_date, notes, recorded_by, created_at
FROM quality_objective_measurements
WHERE objective_id = $1
ORDER BY measurement_date DESC
LIMIT $2
`

type ListQualityObjectiveMeasurementsParams struct {
	ObjectiveID int64 `json:"objective_id"`
	Limit       int32 `json:"limit"`
}

func (q *Queries) ListQualityObjectiveMeasurements(ctx context.Context, arg ListQualityObjectiveMeasurementsParams) ([]QualityObjectiveMeasurement, error) {
	rows, err := q.db.Query(ctx, listQualityObjectiveMeasurements, arg.ObjectiveID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QualityObjectiveMeasurement
	for rows.Next() {
		var i QualityObjectiveMeasurement
		if err := rows.Scan(
			&i.ID,
			&i.ObjectiveID,
			&i.Value,
			&i.MeasurementDate,
			&i.Notes,
			&i.RecordedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQualityObjectives = `-- name: ListQualityObjectives :many
SELECT id, company_id, name, description, metric_type, target_value, current_value,
       unit, frequency, owner_id, status, start_date, end_date, created_at, updated_at
FROM quality_objectives
WHERE company_id = $1
  AND ($2::text IS NULL OR status = $2)
ORDER BY name
`

type ListQualityObjectivesParams struct {
	CompanyID int64  `json:"company_id"`
	Column2   string `json:"column_2"`
}

func (q *Queries) ListQualityObjectives(ctx context.Context, arg ListQualityObjectivesParams) ([]QualityObjective, error) {
	rows, err := q.db.Query(ctx, listQualityObjectives, arg.CompanyID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QualityObjective
	for rows.Next() {
		var i QualityObjective
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Description,
			&i.MetricType,
			&i.TargetValue,
			&i.CurrentValue,
			&i.Unit,
			&i.Frequency,
			&i.OwnerID,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierAudits = `-- name: ListSupplierAudits :many
SELECT id, company_id, supplier_id, audit_number, audit_type, status, standard,
       planned_date, actual_date, score, lead_auditor_id, report_number, created_by, created_at, updated_at
FROM supplier_audits
WHERE company_id = $1
  AND ($2::int8 IS NULL OR supplier_id = $2)
ORDER BY planned_date DESC NULLS LAST
LIMIT $3 OFFSET $4
`

type ListSupplierAuditsParams struct {
	CompanyID int64 `json:"company_id"`
	Column2   int64 `json:"column_2"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListSupplierAudits(ctx context.Context, arg ListSupplierAuditsParams) ([]SupplierAudit, error) {
	rows, err := q.db.Query(ctx, listSupplierAudits,
		arg.CompanyID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplierAudit
	for rows.Next() {
		var i SupplierAudit
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SupplierID,
			&i.AuditNumber,
			&i.AuditType,
			&i.Status,
			&i.Standard,
			&i.PlannedDate,
			&i.ActualDate,
			&i.Score,
			&i.LeadAuditorID,
			&i.ReportNumber,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierQuality = `-- name: ListSupplierQuality :many
SELECT id, company_id, supplier_id, status, quality_rating, risk_level,
       approved_date, expiry_date, last_audit_date, next_audit_date, notes, created_by, created_at, updated_at
FROM supplier_quality
WHERE company_id = $1
  AND ($2::text IS NULL OR status = $2)
ORDER BY supplier_id
LIMIT $3 OFFSET $4
`

type ListSupplierQualityParams struct {
	CompanyID int64  `json:"company_id"`
	Column2   string `json:"column_2"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListSupplierQuality(ctx context.Context, arg ListSupplierQualityParams) ([]SupplierQuality, error) {
	rows, err := q.db.Query(ctx, listSupplierQuality,
		arg.CompanyID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplierQuality
	for rows.Next() {
		var i SupplierQuality
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SupplierID,
			&i.Status,
			&i.QualityRating,
			&i.RiskLevel,
			&i.ApprovedDate,
			&i.ExpiryDate,
			&i.LastAuditDate,
			&i.NextAuditDate,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const qMSUpdateCAPAStatus = `-- name: QMSUpdateCAPAStatus :exec
UPDATE capas
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type QMSUpdateCAPAStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) QMSUpdateCAPAStatus(ctx context.Context, arg QMSUpdateCAPAStatusParams) error {
	_, err := q.db.Exec(ctx, qMSUpdateCAPAStatus, arg.ID, arg.Status)
	return err
}

const qMSUpdateNCRStatus = `-- name: QMSUpdateNCRStatus :exec
UPDATE ncrs
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type QMSUpdateNCRStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) QMSUpdateNCRStatus(ctx context.Context, arg QMSUpdateNCRStatusParams) error {
	_, err := q.db.Exec(ctx, qMSUpdateNCRStatus, arg.ID, arg.Status)
	return err
}

const releaseQMSHold = `-- name: ReleaseQMSHold :exec
UPDATE qms_holds
SET status = 'RELEASED', released_by = $2, released_at = NOW()
WHERE id = $1 AND company_id = $3 AND status = 'ACTIVE'
`

type ReleaseQMSHoldParams struct {
	ID         int64       `json:"id"`
	ReleasedBy pgtype.Int8 `json:"released_by"`
	CompanyID  int64       `json:"company_id"`
}

func (q *Queries) ReleaseQMSHold(ctx context.Context, arg ReleaseQMSHoldParams) error {
	_, err := q.db.Exec(ctx, releaseQMSHold, arg.ID, arg.ReleasedBy, arg.CompanyID)
	return err
}

const updateAudit = `-- name: UpdateAudit :exec
UPDATE audits
SET title = $2, description = $3, scope = $4, lead_auditor_id = $5,
    audit_team_ids = $6, auditee_id = $7, planned_start = $8, planned_end = $9, updated_at = NOW()
WHERE id = $1
`

type UpdateAuditParams struct {
	ID            int64       `json:"id"`
	Title         string      `json:"title"`
	Description   pgtype.Text `json:"description"`
	Scope         pgtype.Text `json:"scope"`
	LeadAuditorID int64       `json:"lead_auditor_id"`
	AuditTeamIds  []int64     `json:"audit_team_ids"`
	AuditeeID     pgtype.Int8 `json:"auditee_id"`
	PlannedStart  pgtype.Date `json:"planned_start"`
	PlannedEnd    pgtype.Date `json:"planned_end"`
}

func (q *Queries) UpdateAudit(ctx context.Context, arg UpdateAuditParams) error {
	_, err := q.db.Exec(ctx, updateAudit,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Scope,
		arg.LeadAuditorID,
		arg.AuditTeamIds,
		arg.AuditeeID,
		arg.PlannedStart,
		arg.PlannedEnd,
	)
	return err
}

const updateAuditFinding = `-- name: UpdateAuditFinding :exec
UPDATE audit_findings
SET category = $2, description = $3, evidence = $4, requirement = $5, risk_level = $6,
    status = $7, response = $8, response_due_date = $9, assigned_to = $10,
    verified_by = $11, verified_at = $12, updated_at = NOW()
WHERE id = $1
`

type UpdateAuditFindingParams struct {
	ID              int64              `json:"id"`
	Category        string             `json:"category"`
	Description     string             `json:"description"`
	Evidence        pgtype.Text        `json:"evidence"`
	Requirement     pgtype.Text        `json:"requirement"`
	RiskLevel       string             `json:"risk_level"`
	Status          string             `json:"status"`
	Response        pgtype.Text        `json:"response"`
	ResponseDueDate pgtype.Date        `json:"response_due_date"`
	AssignedTo      pgtype.Int8        `json:"assigned_to"`
	VerifiedBy      pgtype.Int8        `json:"verified_by"`
	VerifiedAt      pgtype.Timestamptz `json:"verified_at"`
}

func (q *Queries) UpdateAuditFinding(ctx context.Context, arg UpdateAuditFindingParams) error {
	_, err := q.db.Exec(ctx, updateAuditFinding,
		arg.ID,
		arg.Category,
		arg.Description,
		arg.Evidence,
		arg.Requirement,
		arg.RiskLevel,
		arg.Status,
		arg.Response,
		arg.ResponseDueDate,
		arg.AssignedTo,
		arg.VerifiedBy,
		arg.VerifiedAt,
	)
	return err
}

const updateCAPA = `-- name: UpdateCAPA :exec
UPDATE capas
SET title = $2, description = $3, priority = $4, owner_id = $5, team_members = $6,
    root_cause = $7, root_cause_method = $8, corrective_action = $9, preventive_action = $10,
    verification_method = $11, verification_result = $12, effectiveness_check = $13,
    target_date = $14, updated_at = NOW()
WHERE id = $1
`

type UpdateCAPAParams struct {
	ID                 int64       `json:"id"`
	Title              string      `json:"title"`
	Description        pgtype.Text `json:"description"`
	Priority           string      `json:"priority"`
	OwnerID            int64       `json:"owner_id"`
	TeamMembers        []int64     `json:"team_members"`
	RootCause          pgtype.Text `json:"root_cause"`
	RootCauseMethod    pgtype.Text `json:"root_cause_method"`
	CorrectiveAction   pgtype.Text `json:"corrective_action"`
	PreventiveAction   pgtype.Text `json:"preventive_action"`
	VerificationMethod pgtype.Text `json:"verification_method"`
	VerificationResult pgtype.Text `json:"verification_result"`
	EffectivenessCheck pgtype.Text `json:"effectiveness_check"`
	TargetDate         pgtype.Date `json:"target_date"`
}

func (q *Queries) UpdateCAPA(ctx context.Context, arg UpdateCAPAParams) error {
	_, err := q.db.Exec(ctx, updateCAPA,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.OwnerID,
		arg.TeamMembers,
		arg.RootCause,
		arg.RootCauseMethod,
		arg.CorrectiveAction,
		arg.PreventiveAction,
		arg.VerificationMethod,
		arg.VerificationResult,
		arg.EffectivenessCheck,
		arg.TargetDate,
	)
	return err
}

const updateCustomerComplaint = `-- name: UpdateCustomerComplaint :exec
UPDATE customer_complaints
SET title = $2, description = $3, severity = $4, assigned_to = $5,
    response_evidence = $6, updated_at = NOW()
WHERE id = $1
`

type UpdateCustomerComplaintParams struct {
	ID               int64       `json:"id"`
	Title            string      `json:"title"`
	Description      string      `json:"description"`
	Severity         string      `json:"severity"`
	AssignedTo       pgtype.Int8 `json:"assigned_to"`
	ResponseEvidence pgtype.Text `json:"response_evidence"`
}

func (q *Queries) UpdateCustomerComplaint(ctx context.Context, arg UpdateCustomerComplaintParams) error {
	_, err := q.db.Exec(ctx, updateCustomerComplaint,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Severity,
		arg.AssignedTo,
		arg.ResponseEvidence,
	)
	return err
}

const updateCustomerComplaintStatus = `-- name: UpdateCustomerComplaintStatus :exec
UPDATE customer_complaints
SET status = $2, closed_at = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateCustomerComplaintStatusParams struct {
	ID       int64              `json:"id"`
	Status   string             `json:"status"`
	ClosedAt pgtype.Timestamptz `json:"closed_at"`
}

func (q *Queries) UpdateCustomerComplaintStatus(ctx context.Context, arg UpdateCustomerComplaintStatusParams) error {
	_, err := q.db.Exec(ctx, updateCustomerComplaintStatus, arg.ID, arg.Status, arg.ClosedAt)
	return err
}

const updateLabSampleStatus = `-- name: UpdateLabSampleStatus :exec
UPDATE qms_lab_samples SET status = $2, completed_at = $3 WHERE id = $1
`

type UpdateLabSampleStatusParams struct {
	ID          int64              `json:"id"`
	Status      string             `json:"status"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateLabSampleStatus(ctx context.Context, arg UpdateLabSampleStatusParams) error {
	_, err := q.db.Exec(ctx, updateLabSampleStatus, arg.ID, arg.Status, arg.CompletedAt)
	return err
}

const updateNCR = `-- name: UpdateNCR :exec
UPDATE ncrs
SET title = $2, description = $3, category = $4, severity = $5,
    responsible_party_id = $6, assigned_to = $7, target_closure_date = $8,
    root_cause = $9, containment_action = $10, updated_at = NOW()
WHERE id = $1
`

type UpdateNCRParams struct {
	ID                 int64       `json:"id"`
	Title              string      `json:"title"`
	Description        pgtype.Text `json:"description"`
	Category           string      `json:"category"`
	Severity           string      `json:"severity"`
	ResponsiblePartyID pgtype.Int8 `json:"responsible_party_id"`
	AssignedTo         pgtype.Int8 `json:"assigned_to"`
	TargetClosureDate  pgtype.Date `json:"target_closure_date"`
	RootCause          pgtype.Text `json:"root_cause"`
	ContainmentAction  pgtype.Text `json:"containment_action"`
}

func (q *Queries) UpdateNCR(ctx context.Context, arg UpdateNCRParams) error {
	_, err := q.db.Exec(ctx, updateNCR,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Severity,
		arg.ResponsiblePartyID,
		arg.AssignedTo,
		arg.TargetClosureDate,
		arg.RootCause,
		arg.ContainmentAction,
	)
	return err
}

const updateQMSInspectionStatus = `-- name: UpdateQMSInspectionStatus :exec
UPDATE qms_inspections
SET status = $2, started_at = COALESCE(started_at, $3), completed_at = $4, updated_at = NOW()
WHERE id = $1
`

type UpdateQMSInspectionStatusParams struct {
	ID          int64              `json:"id"`
	Status      string             `json:"status"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateQMSInspectionStatus(ctx context.Context, arg UpdateQMSInspectionStatusParams) error {
	_, err := q.db.Exec(ctx, updateQMSInspectionStatus,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
	)
	return err
}

const updateQualityObjective = `-- name: UpdateQualityObjective :exec
UPDATE quality_objectives
SET name = $2, description = $3, target_value = $4, current_value = $5, owner_id = $6,
    status = $7, end_date = $8, updated_at = NOW()
WHERE id = $1
`

type UpdateQualityObjectiveParams struct {
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	TargetValue  float64     `json:"target_value"`
	CurrentValue float64     `json:"current_value"`
	OwnerID      int64       `json:"owner_id"`
	Status       string      `json:"status"`
	EndDate      pgtype.Date `json:"end_date"`
}

func (q *Queries) UpdateQualityObjective(ctx context.Context, arg UpdateQualityObjectiveParams) error {
	_, err := q.db.Exec(ctx, updateQualityObjective,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.TargetValue,
		arg.CurrentValue,
		arg.OwnerID,
		arg.Status,
		arg.EndDate,
	)
	return err
}

const updateSupplierQuality = `-- name: UpdateSupplierQuality :exec
UPDATE supplier_quality
SET status = $2, quality_rating = $3, risk_level = $4, approved_date = $5,
    expiry_date = $6, last_audit_date = $7, next_audit_date = $8, notes = $9, updated_at = NOW()
WHERE id = $1
`

type UpdateSupplierQualityParams struct {
	ID            int64       `json:"id"`
	Status        string      `json:"status"`
	QualityRating float64     `json:"quality_rating"`
	RiskLevel     string      `json:"risk_level"`
	ApprovedDate  pgtype.Date `json:"approved_date"`
	ExpiryDate    pgtype.Date `json:"expiry_date"`
	LastAuditDate pgtype.Date `json:"last_audit_date"`
	NextAuditDate pgtype.Date `json:"next_audit_date"`
	Notes         pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateSupplierQuality(ctx context.Context, arg UpdateSupplierQualityParams) error {
	_, err := q.db.Exec(ctx, updateSupplierQuality,
		arg.ID,
		arg.Status,
		arg.QualityRating,
		arg.RiskLevel,
		arg.ApprovedDate,
		arg.ExpiryDate,
		arg.LastAuditDate,
		arg.NextAuditDate,
		arg.Notes,
	)
	return err
}
