// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac_scoped.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const rbacCompleteAccessReview = `-- name: RbacCompleteAccessReview :one
UPDATE rbac_access_reviews
SET status = 'COMPLETED',
    decision = $1,
    decided_by_user_id = $2,
    decided_at = NOW(),
    updated_at = NOW()
WHERE company_id = $3
  AND id = $4
  AND status = 'OPEN'
RETURNING id, company_id, subject_user_id, review_key, status, decision,
          opened_by_user_id, decided_by_user_id, decided_at, created_at, updated_at
`

type RbacCompleteAccessReviewParams struct {
	Decision        pgtype.Text `json:"decision"`
	DecidedByUserID pgtype.Int8 `json:"decided_by_user_id"`
	CompanyID       int64       `json:"company_id"`
	ID              int64       `json:"id"`
}

func (q *Queries) RbacCompleteAccessReview(ctx context.Context, arg RbacCompleteAccessReviewParams) (RbacAccessReview, error) {
	row := q.db.QueryRow(ctx, rbacCompleteAccessReview,
		arg.Decision,
		arg.DecidedByUserID,
		arg.CompanyID,
		arg.ID,
	)
	var i RbacAccessReview
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SubjectUserID,
		&i.ReviewKey,
		&i.Status,
		&i.Decision,
		&i.OpenedByUserID,
		&i.DecidedByUserID,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rbacCreateScopedRoleAssignment = `-- name: RbacCreateScopedRoleAssignment :one
INSERT INTO rbac_user_role_assignments (
    company_id,
    user_id,
    role_id,
    branch_id,
    valid_from,
    valid_to
)
VALUES (
    $1,
    $2,
    $3,
    $4::bigint,
    $5::timestamptz,
    $6::timestamptz
)
RETURNING id, company_id, user_id, role_id, branch_id, valid_from, valid_to, created_at
`

type RbacCreateScopedRoleAssignmentParams struct {
	CompanyID int64              `json:"company_id"`
	UserID    int64              `json:"user_id"`
	RoleID    int64              `json:"role_id"`
	BranchID  pgtype.Int8        `json:"branch_id"`
	ValidFrom pgtype.Timestamptz `json:"valid_from"`
	ValidTo   pgtype.Timestamptz `json:"valid_to"`
}

func (q *Queries) RbacCreateScopedRoleAssignment(ctx context.Context, arg RbacCreateScopedRoleAssignmentParams) (RbacUserRoleAssignment, error) {
	row := q.db.QueryRow(ctx, rbacCreateScopedRoleAssignment,
		arg.CompanyID,
		arg.UserID,
		arg.RoleID,
		arg.BranchID,
		arg.ValidFrom,
		arg.ValidTo,
	)
	var i RbacUserRoleAssignment
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.RoleID,
		&i.BranchID,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedAt,
	)
	return i, err
}

const rbacDeleteScopedRoleAssignment = `-- name: RbacDeleteScopedRoleAssignment :execrows
DELETE FROM rbac_user_role_assignments
WHERE company_id = $1
  AND id = $2
`

type RbacDeleteScopedRoleAssignmentParams struct {
	CompanyID int64 `json:"company_id"`
	ID        int64 `json:"id"`
}

func (q *Queries) RbacDeleteScopedRoleAssignment(ctx context.Context, arg RbacDeleteScopedRoleAssignmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, rbacDeleteScopedRoleAssignment, arg.CompanyID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rbacEffectivePermissionsInScope = `-- name: RbacEffectivePermissionsInScope :many
SELECT DISTINCT p.name
FROM rbac_user_role_assignments ura
JOIN role_permissions rp ON rp.role_id = ura.role_id
JOIN permissions p ON p.id = rp.permission_id
WHERE ura.user_id = $1
  AND ura.company_id = $2
  AND ura.valid_from <= $3::timestamptz
  AND (ura.valid_to IS NULL OR $3::timestamptz < ura.valid_to)
  AND (
      ($4::bigint IS NULL AND ura.branch_id IS NULL)
      OR
      ($4::bigint IS NOT NULL
          AND (ura.branch_id IS NULL OR ura.branch_id = $4::bigint))
  )
  AND (
      $4::bigint IS NULL
      OR EXISTS (
          SELECT 1
          FROM branches b
          WHERE b.id = $4::bigint
            AND b.company_id = $2
      )
  )
ORDER BY p.name
`

type RbacEffectivePermissionsInScopeParams struct {
	UserID    int64              `json:"user_id"`
	CompanyID int64              `json:"company_id"`
	At        pgtype.Timestamptz `json:"at"`
	BranchID  pgtype.Int8        `json:"branch_id"`
}

// Active-scope semantics:
//   - valid_from is inclusive;
//   - valid_to is exclusive;
//   - a NULL branch assignment is company-wide;
//   - a branch-scoped assignment is usable only for that branch;
//   - a company-level lookup never widens to a branch-scoped assignment.
//
// Legacy user_roles are intentionally not included here. They remain available
// through UserEffectivePermissions for compatibility with global callers.
func (q *Queries) RbacEffectivePermissionsInScope(ctx context.Context, arg RbacEffectivePermissionsInScopeParams) ([]string, error) {
	rows, err := q.db.Query(ctx, rbacEffectivePermissionsInScope,
		arg.UserID,
		arg.CompanyID,
		arg.At,
		arg.BranchID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rbacGetAccessReview = `-- name: RbacGetAccessReview :one
SELECT id, company_id, subject_user_id, review_key, status, decision,
       opened_by_user_id, decided_by_user_id, decided_at, created_at, updated_at
FROM rbac_access_reviews
WHERE company_id = $1
  AND id = $2
`

type RbacGetAccessReviewParams struct {
	CompanyID int64 `json:"company_id"`
	ID        int64 `json:"id"`
}

func (q *Queries) RbacGetAccessReview(ctx context.Context, arg RbacGetAccessReviewParams) (RbacAccessReview, error) {
	row := q.db.QueryRow(ctx, rbacGetAccessReview, arg.CompanyID, arg.ID)
	var i RbacAccessReview
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SubjectUserID,
		&i.ReviewKey,
		&i.Status,
		&i.Decision,
		&i.OpenedByUserID,
		&i.DecidedByUserID,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rbacListOpenAccessReviews = `-- name: RbacListOpenAccessReviews :many
SELECT id, company_id, subject_user_id, review_key, status, decision,
       opened_by_user_id, decided_by_user_id, decided_at, created_at, updated_at
FROM rbac_access_reviews
WHERE company_id = $1
  AND status = 'OPEN'
ORDER BY created_at ASC, id ASC
`

func (q *Queries) RbacListOpenAccessReviews(ctx context.Context, companyID int64) ([]RbacAccessReview, error) {
	rows, err := q.db.Query(ctx, rbacListOpenAccessReviews, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RbacAccessReview
	for rows.Next() {
		var i RbacAccessReview
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SubjectUserID,
			&i.ReviewKey,
			&i.Status,
			&i.Decision,
			&i.OpenedByUserID,
			&i.DecidedByUserID,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rbacListScopedRoleAssignments = `-- name: RbacListScopedRoleAssignments :many
SELECT id, company_id, user_id, role_id, branch_id, valid_from, valid_to, created_at
FROM rbac_user_role_assignments
WHERE company_id = $1
  AND user_id = $2
ORDER BY valid_from DESC, id DESC
`

type RbacListScopedRoleAssignmentsParams struct {
	CompanyID int64 `json:"company_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) RbacListScopedRoleAssignments(ctx context.Context, arg RbacListScopedRoleAssignmentsParams) ([]RbacUserRoleAssignment, error) {
	rows, err := q.db.Query(ctx, rbacListScopedRoleAssignments, arg.CompanyID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RbacUserRoleAssignment
	for rows.Next() {
		var i RbacUserRoleAssignment
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.RoleID,
			&i.BranchID,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rbacOpenAccessReview = `-- name: RbacOpenAccessReview :one
INSERT INTO rbac_access_reviews (
    company_id,
    subject_user_id,
    review_key,
    opened_by_user_id
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (company_id, subject_user_id, review_key)
DO UPDATE SET review_key = EXCLUDED.review_key
RETURNING id, company_id, subject_user_id, review_key, status, decision,
          opened_by_user_id, decided_by_user_id, decided_at, created_at, updated_at
`

type RbacOpenAccessReviewParams struct {
	CompanyID      int64  `json:"company_id"`
	SubjectUserID  int64  `json:"subject_user_id"`
	ReviewKey      string `json:"review_key"`
	OpenedByUserID int64  `json:"opened_by_user_id"`
}

func (q *Queries) RbacOpenAccessReview(ctx context.Context, arg RbacOpenAccessReviewParams) (RbacAccessReview, error) {
	row := q.db.QueryRow(ctx, rbacOpenAccessReview,
		arg.CompanyID,
		arg.SubjectUserID,
		arg.ReviewKey,
		arg.OpenedByUserID,
	)
	var i RbacAccessReview
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SubjectUserID,
		&i.ReviewKey,
		&i.Status,
		&i.Decision,
		&i.OpenedByUserID,
		&i.DecidedByUserID,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
